### ISSUE TITLE
Optifine doesn't load

### ISSUE THREAD

**Issue by Arnold1338** [CleanroomMC/Cleanroom#105]
### Your CleanroomMC Discord Username

godofhonor (user) / МелкаяЧувырла (displayed)

### Cleanroom Version

14.23.5.0 (Latest experimental branch)

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

Prism launcher
Optifine doesn't make any differences ingame other from text in left down corner
Optifine works on stable branch, but fugue crashes it
https://mclo.gs/pN6w9SD (Latest)
https://mclo.gs/YxcwUWv (Debug)

### Mod List

Fugue, Optifine G6_pre1

### MMC Instance Notes

This instance is built using Github Action.
Using installer artifact from commit: d430777e2bcb886d1c2ff141e9fd630d432d388f
Action URL: https://github.com/CleanroomMC/Cleanroom/actions/runs/8447096314

### Final Checklist

- [x] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fixed this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Try add `optifine.OptiFineClassTransformer` to getCodeSource list in fugue.cfg

**Comment by Arnold1338** [comment]
Still the same issue
https://mclo.gs/VOlHT4L
Fugue crashes stable even without an Optifine

**Comment by kappa-maintainer** [comment]
Optifine won't be officially supported, but I do have personal interest to see why it can't even boot
So where did you get G6? I can't find it on official website

**Comment by Arnold1338** [comment]
Preview versions of optifine, official site
![изображение](https://github.com/CleanroomMC/Cleanroom/assets/37241096/4121fc0d-e22d-443c-9b1f-fcef3c954b1b)

**Comment by kappa-maintainer** [comment]
Fixed in https://github.com/CleanroomMC/Fugue/releases/tag/0.12.2
Remember to reset your config
