### ISSUE TITLE
Faild too boot in Arch linux

### ISSUE THREAD

**Issue by s0u7a** [CleanroomMC/Cleanroom#106]
### Cleanroom Version

14.23.5.2860

### Java Version

Java 21

### Graphics Card Vendor

Intel iGPU

### Bug Report

Log:https://mclo.gs/an6tdC3 I downloaded the latest version of Vintagium and cleanroomlauncher and am running it with Java 21 (extra/jre21-openjdk) Without Vintagium it works.
please see this : https://github.com/Asek3/sodium-1.12/issues/35

### Mod List

vintagium

### MMC Instance Notes

This instance is built using Github Action.\nUsing installer artifact from commit: a008ef1b8b022193ba14a39d4a20484d0eab7cb0\nAction URL: https://github.com/CleanroomMC/Cleanroom/actions/runs/8494989842

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fixed this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by s0u7a** [comment]
Using the latest STABLE has solved the problem! However, I will keep this issue as I think the logs will be useful for development.

**Comment by kappa-maintainer** [comment]
Fixed in latest cleanroom

**Comment by s0u7a** [comment]
Thank you
