### ISSUE TITLE
Crash with `Foundation`

### ISSUE THREAD

**Issue by Ecdcaeb** [CleanroomMC/Cleanroom#108]
### Your CleanroomMC Discord Username

Hileb

### Cleanroom Version

15.24.0.3029 | https://github.com/CleanroomMC/Cleanroom/actions/runs/8564080798

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

https://mclo.gs/Ur73iva
https://mclo.gs/a5cA6TY

### Mod List

+Fugue-1.12.2-0.12.4-beta

3030 is the folder name, the version of cleanroom is https://github.com/CleanroomMC/Cleanroom/actions/runs/8564080798 (3029)

### MMC Instance Notes

-

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fixed this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Use 0.5.4
