### ISSUE TITLE
Crash with `Sword Art Online UI`

### ISSUE THREAD

**Issue by Ecdcaeb** [CleanroomMC/Cleanroom#109]
### Your CleanroomMC Discord Username

Hileb

### Cleanroom Version

15.24.0.3026

### Java Version

Java 21

### Graphics Card Vendor

NVidia

#### Original
https://mclo.gs/MzYHIvX

#### Abstract
```
Caused by: jakarta.xml.bind.JAXBException: Implementation of Jakarta XML Binding-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: org.glassfish.jaxb.runtime.v2.ContextFactory]
	at jakarta.xml.bind.ContextFinder.newInstance(ContextFinder.java:250)
```

#### Related
https://github.com/Bluexin/saoui/blob/2.0-1.12-features/src/main/java/com/tencao/saoui/themes/XmlThemeLoader.kt
Oh, `javax.xml.bind.JAXBContext` for java 21!
We need Fugue!

### Mod List

| LCH   | minecraft            | 1.12.2     | minecraft.jar                            | None      |
| LCH   | mcp                    | 9.42        | minecraft.jar                            | None      |
| LCH   | configanytime    | 2.0          | minecraft.jar                            | None      |
| LCH   | FML                    | 8.0.99.99 | cleanroom-15.24.0.3026.jar   | None      |
| LCH   | forge                  | 14.23.5.0 | cleanroom-15.24.0.3026.jar   | None      |
| LCH   | mixinbooter       | 10.0        | minecraft.jar                           | None      |
| LCH   | forgelin              | 1.8.4       | Forgelin-1.8.4.jar                     | None      |
| LCH   | librarianlib         | 4.22        | librarianlib-1.12.2-4.22.jar      | None      |
| LCH   | saomclib            | 1.4.10     | saomclib-1.12.2-1.4.10.jar      | None      |
| LCE    | saoui                 | 2.1.9       | saoui-1.12.2-2.1.9.jar              | None      |
| LC      | librarianliblate  | 4.22        | librarianlib-1.12.2-4.22.jar       | None      |

### MMC Instance Notes

Do not use MMC instance pack.

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fixed this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
3026 is not supported.
We have got jakarta xml for a long time.
