### ISSUE TITLE
NoClassDefFoundError: scala/collection/Seq

### ISSUE THREAD

**Issue by UraraChiya** [CleanroomMC/Cleanroom#110]
### Cleanroom Version

15.24.0.3035

### Java Version

Java 21

### Graphics Card Vendor

Intel iGPU

### Bug Report

crash-2024-04-07_21.32.02-client.txt: https://mclo.gs/ELs3N5a

### Mod List

       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                                | Version              | Source                                             | Signature |
       |:----- |:--------------------------------- |:-------------------- |:-------------------------------------------------- |:--------- |
       | LC    | minecraft                         | 1.12.2               | minecraft.jar                                      | None      |
       | LC    | mcp                               | 9.42                 | minecraft.jar                                      | None      |
       | LC    | configanytime                     | 2.0                  | minecraft.jar                                      | None      |
       | LC    | FML                               | 8.0.99.99            | cleanroom-15.24.0.3035-universal.jar               | None      |
       | LC    | forge                             | 14.23.5.2860         | cleanroom-15.24.0.3035-universal.jar               | None      |
       | LC    | creativecoredummy                 | 1.0.0                | minecraft.jar                                      | None      |
       | LC    | hecharacters                      | @VERSION@            | hecharacters-1.12.2-1.4.1.jar                      | None      |
       | LC    | jecharacters                      | 1.12.0-3.7.2         | jecharacters-1.12.0-3.7.2.jar                      | None      |
       | LC    | littletilescore                   | 1.0.0                | minecraft.jar                                      | None      |
       | LC    | smoothfontcore                    | mc1.12.2-2.1.4       | minecraft.jar                                      | None      |
       | LC    | mixinbooter                       | 10.0                 | minecraft.jar                                      | None      |
       | LC    | smoothfont                        | mc1.12.2-2.1.4       | SmoothFont-mc1.12.2-2.1.4.jar                      | None      |
       | LC    | redcore                           | 0.6-Dev-3            | !Red-Core-MC-1.8-1.12-0.6-Dev-3.jar                | None      |
       | LC    | fugue                             | 1.12.2-0.14.0-beta   | +Fugue-1.12.2-0.14.0-beta.jar                      | None      |
       | LC    | actuallyadditions                 | 1.12.2-r152          | ActuallyAdditions-1.12.2-r152.jar                  | None      |
       | LC    | ctm                               | MC1.12.2-1.0.2.31    | CTM-MC1.12.2-1.0.2.31.jar                          | None      |
       | LC    | appliedenergistics2               | v0.56.4              | ae2-uel-v0.56.4.jar                                | None      |
       | L     | bdlib                             | 1.14.4.1             | bdlib-1.14.4.1-mc1.12.2.jar                        | None      |
       | L     | ae2stuff                          | 0.9                  | ae2stuff-1.12.2-0.9.jar                            | None      |
       | L     | architecturecraft                 | @VERSION@            | architecturecraft-1.12-3.108.jar                   | None      |
       | L     | crafttweaker                      | 4.1.20               | CraftTweaker2-1.12-4.1.20.697.jar                  | None      |
       | L     | mtlib                             | 3.0.7                | MTLib-3.0.7.jar                                    | None      |
       | L     | modtweaker                        | 4.0.19               | modtweaker-4.0.20.11.jar                           | None      |
       | L     | jei                               | 4.25.2               | HadEnoughItems_1.12.2-4.25.2.jar                   | None      |
       | L     | base                              | 3.14.0               | base-1.12.2-3.14.0.jar                             | None      |
       | L     | betteradvancements                | 0.1.0.77             | BetterAdvancements-1.12.2-0.1.0.77.jar             | None      |
       | L     | forgelin                          | 1.8.4                | Forgelin-1.8.4.jar                                 | None      |
       | L     | betterp2p                         | 1.12.2-1.3.2         | betterp2p-1.12.2-1.3.2.jar                         | None      |
       | L     | betterquesting                    | 4.2.2                | BetterQuestingUnofficial-4.2.2.jar                 | None      |
       | L     | buildinggadgets                   | 2.8.4                | BuildingGadgets-2.8.4.jar                          | None      |
       | L     | loliasm                           | 5.19                 | censoredasm5.19.jar                                | None      |
       | L     | chameleon                         | 1.12-4.1.3           | Chameleon-1.12-4.1.3.jar                           | None      |
       | L     | chesttransporter                  | 2.8.8                | ChestTransporter-1.12.2-2.8.8.jar                  | None      |
       | L     | chisel                            | MC1.12.2-1.0.2.45    | Chisel-MC1.12.2-1.0.2.45.jar                       | None      |
       | L     | classicbar                        | @VERSION@            | classicbar-0.5.4.jar                               | None      |
       | L     | codechickenlib                    | 3.2.3.358            | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | None      |
       | L     | contenttweaker                    | 1.12.2-4.10.0        | ContentTweaker-1.12.2-4.10.0.jar                   | None      |
       | L     | controlling                       | 3.0.10               | Controlling-3.0.12.2.jar                           | None      |
       | L     | craftingstation                   | @VERSION@            | craftingstation-0.1.8a.jar                         | None      |
       | L     | craftingtweaks                    | 8.1.9                | CraftingTweaks_1.12.2-8.1.9.jar                    | None      |
       | L     | ctgui                             | 1.0.0                | CraftTweaker2-1.12-4.1.20.697.jar                  | None      |
       | L     | crafttweakerjei                   | 2.0.3                | CraftTweaker2-1.12-4.1.20.697.jar                  | None      |
       | L     | creativecore                      | 1.10.0               | CreativeCore_v1.10.71_mc1.12.2.jar                 | None      |
       | L     | elevatorid                        | 1.3.14               | ElevatorMod-1.12.2-1.3.14.jar                      | None      |
       | L     | endercore                         | 1.12.2-0.5.78        | EnderCore-1.12.2-0.5.78.jar                        | None      |
       | L     | enderio                           | 5.3.72               | EnderIO-1.12.2-5.3.72.jar                          | None      |
       | L     | enderiointegrationtic             | 5.3.72               | EnderIO-1.12.2-5.3.72.jar                          | None      |
       | L     | enderiobase                       | 5.3.72               | EnderIO-1.12.2-5.3.72.jar                          | None      |
       | L     | enderioconduits                   | 5.3.72               | EnderIO-1.12.2-5.3.72.jar                          | None      |
       | L     | enderioconduitsappliedenergistics | 5.3.72               | EnderIO-1.12.2-5.3.72.jar                          | None      |
       | L     | enderioconduitsopencomputers      | 5.3.72               | EnderIO-1.12.2-5.3.72.jar                          | None      |
       | L     | enderioconduitsrefinedstorage     | 5.3.72               | EnderIO-1.12.2-5.3.72.jar                          | None      |
       | L     | enderiointegrationforestry        | 5.3.72               | EnderIO-1.12.2-5.3.72.jar                          | None      |
       | L     | enderiointegrationticlate         | 5.3.72               | EnderIO-1.12.2-5.3.72.jar                          | None      |
       | L     | enderioinvpanel                   | 5.3.72               | EnderIO-1.12.2-5.3.72.jar                          | None      |
       | L     | ftblib                            | 5.4.7.2              | FTBLib-5.4.7.2.jar                                 | None      |
       | L     | enderiomachines                   | 5.3.72               | EnderIO-1.12.2-5.3.72.jar                          | None      |
       | L     | enderiopowertools                 | 5.3.72               | EnderIO-1.12.2-5.3.72.jar                          | None      |
       | L     | enderioendergy                    | 5.3.72               | EnderIO-endergy-1.12.2-5.3.72.jar                  | None      |
       | L     | enderstorage                      | 2.4.9                | EnderStorage-1.12.2-2.4.9.jar                      | None      |
       | L     | enderutilities                    | 0.7.15               | enderutilities-1.12.2-0.7.15.jar                   | None      |
       | L     | extendedae                        | 1.12-0.0.1           | ExtendedAE-1.12-0.0.1.jar                          | None      |
       | L     | extrautils2                       | 1.0                  | extrautils2-1.12-1.9.9.jar                         | None      |
       | L     | ae2fc                             | 2.5.8-r              | Fluid Craft for AE2-2.5.8-r.jar                    | None      |
       | L     | libnine                           | 1.2.1                | libnine-1.12.2-1.2.1.jar                           | None      |
       | L     | storagedrawers                    | 5.5.0                | StorageDrawers-1.12.2-5.5.0.jar                    | None      |
       | L     | fluiddrawers                      | 1.0.7                | fluiddrawers-1.12.2-1.0.7.jar                      | None      |
       | L     | fpsreducer                        | mc1.12.2-1.20        | FpsReducer-mc1.12.2-1.20.jar                       | None      |
       | L     | framedcompactdrawers              | 1.2.7                | framedcompactdrawers-1.2.7.jar                     | None      |
       | L     | ftbutilities                      | 5.4.1.131            | FTBUtilities-5.4.1.131.jar                         | None      |
       | L     | futuremc                          | 0.2.6                | Future-MC-0.2.19.jar                               | None      |
       | L     | theoneprobe                       | 1.4.28               | theoneprobe-1.12-1.4.28.jar                        | None      |
       | L     | gregtech                          | 2.8.7-beta           | gregtech-1.12.2-2.8.7-beta.jar                     | None      |
       | L     | gcym                              | 1.2.8                | GregicalityMultiblocks-1.2.8.jar                   | None      |
       | L     | gregtechdrawers                   | 1.0.7                | gregtech-drawers-1.12.2-1.0.7.jar                  | None      |
       | L     | gregtechfoodoption                | 1.11.1               | gregtechfoodoption-1.12.2-1.11.1.jar               | None      |
       | L     | gtlitecore                        | 0.0.1-alpha          | gtlitecore-0.0.1-alpha.jar                         | None      |
       | L     | inventorytweaks                   | 1.64+dev.151.822d839 | InventoryTweaks-1.64+dev.151.jar                   | None      |
       | L     | ironchest                         | 1.12.2-7.0.67.844    | ironchest-1.12.2-7.0.72.847.jar                    | None      |
       | L     | jeiutilities                      | 0.2.12               | JEI-Utilities-1.12.2-0.2.12.jar                    | None      |
       | L     | jetif                             | 1.5.2                | jetif-1.12.2-1.5.2.jar                             | None      |
       | L     | journeymap                        | 1.12.2-5.7.1         | journeymap-1.12.2-5.7.1.jar                        | None      |
       | L     | jecalculation                     | 1.12.2-3.2.7         | JustEnoughCalculation-1.12.2-3.2.7.jar             | None      |
       | L     | jeresources                       | 0.9.3.203            | JustEnoughResources-1.12.2-0.9.3.203.jar           | None      |
       | L     | threng                            | 1.1.26               | lazy-ae2-1.12.2-1.1.26.jar                         | None      |
       | L     | lazyae2patch                      | 1.1.0                | lazy-ae2-patch-1.1.0.jar                           | None      |
       | L     | legendarytooltips                 | 1.1.9                | LegendaryTooltips-1.12.2-1.1.9.jar                 | None      |
       | L     | littletiles                       | 1.5.0                | LittleTiles_v1.5.87_mc1.12.2.jar                   | None      |
       | L     | moarsigns                         | 6.0.0.11             | MoarSigns-1.12.2-6.0.0.11.jar                      | None      |
       | L     | modernsplash                      | @VERSION@            | modernsplash-1.12.2-1.3.jar                        | None      |
       | L     | modnametooltip                    | 1.10.1               | modnametooltip_1.12.2-1.10.1.jar                   | None      |
       | L     | morefurnaces                      | 1.11.0               | MoreFurnaces-Nomifactory-Edition-1.12.2-1.11.0.jar | None      |
       | L     | moreoverlays                      | 1.15.1               | moreoverlays-1.15.1-mc1.12.2.jar                   | None      |
       | L     | mousetweaks                       | 2.10.1               | MouseTweaks-2.10.1-mc1.12.2.jar                    | None      |
       | L     | nae2                              | 1.6.1-GTLite         | nae2-1.6.1-GTLite.jar                              | None      |
       | L     | naturescompass                    | 1.8.5                | NaturesCompass-1.12.2-1.8.5.jar                    | None      |
       | L     | packagedauto                      | 1.12.2-1.0.10.38     | PackagedAuto-1.12.2-1.0.10.38.jar                  | None      |
       | L     | pickupnotifier                    | 1.1.5                | PickUpNotifier-v1.1.5-1.12.2.jar                   | None      |
       | L     | resourceloader                    | 1.5.3                | ResourceLoader-MC1.12.1-1.5.3.jar                  | None      |
       | L     | simplybackpacks                   | 1.4.9                | simplybackpacks-1.4.9.jar                          | None      |
       | L     | snad                              | 1.12.1-1.7.09.16a    | Snad-1.12.1-1.7.09.16a.jar                         | None      |
       | L     | supersoundmuffler                 | 1.0.2.10             | supersoundmuffler-revived_1.12.2_1.0.2.10.jar      | None      |
       | L     | tips                              | 1.0.9                | Tips-1.12.2-1.0.9.jar                              | None      |
       | L     | topaddons                         | 1.12.2-1.13.0        | topaddons-1.12.2-1.13.0.jar                        | None      |
       | L     | torchmaster                       | 1.8.5.0              | torchmaster_1.12.2-1.8.5.0.jar                     | None      |
       | L     | universaltweaks                   | 1.10.0               | UniversalTweaks-1.12.2-1.10.0.jar                  | None      |
       | L     | valkyrie                          | 0.2-Dev-10           | Valkyrie-0.2-Dev-10.jar                            | None      |
       | L     | vintagefix                        | 0.4.1                | vintagefix-0.4.1.jar                               | None      |
       | L     | worleycaves                       | 1.5.2                | worleycaves-1.12.2-1.5.2.jar                       | None      |
       | L     | xtones                            | 1.2.2                | Xtones-1.2.2.jar                                   | None      |
       | L     | recipehandler                     | 0.14                 | YARCF-0.14(1.12.2).jar                             | None      |

### MMC Instance Notes

This instance is built using Github Action.
Using installer artifact from commit: db3538e74c0d9ef3e458e091dd1364cba83c6bbf
Action URL: https://github.com/CleanroomMC/Cleanroom/actions/runs/8580871663

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fixed this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by Rongmario** [comment]
Install [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1)
