### ISSUE TITLE
java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by MrLuxALot** [CleanroomMC/Cleanroom#112]
### Your CleanroomMC Discord Username

mrluxalot

### Cleanroom Version

15.24.0.3036

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

[debug.log](https://github.com/CleanroomMC/Cleanroom/files/14949531/debug.log)
[latest.log](https://github.com/CleanroomMC/Cleanroom/files/14949532/latest.log)

### Mod List

The 1.12.2 Pack: Perfectly Complex

-Added mods: 
storage drawers
storage drawers extra
framed compact drawers
draconic evolution
brandon core
tinkers tool leveling
spice of life carrot
apple core
rftools
ftb utilites
ftb ultimine
nuclear craft
dank null
inventory scanning
fugue
scalar

-removed mods:
additional pipes
logistical pipes
buildcraft lib
iron tanks
mixin booter
renderlib
entity culling
hesperus

### MMC Instance Notes

This instance is built using Github Action.
Using installer artifact from commit: d6a43d3688bbe7f2e23d6a571193f43dd967c9a0
Action URL: https://github.com/CleanroomMC/Cleanroom/actions/runs/8617662837

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fixed this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by KorewaLidesu** [comment]
Update IC2Patcher

**Comment by MrLuxALot** [comment]
FYI you need to remove sledgehammer if you remove mixinbooter. Got stuck loading with sledgehammer searching for mixinbooter
![image](https://github.com/CleanroomMC/Cleanroom/assets/52431814/8abcfec5-2484-4e54-9bc5-5dfb5ada7d38)
now i get this
[crash-2024-04-11_23.36.46-client.txt](https://github.com/CleanroomMC/Cleanroom/files/14951530/crash-2024-04-11_23.36.46-client.txt)

**Comment by erialsan** [comment]
It worked when I turned off Gravisuit in a similar situation, suggesting that there may be an error in Gravisuit.

**Comment by MrLuxALot** [comment]
I need to have gravity suit tho bc i play on a server with friends

**Comment by erialsan** [comment]
I will create a log of the minimum environment using Gravisuit on my end and send it as a separate issue.

**Comment by MrLuxALot** [comment]
I submitted an issue to the gravitation suit patcher github bc the ic2 forum register is outrageosly stupid
