### ISSUE TITLE
Unable to launch on Nomifactory CEU 1.7-alpha-4

### ISSUE THREAD

**Issue by lynxx131** [CleanroomMC/Cleanroom#113]
### Your CleanroomMC Discord Username

lynxx131

### Cleanroom Version

15.24.0.3036 commit d6a43d3 on the experimental/foundation branch

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

Unable to launch Nomifactory CEU 1.7-alpha4 due to the following error:

```
java.lang.NoClassDefFoundError: scala/collection/Seq
```

To reproduce just use Prism launcher to download Nomifactory CEU 1.7-alpha4 from Curseforge and then copy the config, mods, groovy, resources and scripts folders into the Cleanroom instance.

Crash report is here: https://mclo.gs/Dn9tAVM

### Mod List

	| State | ID                                | Version                             | Source                                                      | Signature |
	|:----- |:--------------------------------- |:----------------------------------- |:----------------------------------------------------------- |:--------- |
	| LC    | minecraft                         | 1.12.2                              | minecraft.jar                                               | None      |
	| LC    | mcp                               | 9.42                                | minecraft.jar                                               | None      |
	| LC    | configanytime                     | 3.0                                 | minecraft.jar                                               | None      |
	| LC    | FML                               | 8.0.99.99                           | cleanroom-15.24.0.3036-universal.jar                        | None      |
	| LC    | forge                             | 14.23.5.2860                        | cleanroom-15.24.0.3036-universal.jar                        | None      |
	| LC    | advancedrocketrycore              | 1                                   | minecraft.jar                                               | None      |
	| LC    | creativecoredummy                 | 1.0.0                               | minecraft.jar                                               | None      |
	| LC    | nomiceu                           | 1.0.0                               | groovyscript-0.8.0.jar                                      | None      |
	| LC    | littletilescore                   | 1.0.0                               | minecraft.jar                                               | None      |
	| LC    | mixinbooter                       | 10.0                                | minecraft.jar                                               | None      |
	| LC    | moresoundconfigcore               | 1.0.0                               | minecraft.jar                                               | None      |
	| LC    | randompatches                     | 1.12.2-1.22.1.10                    | randompatches-1.12.2-1.22.1.10.jar                          | None      |
	| LC    | redcore                           | 0.5.1                               | !Red-Core-MC-1.7-1.12-0.5.1.jar                             | None      |
	| LC    | fugue                             | 1.12.2-0.14.0-beta                  | +Fugue-1.12.2-0.14.0-beta.jar                               | None      |
	| LC    | actuallyadditions                 | 1.12.2-r152                         | ActuallyAdditions-1.12.2-r152.jar                           | None      |
	| LC    | baubles                           | 1.5.2                               | Baubles-1.12-1.5.2.jar                                      | None      |
	| LC    | actuallybaubles                   | 1.1                                 | ActuallyBaubles-1.12-1.1.jar                                | None      |
	| LC    | redstoneflux                      | 2.1.1                               | RedstoneFlux-1.12-2.1.1.1-universal.jar                     | None      |
	| LC    | cofhcore                          | 4.6.6                               | CoFHCore-1.12.2-4.6.6.1-universal.jar                       | None      |
	| LC    | libvulpes                         | 0.4.2.-75                           | LibVulpes-1.12.2-0.4.2-75-universal.jar                     | None      |
	| LC    | advancedrocketry                  | 1.7.0.-232                          | AdvancedRocketry-1.12.2-1.7.0-232-universal.jar             | None      |
	| LC    | advsolars                         | 1.0                                 | advsolars-1.0.jar                                           | None      |
	| LC    | ctm                               | MC1.12.2-1.0.2.31                   | CTM-MC1.12.2-1.0.2.31.jar                                   | None      |
	| LC    | appliedenergistics2               | rv6-stable-7-extended_life-v0.55.27 | appliedenergistics2-rv6-stable-7-extended_life-v0.55.27.jar | None      |
	| L     | bdlib                             | 1.14.4.1                            | bdlib-1.14.4.1-mc1.12.2.jar                                 | None      |
	| L     | ae2stuff                          | 0.7.0.4                             | ae2stuff-0.7.0.4-mc1.12.2.jar                               | None      |
	| L     | endercore                         | 1.12.2-0.5.78                       | EnderCore-1.12.2-0.5.78.jar                                 | None      |
	| L     | crafttweaker                      | 4.1.20                              | CraftTweaker2-1.12-4.1.20.692.jar                           | None      |
	| L     | mtlib                             | 3.0.7                               | MTLib-3.0.7.jar                                             | None      |
	| L     | modtweaker                        | 4.0.19                              | modtweaker-4.0.20.5.jar                                     | None      |
	| L     | jei                               | 4.25.0                              | HadEnoughItems_1.12.2-4.25.0.jar                            | None      |
	| L     | codechickenlib                    | 3.2.3.358                           | CodeChickenLib-1.12.2-3.2.3.358-universal.jar               | None      |
	| L     | brandonscore                      | 2.4.20                              | BrandonsCore-1.12.2-2.4.20.162-universal.jar                | None      |
	| L     | cofhworld                         | 1.4.0                               | CoFHWorld-1.12.2-1.4.0.1-universal.jar                      | None      |
	| L     | thermalfoundation                 | 2.6.7                               | ThermalFoundation-1.12.2-2.6.7.1-universal.jar              | None      |
	| L     | draconicevolution                 | 2.3.28                              | Draconic-Evolution-1.12.2-2.3.28.354-universal.jar          | None      |
	| L     | thermalexpansion                  | 5.5.7                               | ThermalExpansion-1.12.2-5.5.7.1-universal.jar               | None      |
	| L     | enderio                           | 5.3.72                              | EnderIO-1.12.2-5.3.72.jar                                   | None      |
	| L     | p455w0rdslib                      | 2.3.161                             | p455w0rdslib-1.12.2-2.3.161.jar                             | None      |
	| L     | ae2wtlib                          | 1.0.34                              | AE2WTLib-1.12.2-1.0.34.jar                                  | None      |
	| L     | alfheim                           | 1.1.1                               | Alfheim-1.1.1.jar                                           | None      |
	| L     | appleskin                         | 1.0.14                              | AppleSkin-mc1.12-1.0.14.jar                                 | None      |
	| L     | architecturecraft                 | @VERSION@                           | architecturecraft-1.12-3.98.jar                             | None      |
	| L     | thedragonlib                      | 1.12.2-5.3.0                        | thedragonlib-1.12.2-5.3.0.jar                               | None      |
	| L     | armorplus                         | 1.12.2-11.25.1.62                   | armorplus-1.12.2-11.25.1.62.jar                             | None      |
	| L     | autoreglib                        | 1.3-32                              | AutoRegLib-1.3-32.jar                                       | None      |
	| L     | avaritia                          | 3.3.0                               | Avaritia-1.12.2-3.3.0.37-universal.jar                      | None      |
	| L     | base                              | 3.14.0                              | base-1.12.2-3.14.0.jar                                      | None      |
	| L     | forgelin                          | 1.8.4                               | Forgelin-1.8.4.jar                                          | None      |
	| L     | betterp2p                         | 1.12.2-1.2.3-extended_life          | betterp2p-1.12.2-1.2.3-extended_life.jar                    | None      |
	| L     | betterquesting                    | 4.2.1                               | BetterQuestingUnofficial-4.2.1.jar                          | None      |
	| L     | modularui                         | 2.4.2                               | modularui-2.4.2.jar                                         | None      |
	| L     | bogosorter                        | 1.4.6                               | bogosorter-1.4.6.jar                                        | None      |
	| L     | bookshelf                         | 2.3.590                             | Bookshelf-1.12.2-2.3.590.jar                                | None      |
	| L     | bountiful                         | 2.2.2                               | Bountiful-2.2.2.jar                                         | None      |
	| L     | buildinggadgets                   | 2.8.4                               | BuildingGadgets-2.8.4.jar                                   | None      |
	| L     | chameleon                         | 1.12-4.1.3                          | Chameleon-1.12-4.1.3.jar                                    | None      |
	| L     | chesttransporter                  | 2.8.8                               | ChestTransporter-1.12.2-2.8.8.jar                           | None      |
	| L     | chisel                            | MC1.12.2-1.0.2.45                   | Chisel-MC1.12.2-1.0.2.45.jar                                | None      |
	| L     | clienttweaks                      | 3.1.11                              | ClientTweaks_1.12.2-3.1.11.jar                              | None      |
	| L     | clumps                            | 3.1.2                               | Clumps-3.1.2.jar                                            | None      |
	| L     | collective                        | 3.0                                 | collective-1.12.2-3.0.jar                                   | None      |
	| L     | controlling                       | 3.0.10                              | Controlling-3.0.12.2.jar                                    | None      |
	| L     | craftelytra                       | 1.2                                 | CraftableElytra-1.1.jar                                     | None      |
	| L     | cns                               | 1.0                                 | CraftingNetherStar 1.12.1 -1.1.jar                          | None      |
	| L     | craftingtweaks                    | 9.0.1                               | CraftingTweaks_1.12.2-9.0.1.jar                             | None      |
	| L     | craftpresence                     | 2.3.5                               | CraftPresence-2.3.5+1.12.2.jar                              | None      |
	| L     | ctgui                             | 1.0.0                               | CraftTweaker2-1.12-4.1.20.692.jar                           | None      |
	| L     | crafttweakerjei                   | 2.0.3                               | CraftTweaker2-1.12-4.1.20.692.jar                           | None      |
	| L     | creativecore                      | 1.10.0                              | CreativeCore_v1.10.71_mc1.12.2.jar                          | None      |
	| L     | cucumber                          | 1.1.3                               | Cucumber-1.12.2-1.1.3.jar                                   | None      |
	| L     | custommainmenu                    | 2.0.9.1                             | CustomMainMenu-MC1.12.2-2.0.9.1.jar                         | None      |
	| L     | darkutils                         | 1.8.230                             | DarkUtils-1.12.2-1.8.230.jar                                | None      |
	| L     | patchouli                         | 1.0-23.6                            | Patchouli-1.0-23.6.jar                                      | None      |
	| L     | deepmoblearning                   | 1.2.1                               | DeepMobEvolution-1.12.2-1.2.1.jar                           | None      |
	| L     | defaultworldgenerator-port        | 1.12-2.3.1                          | DefaultWorldGenerator-port-1.12-2.3.1.jar                   | None      |
	| L     | difficultylock                    | 1.2                                 | difficultylock_1.12.2-1.2.jar                               | None      |
	| L     | theoneprobe                       | 1.4.28                              | theoneprobe-1.12-1.4.28.jar                                 | None      |
	| L     | dimensionaledibles                | 1.12.2-1.6.4                        | DimensionalEdibles-1.12.2-1.6.4.jar                         | None      |
	| L     | dynamistics                       | 1.0.2                               | dynamistics-1.0.2.jar                                       | None      |
	| L     | effortlessbuilding                | 1.12.2-2.16                         | effortlessbuilding-1.12.2-2.16.jar                          | None      |
	| L     | elevatorid                        | 1.3.14                              | ElevatorMod-1.12.2-1.3.14.jar                               | None      |
	| L     | enchdesc                          | 1.1.15                              | EnchantmentDescriptions-1.12.2-1.1.15.jar                   | None      |
	| L     | enderiointegrationtic             | 5.3.72                              | EnderIO-1.12.2-5.3.72.jar                                   | None      |
	| L     | enderiobase                       | 5.3.72                              | EnderIO-1.12.2-5.3.72.jar                                   | None      |
	| L     | enderioconduits                   | 5.3.72                              | EnderIO-1.12.2-5.3.72.jar                                   | None      |
	| L     | enderioconduitsappliedenergistics | 5.3.72                              | EnderIO-1.12.2-5.3.72.jar                                   | None      |
	| L     | enderioconduitsopencomputers      | 5.3.72                              | EnderIO-1.12.2-5.3.72.jar                                   | None      |
	| L     | enderioconduitsrefinedstorage     | 5.3.72                              | EnderIO-1.12.2-5.3.72.jar                                   | None      |
	| L     | enderiointegrationforestry        | 5.3.72                              | EnderIO-1.12.2-5.3.72.jar                                   | None      |
	| L     | enderiointegrationticlate         | 5.3.72                              | EnderIO-1.12.2-5.3.72.jar                                   | None      |
	| L     | enderioinvpanel                   | 5.3.72                              | EnderIO-1.12.2-5.3.72.jar                                   | None      |
	| L     | ftblib                            | 5.4.7.2                             | FTBLib-5.4.7.2.jar                                          | None      |
	| L     | enderiomachines                   | 5.3.72                              | EnderIO-1.12.2-5.3.72.jar                                   | None      |
	| L     | enderiopowertools                 | 5.3.72                              | EnderIO-1.12.2-5.3.72.jar                                   | None      |
	| L     | enderioendergy                    | 5.3.72                              | EnderIO-endergy-1.12.2-5.3.72.jar                           | None      |
	| L     | enderstorage                      | 2.4.6.137                           | EnderStorage-1.12.2-2.4.6.137-universal.jar                 | None      |
	| L     | extendedcrafting                  | 1.7.0.6                             | extendedcrafting-nomifactory-edition-1.7.0.6.jar            | None      |
	| L     | extrautils2                       | 1.0                                 | extrautils2-1.12-1.9.9.jar                                  | None      |
	| L     | fasterladderclimbing              | 0.1-146                             | FasterLadderClimbing-1.12-0.1-146.jar                       | None      |
	| L     | forgemultipartcbe                 | 2.6.2.83                            | ForgeMultipart-1.12.2-2.6.2.83-universal.jar                | None      |
	| L     | microblockcbe                     | 2.6.2.83                            | ForgeMultipart-1.12.2-2.6.2.83-universal.jar                | None      |
	| L     | minecraftmultipartcbe             | 2.6.2.83                            | ForgeMultipart-1.12.2-2.6.2.83-universal.jar                | None      |
	| L     | forgivingvoid                     | 1.1.0                               | ForgivingVoid_1.12.2-1.1.0.jar                              | None      |
	| L     | storagedrawers                    | 5.5.0                               | StorageDrawers-1.12.2-5.5.0.jar                             | None      |
	| L     | framedcompactdrawers              | 1.2.7                               | framedcompactdrawers-1.2.7.jar                              | None      |
	| L     | ftbbackups                        | 1.1.0.1                             | FTBBackups-1.1.0.1.jar                                      | None      |
	| L     | ftbutilities                      | 5.4.1.131                           | FTBUtilities-5.4.1.131.jar                                  | None      |
	| L     | groovyscript                      | 0.8.0                               | groovyscript-0.8.0.jar                                      | None      |
	| L     | gregtech                          | 2.8.7-beta                          | gregtech-1.12.2-2.8.7-beta.jar                              | None      |
	| L     | gcym                              | 1.2.8                               | GregicalityMultiblocks-1.2.8.jar                            | None      |
	| L     | gregtechdrawers                   | 1.0.7                               | gregtech-drawers-1.12.2-1.0.7.jar                           | None      |
	| L     | librarianlib                      | 4.22                                | librarianlib-1.12.2-4.22.jar                                | None      |
	| L     | hooked                            | %VERSION%                           | hooked-1.0.3.jar                                            | None      |
	| L     | jeiutilities                      | 0.2.12                              | JEI-Utilities-1.12.2-0.2.12.jar                             | None      |
	| L     | journeymap                        | 1.12.2-5.7.1                        | journeymap-1.12.2-5.7.1.jar                                 | None      |
	| L     | jecalculation                     | 1.12.2-3.2.7                        | JustEnoughCalculation-1.12.2-3.2.7.jar                      | None      |
	| L     | justenoughdimensions              | 1.6.0-dev.20200416.184714           | justenoughdimensions-1.12.2-1.6.0-dev.20200416.184714.jar   | None      |
	| L     | jeresources                       | 0.9.2.60                            | JustEnoughResources-1.12.2-0.9.2.60.jar                     | None      |
	| L     | littletiles                       | 1.5.0                               | LittleTiles_v1.5.81_mc1.12.2.jar                            | None      |
	| L     | lostcities                        | 2.0.22                              | lostcities-1.12-2.0.22.jar                                  | None      |
	| L     | modnametooltip                    | 1.10.1                              | modnametooltip_1.12.2-1.10.1.jar                            | None      |
	| L     | morefurnaces                      | 1.11.0                              | MoreFurnaces-Nomifactory-Edition-1.12.2-1.11.0.jar          | None      |
	| L     | morelibs                          | 1.2.2                               | morelibs-1.12.2-1.2.2.jar                                   | None      |
	| L     | moreoverlays                      | 1.15.1                              | moreoverlays-1.15.1-mc1.12.2.jar                            | None      |
	| L     | mrtjpcore                         | 2.1.4.43                            | MrTJPCore-1.12.2-2.1.4.43-universal.jar                     | None      |
	| L     | projectred-core                   | 4.9.4.120                           | ProjectRed-1.12.2-4.9.4.120-Base.jar                        | None      |
	| L     | moreplates                        | 5.5.2                               | moreplates-1.12.2-5.5.2.jar                                 | None      |
	| L     | morpheus                          | 1.12.2-3.5.106                      | Morpheus-1.12.2-3.5.106.jar                                 | None      |
	| L     | mousetweaks                       | 3.1.4                               | mousetweaks-1.12.2-3.1.4.jar                                | None      |
	| L     | nae2                              | 1.3.1                               | nae2-1.3.1.jar                                              | None      |
	| L     | naturescompass                    | 1.8.5                               | NaturesCompass-1.12.2-1.8.5.jar                             | None      |
	| L     | packmode                          | 1.2.0                               | packmode-1.12.2-1.2.0.jar                                   | None      |
	| L     | nomilabs                          | 0.6.28                              | NomiLabs-0.6.28.jar                                         | None      |
	| L     | nonetherportals                   | 1.1.0                               | nonetherportals-1.1.0.jar                                   | None      |
	| L     | nuclearcraft                      | 2.18y                               | NuclearCraft-2.18y-1.12.2.jar                               | None      |
	| L     | oauth                             | 1.06.4                              | oauth-1.06.4.jar                                            | None      |
	| L     | openglider                        | @VERSION@                           | OpenGlider-1.12.1-1.1.0.jar                                 | None      |
	| L     | packagedauto                      | 1.12.2-1.0.11.40                    | PackagedAuto-1.12.2-1.0.11.40.jar                           | None      |
	| L     | packagedexcrafting                | 1.12.2-1.0.2.10                     | PackagedExCrafting-1.12.2-1.0.2.10.jar                      | None      |
	| L     | placebo                           | 1.6.0                               | Placebo-1.12.2-1.6.0.jar                                    | None      |
	| L     | projectintelligence               | 1.0.9                               | ProjectIntelligence-1.12.2-1.0.9.28-universal.jar           | None      |
	| L     | projectred-integration            | 4.9.4.120                           | ProjectRed-1.12.2-4.9.4.120-integration.jar                 | None      |
	| L     | projectred-transmission           | 4.9.4.120                           | ProjectRed-1.12.2-4.9.4.120-integration.jar                 | None      |
	| L     | realbench                         | 1.0.4                               | RealBench-Nomi-CEu-1.0.4.jar                                | None      |
	| L     | redstonearsenal                   | 2.6.6                               | RedstoneArsenal-1.12.2-2.6.6.1-universal.jar                | None      |
	| L     | resourceloader                    | 1.5.3                               | ResourceLoader-MC1.12.1-1.5.3.jar                           | None      |
	| L     | simplyjetpacks                    | 2.2.15.69                           | SimplyJetpacks2-1.12.2-2.2.15.69.jar                        | None      |
	| L     | snad                              | 1.12.1-1.7.09.16a                   | Snad-1.12.1-1.7.09.16a.jar                                  | None      |
	| L     | solarflux                         | 12.4.11                             | SolarFluxReborn-1.12.2-12.4.11.jar                          | None      |
	| L     | spark                             | 1.5.2                               | spark-forge1122.jar                                         | None      |
	| L     | supersoundmuffler                 | 1.0.2.10                            | supersoundmuffler-revived_1.12.2_1.0.2.10.jar               | None      |
	| L     | thermalcultivation                | 0.3.6                               | ThermalCultivation-1.12.2-0.3.6.1-universal.jar             | None      |
	| L     | thermalinnovation                 | 0.3.6                               | ThermalInnovation-1.12.2-0.3.6.1-universal.jar              | None      |
	| L     | tipthescales                      | 1.0.4                               | TipTheScales-1.12.2-1.0.4.jar                               | None      |
	| L     | tombmanygraves                    | 1.12-4.2.0                          | TombManyGraves-1.12-4.2.0.jar                               | None      |
	| L     | toolbelt                          | 1.9.14                              | ToolBelt-1.12.2-1.9.14.jar                                  | None      |
	| L     | topaddons                         | 1.12.2-1.13.0                       | topaddons-1.12.2-1.13.0.jar                                 | None      |
	| L     | torchmaster                       | 1.8.5.0                             | torchmaster_1.12.2-1.8.5.0.jar                              | None      |
	| L     | trashslot                         | 8.4.10                              | TrashSlot_1.12.2-8.4.10.jar                                 | None      |
	| L     | ulv_covers                        | 0.2.2                               | ULVCovers-1.12.2-2.8.0.jar                                  | None      |
	| L     | universaltweaks                   | 1.9.0                               | UniversalTweaks-1.12.2-1.9.0.jar                            | None      |
	| L     | vintagefix                        | 0.3.3                               | vintagefix-0.3.3.jar                                        | None      |
	| L     | visualores                        | 0.2.4                               | visualores-0.2.4.jar                                        | None      |
	| L     | wct                               | 3.12.97                             | WirelessCraftingTerminal-1.12.2-3.12.97.jar                 | None      |
	| L     | worleycaves                       | 1.5.2                               | worleycaves-1.12.2-1.5.2.jar                                | None      |
	| L     | xtones                            | 1.2.2                               | Xtones-1.2.2.jar                                            | None      |
	| L     | densemetals                       | 2.0.0                               | DenseMetals-1.12.2-2.0.0.30.jar                             | None      |
	| L     | moresoundconfig                   | 1.0.4                               | moresoundconfig-1.0.4.jar                                   | None      |
	| L     | librarianliblate                  | 4.22                                | librarianlib-1.12.2-4.22.jar                                | None      |

### MMC Instance Notes

This instance is built using Github Action.
Using installer artifact from commit: 2b470f47112f1e6b9cad920b989e2a5b4408dd8e
Action URL: https://github.com/CleanroomMC/Cleanroom/actions/runs/8502574841

But manually updated to 15.24.0.3036 to see if it fixed the issue which it didn't.

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fixed this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Install Scalar
https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1
That's a new change in recent exp branch
