### ISSUE TITLE
Crash with Open Computer

### ISSUE THREAD

**Issue by ChenHaoYan1234** [CleanroomMC/Cleanroom#115]
### Cleanroom Version

15.24.0.3036

### Java Version

Java 21

### Graphics Card Vendor

Intel iGPU

### Bug Report

[latest.log](https://github.com/CleanroomMC/Cleanroom/files/14960715/latest.log)
[crash-2024-04-12_23.27.35-client.txt](https://github.com/CleanroomMC/Cleanroom/files/14960723/crash-2024-04-12_23.27.35-client.txt)

### Mod List

Open Computer 1.8.3
Fugue 0.14.0-beta

### MMC Instance Notes

none

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fixed this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Install Scalar
Please read readme before opening issue

**Comment by MicroNeutron** [comment]
Hello kappa-maintainer, 
The problem didn't solve with Scalar. It still conflicted and failed to load in.

**Comment by kappa-maintainer** [comment]
Scalar Legacy
