### ISSUE TITLE
Mixin issue with Realistic Terrain Generation Plus

### ISSUE THREAD

**Issue by ChromaPIE** [CleanroomMC/Cleanroom#117]
### Cleanroom Version

https://github.com/CleanroomMC/CleanroomMMC/actions/runs/8670014434

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

https://mclo.gs/1aCer49

### Mod List

In the report

### MMC Instance Notes

```
This instance is built using Github Action.
Using installer artifact from commit: 7685ce9679aa2b8b327ceb27dd1e451ff90a81a6
Action URL: https://github.com/CleanroomMC/Cleanroom/actions/runs/8669970544
```

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Same crash on Forge, so not a Cleanroom bug
Reporting to REID author
