### ISSUE TITLE
Scalar not providing Scala lang

### ISSUE THREAD

**Issue by ZZZank** [CleanroomMC/Cleanroom#122]
### Cleanroom Version

15.24.0.3027(https://github.com/CleanroomMC/Cleanroom/actions/runs/8766115232)

### Java Version

Java 21

### Graphics Card Vendor

AMD iGPU

### Bug Report

crash reports on two different launchers, but crash reasons are the same:
[crash-2024-04-21_00.29.02-client.txt](https://github.com/CleanroomMC/Cleanroom/files/15050558/crash-2024-04-21_00.29.02-client.txt)
[crash-2024-04-21_11.50.24-client.txt](https://github.com/CleanroomMC/Cleanroom/files/15050559/crash-2024-04-21_11.50.24-client.txt)

latest.log:
[latest.log](https://github.com/CleanroomMC/Cleanroom/files/15050561/latest.log)

### Mod List

In the crash report. 
Modlist is basically the same as a fresh installed Multiblock Madness, with Fugue and Scalar added. 

There's no "additional info" section for me to fill in, so I might just say here:
- I notice that when the crash happens, the game is trying to load BDLib, according to startup screen and status marker in the modlist included in crash report. And BDLib, happens to be a mod written in Scala. 
- But when I test this on a fresh instance with only Scalar and BDLib installed, it does not crash, and behaves perfectly normal in-game.

### MMC Instance Notes

Not MMC instance

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Is bdlib a corebmod? Try rename it to !Scalar or smth

**Comment by ZZZank** [comment]
nope, BDLib is just a regular library mod as far as I know, and renaming Scalar jar file does not help. 
I also tried renaming jars exported in "1.12.2" folder, not helping too.

**Comment by kappa-maintainer** [comment]
Please check if Scalar's manifest contains "NonModDeps", if no, re-download Scalar 2.11.1

**Comment by ZZZank** [comment]
Using the newest Scalar 2.11.1 does fixes this, and the one I was using before is just missing one line in `MANIFEST.MF` :
```
NonModDeps: true
```
Is Scalar published twice using same version code?
