### ISSUE TITLE
Incompatibility with Modular Machinery: Community Edition

### ISSUE THREAD

**Issue by valiray** [CleanroomMC/Cleanroom#124]
### Your CleanroomMC Discord Username

valiray

### Cleanroom Version

15.24.0.3038

### Java Version

Java 21

### Graphics Card Vendor

Intel iGPU

### Bug Report

on a fresh install of clean room with just Fugue, scalar, CraftTweaker and mmce i am getting this crash

https://mclo.gs/c3wBUG6

### Mod List

Fugue, scalar, CraftTweaker and Modular Machinery

### MMC Instance Notes

This instance is built using Github Action.
Using installer artifact from commit: 23e2f7225e1be750f6473b5f83aa185ba80da8d0
Action URL: https://github.com/CleanroomMC/Cleanroom/actions/runs/8785198791

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by LonelyxiyaOVO** [comment]
Using this version should solve your problem
ModularMachinery-CE-2.0.0-pre4

**Comment by valiray** [comment]
> Using this version should solve your problem ModularMachinery-CE-2.0.0-pre4

trying the latest [dev build](https://github.com/NovaEngineering-Source/ModularMachinery-Community-Edition/actions/runs/8771434199) on the github and i still get the same crash

**Comment by LonelyxiyaOVO** [comment]
cleanroom loader 对于RenderLib mod 不受支持

**Comment by valiray** [comment]
sorry, that crash report was for something else i am working on, here is the clean crash report https://mclo.gs/tXfkVJV without RenderLib

**Comment by kappa-maintainer** [comment]
1. Latest exp does support renderlib + nothirium
2. The author of Modular Machinery CE is working on this crash

**Comment by KasumiNova** [comment]
Fixed in 2.0.0-pre4, just update it.
