### ISSUE TITLE
Minecraft won't start with CB Multipart(ForgeMultipart)

### ISSUE THREAD

**Issue by Arnold1338** [CleanroomMC/Cleanroom#127]
### Your CleanroomMC Discord Username

godofhonor (user) / МелкаяЧувырла (displayed)

### Cleanroom Version

Latest exp branch([Experimental#510])

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

https://mclo.gs/AxMdzsF

### Mod List

Fugue, Scalar 2, CodeChickenLib, Forge Multipart CBE

### MMC Instance Notes

This instance is built using Github Action.
Using installer artifact from commit: c1af5dc2acb06aacc3c9712ddbbdd19e9013ae5f
Action URL: https://github.com/CleanroomMC/Cleanroom/actions/runs/8868400314

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by Arnold1338** [comment]
Crash happens with CCLib even without FMCBE

**Comment by kappa-maintainer** [comment]
Should have fixed in latest exp commit
It was a dumb bug introduced when I tried to implement Mixin class transformer
