### ISSUE TITLE
Storage Drawers crash

### ISSUE THREAD

**Issue by ExeDaRespond** [CleanroomMC/Cleanroom#134]
### Cleanroom Version

 0.2.0-alpha

### Java Version

Java 21

### Graphics Card Vendor

Intel iGPU

### Bug Report

https://mclo.gs/xgdKk7w

### Mod List

[✔] Chameleon-1.12.2-4.1.3
[✔] scalar-1.12.2-2.11.1
[✔] StorageDrawers-1.12.2-5.5.0
[✔] +Fugue-1.12.2-0.14.5-beta

### MMC Instance Notes

This instance is built using Github Action.
Using installer artifact from commit: 47cf52efe43bc08929ba1299aea14b58a0eb60fb
Action URL: https://github.com/CleanroomMC/Cleanroom/actions/runs/8963295610

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Can't reproduce, try re-download the instance?

**Comment by ExeDaRespond** [comment]
It doesn't fix the problem

**Comment by ExeDaRespond** [comment]
i realized that chameleon lib from modrinth was causing the problem as is
