### ISSUE TITLE
Replaymod cannot load properly

### ISSUE THREAD

**Issue by VillagerGold** [CleanroomMC/Cleanroom#135]
### Cleanroom Version

0.2.0-alpha+build.10.run.553

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

When I tried to load replaymod in cleanroom, I found that the buttons of the mod were not displaying properly and were not compatible with the button addition function of replaymod in CustomimMainMenu. I hope it can be fixed

### Mod List

CustomMainMenu-2.0.9.1
Fugue-0.14.6
replaymod-2.6.14

### MMC Instance Notes

nothing

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by VillagerGold** [comment]
![forge界面](https://github.com/CleanroomMC/Cleanroom/assets/70471621/e53f9cbf-5687-44d4-96cd-0e955ba3b8c1)
This is the original Forge single player game interface
![cleanroom界面](https://github.com/CleanroomMC/Cleanroom/assets/70471621/dda32d19-e443-4351-a834-86e9fd818e17)
This is the single player game interface of cleanroom
You can see that there is no record button, and similarly, CustomimMainMenu cannot load the record button for replaymod. I hope the next version can support loading replaymod

**Comment by kappa-maintainer** [comment]
Try fugue 0.14.6

**Comment by VillagerGold** [comment]
I tried the latest beta version of fugue, but still couldn't solve the problem of replaymod not loading properly

**Comment by kappa-maintainer** [comment]
Make sure it's 0.14.6 + release version of Cleanroom
If it didn't work, redownload all and re-try
If it still didn't work, use Prism to launch the game or provide logs

**Comment by VillagerGold** [comment]
You can download replaymod yourself to verify if Cleanroom can load replaymod,

**Comment by kappa-maintainer** [comment]
I told you to test because it fxxking works on my side

**Comment by VillagerGold** [comment]
Problem client link：https://pan.baidu.com/s/1N07Lwj-laOxlL7aL_TISkA 
Extract code：Gold

**Comment by kappa-maintainer** [comment]
You should just post mod list and log, I wouldn't download the client
Just tested, fresh installed 0.2.1-alpha release and replaymod:
![图片](https://github.com/CleanroomMC/Cleanroom/assets/11038263/6ce2a45d-8748-4035-8465-677328233850)

If you mean CustomMainMenu hiding the view replay button in main menu, that's a mod conflict and not our business

**Comment by VillagerGold** [comment]
![image](https://github.com/CleanroomMC/Cleanroom/assets/70471621/e60057c6-8ef7-4a50-951a-c05a5ec75cd7)
**
![image](https://github.com/CleanroomMC/Cleanroom/assets/70471621/ddf89310-78af-4954-a9a2-0f232a376870)
**
![image](https://github.com/CleanroomMC/Cleanroom/assets/70471621/ab5ae8cd-c760-4764-8348-7cab27880dd8)

**Comment by kappa-maintainer** [comment]
Please don't remove that `+` in fugue file name, no guarantee it will still work after removal

**Comment by VillagerGold** [comment]
May I ask what version of Cleanroom is being used

**Comment by kappa-maintainer** [comment]
0.2.1-alpha from release, not action

**Comment by VillagerGold** [comment]
![image](https://github.com/CleanroomMC/Cleanroom/assets/70471621/4878c090-788e-40f3-b85d-61e1a3967702)
![image](https://github.com/CleanroomMC/Cleanroom/assets/70471621/db4e752c-da9e-44b6-8c2d-5e7170d09a04)

**Comment by kappa-maintainer** [comment]
Further test shows Fugue works in this case even with name changed
Then my only suggestion is to use Prism, since other launchers have never been officially supported.
If you can't use Prism, that's your problem.

**Comment by VillagerGold** [comment]
Can HMCL receive official support

**Comment by kappa-maintainer** [comment]
It's impossible since we can't customize libraries in HMCL like in MMC-based launcher
Btw you should really ask in QQ or Discord, every comment here will be sent to everyone watching this repository, which may cause spam in some case

**Comment by VillagerGold** [comment]
May I know your QQ number

**Comment by kappa-maintainer** [comment]
664266845
Please don't reply again
