### ISSUE TITLE
OptiFine is not supported again

### ISSUE THREAD

**Issue by VillagerGold** [CleanroomMC/Cleanroom#137]
### Cleanroom Version

0.2.0-alpha+build.10.run.553

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

As the question suggests, I hope the new version of Cleanroom supports OptiFine (including when Fugue is installed)

### Mod List

nothing

### MMC Instance Notes

nothing

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Try roll back one commit

**Comment by VillagerGold** [comment]
I tried using 554 and 553, but they couldn't solve the problem of crashing when using OptiFine

**Comment by kappa-maintainer** [comment]
Can't reproduce, no log no fix
![Screenshot_20240508_171855](https://github.com/CleanroomMC/Cleanroom/assets/11038263/cb2be222-a7f4-49da-bfe0-b40ca9abc599)

**Comment by VillagerGold** [comment]
[minecraft-exported-crash-info-2024-05-08T17-27-05.zip](https://github.com/CleanroomMC/Cleanroom/files/15246821/minecraft-exported-crash-info-2024-05-08T17-27-05.zip)

**Comment by kappa-maintainer** [comment]
Launcher problem
HMCL somehow added another `-width`
Launch from script should work
