### ISSUE TITLE
A series of errors triggered by achievement rewards

### ISSUE THREAD

**Issue by VillagerGold** [CleanroomMC/Cleanroom#143]
### Your CleanroomMC Discord Username

村民黄金

### Cleanroom Version

0.2.1-alpha

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

[minecraft-exported-crash-info-2024-05-12T19-16-47.zip](https://github.com/CleanroomMC/Cleanroom/files/15304014/minecraft-exported-crash-info-2024-05-12T19-16-47.zip)
No need to provide a module. Under the same module, the Forge loader can enter the map and eat the Ender cake to enter the destination normally. However, the Cleanroom loader cannot enter the map and eat the Ender cake to enter the destination normally. The error message is an issue with achievement rewards. I guess it is because the Cleanroom loader is missing some functions of the Forge loader (I provide a mod open source, and merging this open source into the Cleanroom loader may solve the problem)
https://github.com/Technici4n/advancements-debug

### Mod List

nothing(I cannot determine the minimum reproduction combination)

### MMC Instance Notes

nothing

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by ZZZank** [comment]
please remove Lucky Block and try again

```
[19:16:40] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:651]: 	at mod.lucky.world.LuckyTickHandler.onClientTick(LuckyTickHandler.java:44)
[19:16:40] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:651]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2163_LuckyTickHandler_onClientTick_ClientTickEvent.invoke(.dynamic)
```

**Comment by kappa-maintainer** [comment]
We are forked from Forge and didn't touch this part of code, so the behavior of the two loaders is identical.

**Comment by VillagerGold** [comment]
Deleting Lucky Block is useless. I hope to check the code in Cleanroom because the Forge loader will not encounter this issue under the same mod (of course, Forge has Mixinboot, while Cleanroom has fugue, scalar, and stellarcore)

**Comment by kappa-maintainer** [comment]
We didn't touch anything about advancement, it's just not related

**Comment by ZZZank** [comment]
you seem to be using old Phosphor together with Optifine, both of which are not recommended, so please remove them amd try again. 
Also, there's nothing fatal about advancement, those errors are caused by modpack devs removing recipes, and are not likely to be the problem.

**Comment by VillagerGold** [comment]
those errors are caused by modpack devs removing recipes,how can we fix this issue

**Comment by ZZZank** [comment]
modpack devs should explicitly set recipe id to match the one requested by advancement. 

e.g. advancement `minecraft:recipes/decorations/torch` requested a recipe with id `minecraft:torch`, then there should be a recipe with its recipe id set to `minecraft:torch`. Assuming that they remove the original, then add a new recipe, then recipe id of the new one should be `minecraft:torch`

Again, advancement barely causes crash, and even less likely to be Cleanroom exclusive.

**Comment by VillagerGold** [comment]
But I won't experience this kind of crash under the Forge loader, I hope it can be fixed

**Comment by kappa-maintainer** [comment]
No bisect no fix
We won't waste time debugging in a pack like this

**Comment by Ecdcaeb** [comment]
Dont pack logs to zip!
