### ISSUE TITLE
Crash with CustomSkinLoader

### ISSUE THREAD

**Issue by ssakura49** [CleanroomMC/Cleanroom#144]
### Your CleanroomMC Discord Username

ssakura

### Cleanroom Version

15.24.0.3029

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

https://mclo.gs/BhIqMFn

### Mod List

CustomSkinLoader_ForgeLegacy-14.19.1.jar
Fugue-1.12.2-0.5.4.jar
scalar-1.12.2-2.11.1.jar

### MMC Instance Notes

I'm using HMCL

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Please use latest alpha from [release](https://github.com/CleanroomMC/Cleanroom/releases/tag/0.2.1-alpha) and Fugue 0.14.9
