### ISSUE TITLE
Incompatibility with MineFantasyReforged and other mods

### ISSUE THREAD

**Issue by MamekoCSc** [CleanroomMC/Cleanroom#146]
### Cleanroom Version

0.2.1-alpha

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

The game crashes when I use MineFantasyReforged and JEI at the same time.

[crash-2024-05-18_13.03.34-client.txt](https://github.com/CleanroomMC/Cleanroom/files/15360009/crash-2024-05-18_13.03.34-client.txt)
[debug.log](https://github.com/CleanroomMC/Cleanroom/files/15360011/debug.log)
[latest.log](https://github.com/CleanroomMC/Cleanroom/files/15360012/latest.log)

Textures of some blocks in BiblioCraft are wrong when I use MineFantasyReforged and BiblioCraft at the same time. 
This problem will not happen if MineFantasyReforged is not used.
[debug.log](https://github.com/CleanroomMC/Cleanroom/files/15360303/debug.log)
[latest.log](https://github.com/CleanroomMC/Cleanroom/files/15360306/latest.log)

![2024-05-18_14 31 48](https://github.com/CleanroomMC/Cleanroom/assets/169260925/dbb82130-911b-4234-826b-59159fef1648)

### Mod List

+Fugue-1.12.2-0.14.11
scalar-1.12.2-2.11.1
jei_1.12.2-4.16.1.1012
CodeChickenLib-1.12.2-3.2.3.358
MineFantasyReforged-1.12.2-0.2.9
OptiFine_1.12.2_HD_U_G5
BiblioCraft[v2.4.6][MC1.12.2]

### MMC Instance Notes

nothing

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)
[latest.log](https://github.com/CleanroomMC/Cleanroom/files/15360304/latest.log)

**Comment by kappa-maintainer** [comment]
Try switch to HEI
https://www.curseforge.com/minecraft/mc-mods/had-enough-items

**Comment by MamekoCSc** [comment]
I used HEI instead but it seems that the same problem happened again.
[debug.log](https://github.com/CleanroomMC/Cleanroom/files/15360136/debug.log)
[latest.log](https://github.com/CleanroomMC/Cleanroom/files/15360137/latest.log)
[crash-2024-05-18_13.48.06-client.txt](https://github.com/CleanroomMC/Cleanroom/files/15360138/crash-2024-05-18_13.48.06-client.txt)

**Comment by kappa-maintainer** [comment]
We will check what happened in MineFantasy

**Comment by MamekoCSc** [comment]
Thanks, and there's another trouble with MineFantasyReforged and BiblioCraft.
![2024-05-18_14 31 48](https://github.com/CleanroomMC/Cleanroom/assets/169260925/0f84ec6a-99b8-423b-a862-dd71aeb6eaf9)

**Comment by kappa-maintainer** [comment]
Try extracting the META-INF/MANIFEST.MF file from minefantasy, delete the line starts with MixinConfigs, and compress that file back to replace the original one

**Comment by kappa-maintainer** [comment]
MFR's Mixin is broken, I am reporting to the authors

**Comment by MamekoCSc** [comment]
Both problems are solved. Thanks!
