### ISSUE TITLE
Incompatibility List

### ISSUE THREAD

**Issue by Nrmot** [CleanroomMC/Cleanroom#15]
OS: Windows, Java is version 21.0.1, using 64 (amd64) architecture, from Azul Systems, Inc..

Incompatibility list of mods, with exception provided:

Literally Unlaunchable:
- GalaxySpace: `[23:04:33] [main/FATAL] [Bouncepad]: Unable to launch
java.lang.RuntimeException: java.lang.ClassNotFoundException: net.minecraftforge.fml.common.Loader
	at 
net.minecraftforge.fml.common.launcher.FMLDeobfTweaker.injectIntoClassLoader(FMLDeobfTweaker.java:67)`
Crashes on Cleanroom Loading:
- SplashAnimation: `java.lang.NoClassDefFoundError: net/minecraftforge/fml/client/SplashProgress$2`
- TFCMedicinal: `java.lang.IncompatibleClassChangeError: Method 'net.dries007.tfc.objects.inventory.ingredient.IIngredient net.dries007.tfc.objects.inventory.ingredient.IIngredient.of(net.minecraftforge.fluids.Fluid, int)' must be InterfaceMethodref constant`

Loading World Crashes:

Crash Logs for most of the exceptions (random order):
[crash-2023-11-24_22.22.03-client.txt](https://github.com/CleanroomMC/Cleanroom/files/13460245/crash-2023-11-24_22.22.03-client.txt)
[crash-2023-11-24_22.26.47-client.txt](https://github.com/CleanroomMC/Cleanroom/files/13460246/crash-2023-11-24_22.26.47-client.txt)
[crash-2023-11-24_22.31.41-client.txt](https://github.com/CleanroomMC/Cleanroom/files/13460247/crash-2023-11-24_22.31.41-client.txt)
[crash-2023-11-24_22.34.53-client.txt](https://github.com/CleanroomMC/Cleanroom/files/13460248/crash-2023-11-24_22.34.53-client.txt)
[crash-2023-11-24_22.38.16-client.txt](https://github.com/CleanroomMC/Cleanroom/files/13460249/crash-2023-11-24_22.38.16-client.txt)
[crash-2023-11-24_22.07.07-client.txt](https://github.com/CleanroomMC/Cleanroom/files/13460250/crash-2023-11-24_22.07.07-client.txt)
[crash-2023-11-24_22.11.03-client.txt](https://github.com/CleanroomMC/Cleanroom/files/13460251/crash-2023-11-24_22.11.03-client.txt)
[crash-2023-11-24_22.13.19-client.txt](https://github.com/CleanroomMC/Cleanroom/files/13460252/crash-2023-11-24_22.13.19-client.txt)
[crash-2023-11-24_22.15.22-client.txt](https://github.com/CleanroomMC/Cleanroom/files/13460253/crash-2023-11-24_22.15.22-client.txt)

Fixed:
- Nuclear Option: `java.lang.NoClassDefFoundError: scala/Product$class`
- OpenComputers: LOG SPAM `[22:11:00] [Client thread/WARN] [OpenComputers]: Something went wrong!
java.lang.NoSuchMethodError: 'scala.collection.mutable.ArrayOps scala.Predef$.refArrayOps(java.lang.Object[])'`
- Quark: `java.lang.InternalError: java.lang.IllegalAccessException: static final field has no write access: net.minecraft.init.Blocks.field_180399_cE/net.minecraft.block.Block/putStatic, from class java.lang.Object (module java.base)`
- Scaling Health: `java.lang.NoClassDefFoundError: javax/activation/UnsupportedDataTypeException`
- Silent Gear: `java.lang.NoClassDefFoundError: javax/activation/UnsupportedDataTypeException`
- Touhou Little Maid: `java.lang.NoClassDefFoundError: javax/script/ScriptEngineManager`
- WorldEdit `java.lang.NoClassDefFoundError: javax/script/ScriptException`
- Silent Gems `java.lang.NoClassDefFoundError: javax/activation/UnsupportedDataTypeException`

**Comment by Nrmot** [comment]
added WorldEdit `java.lang.NoClassDefFoundError: javax/script/ScriptException`

**Comment by Nrmot** [comment]
added SilentGems `java.lang.NoClassDefFoundError: javax/activation/UnsupportedDataTypeException`

**Comment by Rongmario** [comment]
`javax/script/...` issues have been solved

**Comment by kappa-maintainer** [comment]
All fixed except from SplashAnimation and TFCMedicinal

**Comment by kappa-maintainer** [comment]
All should be patched in Fugue 0.5.2
