### ISSUE TITLE
Various mods can crash with CME when using HashMap's computeIfAbsent()

### ISSUE THREAD

**Issue by jchung01** [CleanroomMC/Cleanroom#150]
### Your CleanroomMC Discord Username

chaosstrikez

### Cleanroom Version

15.24.0.3037

### Java Version

Java 22

### Graphics Card Vendor

Intel iGPU

### Bug Report

Using an old cleanroom from https://github.com/CleanroomMC/CleanroomMMC/actions/runs/8765858825 and Fugue 0.14.3, but I believe this issue would still exist on latest versions.
The following crashes were reported from a user in the Meatballcraft server, it looks like they are `ConcurrentModificationException`s when calling `HashMap#computeIfAbsent()`.
- [x] Astral Sorcery: https://mclo.gs/5hmtH6O
- [x] InControl: https://mclo.gs/0JqNEa2
Seemingly the same issue that AE2UEL had [here](https://github.com/AE2-UEL/Applied-Energistics-2/pull/362).

### Mod List

[Meatballcraft](https://www.curseforge.com/minecraft/modpacks/meatballcraft) pack, but relevant mods are:
- Fugue 0.14.3
- astralsorcery-1.12.2-1.10.27
- incontrol-1.12-3.9.18

### MMC Instance Notes

None

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by Rongmario** [comment]
For context's sake:

In [Java 8](https://github.com/adoptium/jdk8u/blob/216b8cbf51f8f5f020a57dabb763c27b36899c12/jdk/src/share/classes/java/util/Map.java#L892), there is no clear contract in the compute methods: `Map#compute`/`Map#computeIfAbsent`/`Map#computeIfPresent` on what would happen if the map was modified through external means during these methods for **non-concurrent maps** (e.g `HashMap`).

However, in [Java 9+](https://github.com/openjdk/jdk/blob/c9a7b9772d96d9a4825d9da2aacc277534282860/src/java.base/share/classes/java/util/Map.java#L1025) this was enforced.

**Comment by kappa-maintainer** [comment]
All patched in 0.15.x
