### ISSUE TITLE
The game crashes while creating or entering the world

### ISSUE THREAD

**Issue by Hlwyefeng** [CleanroomMC/Cleanroom#151]
### Cleanroom Version

cleanroom-0.2.1-alpha

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

https://mclo.gs/PdPrPNm

### Mod List

https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod/files/3865259
https://www.curseforge.com/minecraft/mc-mods/secretroomsmod/files/2561617

### MMC Instance Notes

no

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Known bug of secretrooms. The file it tried to access is no longer available on its website.
A workaround is try add `com.wynprice.secretroomsmod.handler.HandlerUpdateChecker` to connection blocking list of fugue.cfg

**Comment by Hlwyefeng** [comment]
Thank you for your answer. Thank you for your hard work!
