### ISSUE TITLE
Xnet incompatibility

### ISSUE THREAD

**Issue by DavidSarif** [CleanroomMC/Cleanroom#152]
### Cleanroom Version

0.2.1-alpha

### Java Version

Other (Please Specify)

### Graphics Card Vendor

NVidia

### Bug Report

Java 22; E2E:E modpack.

Can't create energy channel in Xnet Controller block: button just does not do anything.

After clicking the button crashlog shows: "java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class mcjty.xnet.apiimpl.energy.EnergyConnectorSettings".
[crash-2024-05-31_20.21.53-server.txt](https://github.com/user-attachments/files/15516923/crash-2024-05-31_20.21.53-server.txt)
[latest.log](https://github.com/user-attachments/files/15517086/latest.log)

### Mod List

 Fragment with mods from latest.log:
[Mods.txt.txt](https://github.com/user-attachments/files/15517085/Mods.txt.txt)

### MMC Instance Notes

Sorry, can't find where to get it =(

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by Ecdcaeb** [comment]
```log
Caused by: java.lang.IncompatibleClassChangeError: Method 'com.google.common.collect.ImmutableSet com.google.common.collect.ImmutableSet.of(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object[])' must be Methodref constant
    at mcjty.xnet.apiimpl.energy.EnergyConnectorSettings.<clinit>(EnergyConnectorSettings.java:35)
```
When I try only Xnet and its depends it doesn't crash.
Oh, a bug hard to locate
might be a broken mod jar file or broken transformer,
You can try to create the smallest mod pack that can reproduce the crash.

**Comment by kappa-maintainer** [comment]
Please try the latest fugue from action + Cleanroom from action

**Comment by DavidSarif** [comment]
Still the same behaviour (universal-0.2.1-alpha+build.10.run.616; +Fugue-1.12.2-0.14.12), can't recognize if the error is the same.
[crash-2024-06-01_20.44.37-server.txt](https://github.com/user-attachments/files/15522768/crash-2024-06-01_20.44.37-server.txt)

**Comment by Ecdcaeb** [comment]
> Still the same behaviour (universal-0.2.1-alpha+build.10.run.616; +Fugue-1.12.2-0.14.12), can't recognize if the error is the same. [crash-2024-06-01_20.44.37-server.txt](https://github.com/user-attachments/files/15522768/crash-2024-06-01_20.44.37-server.txt)
```
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IncompatibleClassChangeError: Method 'com.google.common.collect.ImmutableSet com.google.common.collect.ImmutableSet.of(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object[])' must be Methodref constant [in thread "Server thread"]
    at mcjty.xnet.apiimpl.energy.EnergyConnectorSettings.<clinit>(EnergyConnectorSettings.java:35)
```

same

**Comment by kappa-maintainer** [comment]
I mean the fugue from [action](https://github.com/CleanroomMC/Fugue/actions)
Local test worked

**Comment by DavidSarif** [comment]
> I mean the fugue from [action](https://github.com/CleanroomMC/Fugue/actions) Local test worked

Yes, I used the latest Fugue from action; that one, where you tried to fix Xnet.

**Comment by kappa-maintainer** [comment]
Hmmm
iirc prism won't add a file with same name, try to remove the old fugue and add the new one
If it still not working, add `-Dfoundation.dump=true` and upload `EnergyConnectorSettings.class` from `CLASS_DUMP` under `.minecraft`

**Comment by DavidSarif** [comment]
Removed Fugue, added manually Fugue from actions. No effect.
Class dump attached:
[EnergyConnectorSettings.class.txt](https://github.com/user-attachments/files/15525718/EnergyConnectorSettings.class.txt)

**Comment by kappa-maintainer** [comment]
I rechecked the original class file and found the first crash report didn't make any sense
Anyway, try the latest fugue from action. I used another library to patch this

**Comment by DavidSarif** [comment]
It worked! No crashes; controller and connectors work as intended. Thank you.
