### ISSUE TITLE
Crash with Modular Machinery: Community Edition

### ISSUE THREAD

**Issue by UraraChiya** [CleanroomMC/Cleanroom#154]
### Cleanroom Version

0.2.1-alpha+build.10.run.616

### Java Version

Java 21

### Graphics Card Vendor

Intel iGPU

### Bug Report

I have searched the issues and found that this bug had been fixed in MMCE-pre4. But it still crashed when I used the pre4 and pre6 with the lasted Cleanroom.
pre-4 https://mclo.gs/pJpgxWa
pre-6 https://mclo.gs/cxJp0Dn

### Mod List

+Fugue-1.12.2-0.14.12.jar
CraftTweaker2-1.12-4.1.20.jar
ModularMachinery-CE-2.0.0-pre4.jar.disabled
ModularMachinery-CE-2.0.0-pre6.jar
scalar-1.12.2-2.11.1.jar

### MMC Instance Notes

This instance is built using Github Action.
Using installer artifact from commit: e84be9cfe4d475e38b2139816a1d151f3a4cf2fb
Action URL: https://github.com/CleanroomMC/Cleanroom/actions/runs/9189505553

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by sddsd2332** [comment]
Through the crash log of pre6, [AE2UEL](https://www.curseforge.com/minecraft/mc-mods/ae2-extended-life)needs to be installed

**Comment by UraraChiya** [comment]
> Through the crash log of pre6, [AE2UEL](https://www.curseforge.com/minecraft/mc-mods/ae2-extended-life) needs to be installed

Installing ae2uel worked. But there are still other mods that had NoClassDefFoundError. https://mclo.gs/UJHtUol

**Comment by sddsd2332** [comment]
You need to update NovaEngineering-Core

**Comment by KasumiNova** [comment]
This is not a cleanroom issue, please contact the mod author to fix this.
