### ISSUE TITLE
Crash when placing controller from MoreRefinedStorage

### ISSUE THREAD

**Issue by MDMCK10** [CleanroomMC/Cleanroom#157]
### Cleanroom Version

0.2.2-alpha

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

latest.log: https://mclo.gs/gUYDbfX

How to reproduce:
1. Add https://www.curseforge.com/minecraft/mc-mods/morerefinedstorage/files/3818846 to an instance (in this case, I used https://github.com/CleanroomMC/Cleanroom/releases/download/0.2.2-alpha/Cleanroom-MMC-instance-0.2.2-alpha.zip as base)
2. Create a new world
3. Place a Controller block
4. Crash

### Mod List

MoreRefinedStorage: https://www.curseforge.com/minecraft/mc-mods/morerefinedstorage/files/3818846

### MMC Instance Notes

N/A

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Try latest Fugue from action

**Comment by MDMCK10** [comment]
> Try latest Fugue from action

Seems to work fine, I noticed this warning when JEI/HEI isn't installed, but it doesn't seem to affect anything:
```
[12:31:07] [Client thread/WARN] [mixin]: Reference map 'fugue.mixin.refmap.json' for fugue.mixin.mod.json could not be read. If this is a development environment you can ignore this message
[12:31:07] [Client thread/WARN] [mixin]: Error loading class: mezz/jei/gui/recipes/RecipesGui (java.lang.ClassNotFoundException: The specified class 'mezz.jei.gui.recipes.RecipesGui' was not found)
[12:31:07] [Client thread/WARN] [mixin]: @Mixin target mezz.jei.gui.recipes.RecipesGui was not found fugue.mixin.mod.json:jei.RecipesGuiMixin from mod unknown-owner
```

**Comment by kappa-maintainer** [comment]
That's for another unrelated issue, it won't warn in release
