### ISSUE TITLE
FermiumASM/CensoredASM crash report "Suspected Mods" feature does not work

### ISSUE THREAD

**Issue by MDMCK10** [CleanroomMC/Cleanroom#159]
### Cleanroom Version

0.2.2-alpha

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

Log: https://mclo.gs/GXxH4Dr
To reproduce:
1. Launch an instance with FermiumASM
2. Load into a world, press F3+C to force a crash (though this issue also happens with "normal" crashes too)
3. FermiumASM fails to identify Suspected Mods due to an error (`Suspected Mods: java.lang.RuntimeException: java.lang.NoSuchMethodException: net.minecraft.launchwrapper.LaunchClassLoader.untransformName(java.lang.String)`)
![image](https://github.com/CleanroomMC/Cleanroom/assets/21245760/e5c0953b-4737-4cc9-91a8-b1dee8bb6608)

### Mod List

FermiumASM : https://www.curseforge.com/minecraft/mc-mods/fermiumasm/files/5346789

### MMC Instance Notes

N/A

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by Rongmario** [comment]
Fermium copies are not supported. Use the correct mods. E.g. CensoredASM for FermiumASM.

**Comment by MDMCK10** [comment]
> Fermium copies are not supported. Use the correct mods. E.g. CensoredASM for FermiumASM.

The issue does not appear to be FermiumASM specific, I can also reproduce it with CensoredASM, though trying to F3+C crash with CensoredASM actually hangs the game instead of crashing, but the Suspected Mods error is visible near the top of the log as well in the -- System Details -- section: https://mclo.gs/k4csWVo (Forge log for comparison: https://mclo.gs/tUKeURs)

**Comment by kappa-maintainer** [comment]
It's a known bug for a long time, I just don't remember it every time I check issue list

**Comment by kappa-maintainer** [comment]
Try latest Fugue from action
It crashed because loliasm didn't handle jrt url correctly

**Comment by MDMCK10** [comment]
> Try latest Fugue from action It crashed because loliasm didn't handle jrt url correctly

Latest build does fix the issue with CensoredASM, but I wonder, what is the reason that Fermium* is not supported?

**Comment by kappa-maintainer** [comment]
It's an outdated loliasm fork only changed the name, there's pointless to use it

**Comment by MDMCK10** [comment]
> It's an outdated loliasm fork only changed the name, it's pointless to use it

Looking at [the commit history of FermiumASM](https://github.com/fonnymunkey/FermiumASM/commits/dev/sync-5.14/), it seems to be up to date with upstream(CensoredASM) 5.20, which is the latest version. It doesn't look outdated to me.

**Comment by kappa-maintainer** [comment]
That's a news to me
Another reason is the whole Fermium series mods were created because the author hate Rong, and decided to use a worse version of Mixin when making FermiumBooter

**Comment by kappa-maintainer** [comment]
Just use loliasm, because they are identical and you still need MixinBooter for other mixin mods
Fugue won't patch the older/worse version of a mod, like I won't even check official ae2 when ae2-uel exists

**Comment by KorewaLidesu** [comment]
- We do not support FermiumASM not because it is outdated. But with the change on latest commit on both FermiumASM and FermiumBooter, there are no reason for us to support if both mods are still on active development by the fork author.
- Fugue is a hackery mod and created to fix ***outdated*** mod, that:
    + No longer received support by the author
    + Having no *active* fork version.
- Tt is the mod/fork author responsibility to work on if they want to have properly support for Cleanroom modloader rather than depended on our hackery solution.
