### ISSUE TITLE
crash with solar flux reborn

### ISSUE THREAD

**Issue by ChenHaoYan1234** [CleanroomMC/Cleanroom#161]
### Cleanroom Version

cleanroom-0.2.2-alpha+build.4.run.636

### Java Version

Java 21

### Graphics Card Vendor

Mesa/Software

### Bug Report

[latest.log](https://github.com/user-attachments/files/15815431/latest.log)
[crash-2024-06-13_15.24.55-client.txt](https://github.com/user-attachments/files/15815422/crash-2024-06-13_15.24.55-client.txt)

### Mod List

Solar Flux Reborn 12.4.11

### MMC Instance Notes

nothing

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Delete fugue.cfg and relaunch
SolarFlux patch is in default config

**Comment by kappa-maintainer** [comment]
Local test work + no response for a week
