### ISSUE TITLE
Frequent occurrence of button delay

### ISSUE THREAD

**Issue by XZYawa** [CleanroomMC/Cleanroom#164]
### Cleanroom Version
0.2.2-alpha
### Java Version
LibericaJDK21.0.3
### Graphics Card Vendor
Mesa/Software
### Bug Report
OS:Debian12.5
And I use the soft renderer provided by HMCL.
The specific situation is shown in the following gif(The bottom right corner displays the key I am currently pressing):
![output](https://github.com/CleanroomMC/Cleanroom/assets/47917763/f6edb1c0-45d8-411d-9028-845ffdffd6b0)
(It may load a bit slow.
The dirtect link:
https://github.com/CleanroomMC/Cleanroom/assets/47917763/f6edb1c0-45d8-411d-9028-845ffdffd6b0)
Button on mouse does not have this issue.
### Mod List
No any mods
### Final Checklist
- [X] I have searched the issues and haven't found a similar issue.
- [x] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [ ] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
What is this "soft renderer?"

**Comment by XZYawa** [comment]
> What is this "soft renderer?"

I'm not sure about the details,but there is the information displayed in the shadow list when OptiFine is installed:
![information](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA40AAAAeCAYAAACITvtJAAABhGlDQ1BJQ0MgcHJvZmlsZQAAKJF9kT1Iw0AcxV9btaIVByuIOGSoTnZRKY61CkWoEGqFVh1MLv2CJg1Jiouj4Fpw8GOx6uDirKuDqyAIfoA4OzgpukiJ/0sKLWI8OO7Hu3uPu3eAv1FhqtkVB1TNMtLJhJDNrQrBV/RgGP2IISYxU58TxRQ8x9c9fHy9i/Is73N/jgElbzLAJxDHmW5YxBvEsU1L57xPHGYlSSE+J5406ILEj1yXXX7jXHTYzzPDRiY9TxwmFoodLHcwKxkq8QxxRFE1yvdnXVY4b3FWKzXWuid/YSivrSxzneYYkljEEkQIkFFDGRVYiNKqkWIiTfsJD/+o4xfJJZOrDEaOBVShQnL84H/wu1uzMD3lJoUSQPeLbX+MA8FdoFm37e9j226eAIFn4Epr+6sNYPaT9HpbixwBg9vAxXVbk/eAyx1g5EmXDMmRAjT9hQLwfkbflAOGboG+Nbe31j5OH4AMdZW6AQ4OgYkiZa97vLu3s7d/z7T6+wEKSnLjempFWAAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAAuIwAALiMBeKU/dgAAAAd0SU1FB+gGFQs4Dbs/TuUAAAAZdEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAMSElEQVR42u2dTW8bVRSGx6ljkn6QlKiAVKkSXXTJj+myi9QCsWgqhLrhR7CpEKIsEKh0wZLfVVWCln4GJyQskmMzr/3Oe+54nNjV+2wix+OZe+4959w759yP3o1rW8cbg371f95UG7XPl6r9qon90SF8Pqh93r682en1CJZfff/i9X7j95bf8lt+y2/5Lb/lt/yW3/Jbfstv+U9Yq4wxxhhjjDHGGIJfGo0xxhhjjDHGUHqff/bJMaYrF8325Y3G77E8penbedO1lt/yW37Lb/ktv+W3/Jbf8lt+y2/5T3Cm0RhjjDHGGGOMXxqNMcYYY4wxxvil0RhjjDHGGGNMh/RuXd85xn/GHNkv7j+Y+aM/fvup9vnpX69qnzcG67XPOIdXbSGr5uiq3x/3Tt6Fv9z7pvG633/+oaqqqrrz1de1z2pL3E8/utKJ/PFcLA8+n7UD8uuPD2vyjxv5+KixPrEccR/1/NCDZW3/rPxI1EfUQ7T/3oNva3LfvnuvqqqqevTwu5T8cT3TO/b8KC/+f9HyM87b/pm+hp7+8uj7mv1jfSn5lf21lR/bX+ndeen/vP4v7ITpDd6f6Rvqf7Z9gtCDrPxMr9r6/ygX6gv6f9SH8/Z/2fZH/xftjvqb1f9Vkx/bn8mPerCs/R/zP4sa/5TKr/x+dvwT1zM9ZP4l9BzlV3aA8is7yPZ/bByQHS+q53c1/sf7dGX/yu8H6j2gdPzdVv6s/S96/KfaQ/k/ZxqNMcYYY4wxxlD6TZGKeKNdu3S19v1weG/mG/eyEJGFiDhcuLg1+8L1esRoFJ9HzxvvH5GitvJjhDk+q+c/fvy48b7RTv++/btVOeL5cZ/hcFhV1SSCdvHqxzP1ADNt7wtjvR89a6yH+Pz2+bPG+4W+jIjeDQ5ezba7g1czy3X05vlC5Wf6dl72j5G2qIf4G/+/AP5q3vrCdp9Xfmb/Z92+XYMRdtZvsEw72oXKCKh+imWaS/1g2H9bsL/A9kb7X3ZQnrALlmnB61dN3rb9Btrvy+OTXQ8H1XLKHfq/bP5H2mfL8U+pHk76/Xfi+7p/wplJbZ9f2k+o8WJFnt/V+B/lD/2v5rT/rN/HjGO2PmL8jRnmSfueyPFh711RubP2v+jxH9rRkMx4of7N783GGGOMMcYYYxj9/dHh1JzV7BttvDnvPahnnHDOLFujw9aysDVeDBbxiAxjZIBwrY2KQE/Ku94ofyUiB3EOCkbOMbKO9YNE5k/J/wLmMGP7skhN1BPKGxEW1IP4PWba2FxzNkcb2x3rCeewY0Qb6wHPnVHlwTWLWN9s7QTC9Iu1PwOvw3rCDDCutWTys4wws3+mb6g3Z23/bI3BbdE+zA6YfGj/of+oDyrTju0REc+hyDiqelJrbBjZNcsTe11vlAfLw/xFEH4P/SCLPMf3cb9oR3xeRH6xfOjfmF2wcmflZ4zbm2Ramf0rf8X8DmsXdf+4DuVV/R/WK/OX0Q4qw1Dqr1kmh9WXWvPF7L9t+zPYmla2hgnLrfy/6i9ZfbL2U349709y58ixmSVqRk9PjH+m/fO7lL6Xtj/aPatHNf6L8Q/7PTv3T/XfY3mS4398Lhv/MruP+5SeI4hr7JjfZ+N/VR/oH9EOWL/wYk67Z+Od0vEfrjHP9gORUVVr0tEenGk0xhhjjDHGGEPpd3kztqYFIw9qLQubYzvvGit8o8a50FnYXGpG24hr9nlt11hlI3cKzOSy8rJMm8q8YOQjnsPWmuH1bC0iRmJRP6JcbO3EpP6HM5/DMpMsw4zEdRhhjHKhPJPI3+xIqMoAIcze2AyERdk/k3/CZmP7ZO2Rfa/IrmlF1IwDFmnH+sZMi/IX2H7KPrL1ELDINCtX+EEagRX2EpFmlmlS+sAydaVyz+vHs2s8WYZpYv/N+qn0SWWQlBwsQzW+r9i9Myt/gGsmox5YffG1WsNG/7YoVKYdyxn+T9m/6i9ZfSp/iH49W7/ZmTbZ/mZVKB0vLvp5pX5dZZzV71i/Ny/hz4Ykgx7ys/6N2Ycqf9t+IfxLdk1hdvx3++6wqB9QdqTszZlGY4wxxhhjjDGUfv/KTrX9T/NuU2oOcoCZmQHZ9SdQaxVZBJ7NYWZv2GqOeqm8Mcd6Mkd7PfX7bISGEc9jc9hD/o3BYdF9ty9vFtXL9Dk66zPbWa1RyrY7i7RG5ITpWfxf1Tu7T6AywtnyKHBthYLZgdLf/pWdevsL+0d52DlDzP5xVz5sZ5ahU7sJh/zq3COmp0ovmB6z58X9s/4y7rP/ujlDqcoZdo9rgpGIWEb7r53+3dvdLaoHZf9s7TZGMPfh+qmIMKxlDHANZ5QHn4cR8ign6j/LqLPMiJKftf/Yf4pIr+oXo37YWr4A14Tj+ZHZ9sYM4PQapfWZ9RXXoV6qcwAx84b1jRmDSfttzvQ7eP141+W1k5h5n/g/1o6q/Ut/j/4/2x+zcY/qL0NuVp/Kr6M9shkKqn/HNcrZ8Qjaf9vxavZ5oUdDssZUZfbG5SHjCOz3S9ufnmtI7Af1ZHswu1yYGePyrTfqzdR9yTnYpe2P511iPxN+4Aj2JED/r/3K7H6Brfln+je+H+nXsjPQcPyj1sijv82O/5gczjQaY4wxxhhjjKF0uqaR7U7E1qbIc1OWlNI54WrtEtYbRnbbri1iPHnypPbctnPMuy6XmnteqmdqTRi7T1vGkaNB/0z1ESOh503bjO1Z09b/ZCPM51VOtSYs7H/3NMNI15YW2gfLMGLGiu0+i5l6dj1m2NB/sUx/yBPyZ/VzvPYEdlNe9vZmmZGQ/+joqKi9RyRCzq5Ta/RwLfii/A7b9Vhxp/D8slKYHUw9l4wbJnsYbLbqL5kdZH/P/F9X4zqW4Ttv1jo+B7hrSvX2jtpDRNizGgcqP7B3v8wPqHNfux4/q/KXtvui9ET1+0z+rL8Zy+33ZmOMMcYYY4wxjP6s+fwqIscyQjTCdPrmGnNwsxE/thuoWsOk7s/eqFWkFd/UWaQByxdrEDeq2eeIMfA8M7VWKcrDnj8u32mbs7nQcb9SPVDXq8joZK1C89o+pWdtI8tMf1SEqjQSy57D9D3mlmPkFdcsZTOqfbGGUdmbOvdK6V+pnqi1QcwfsPrNZmbHu72S89HYbmRKfq73s+shdgUuLSe73xGsgbyTzFBP6vsA9LO+pkPdj+3amb3+ZbL8zB4iw6b0gP1enWvL17z2G7/PtneU+3ZSf6O8cf9dcZ4XtuN0/9Lc/lgPSv9xjSaTX0XCWb3i80sz62oNXsjP+g2UC/uT+B53Q1UZ2/HeCqPn7frLU7Jr9pldlva3KL9ao8jGP5gZU+M37F9Lx3tqhgRDrbFU8jP/huXPjtuYHbHdOrPj/9AH9XvmV+N+G73c3g7qXMKQJ9o9Wx9t5Vd+SJ+zvtlq/Jc9xz7qexf2MEB/iHsOTNm935uNMcYYY4wxxjB6t67vHKs3ZZYpwfP5IiKFkXeM9GGmTa0JikgYi7xFeVnmj90f75PdvSjkzp57ouSP7yOCHhnZ+JwtJyvHVKaRRELwvtl6pOe5JK+P69SuuBGpCT0biN3BWP0qPWP6H+XGTIOKNKJcUQ7cDTfb/the2Qirul/WnliknV3f1v7Z7qhqd0UsB9Zvqd1ju6MfULszo/ys/fF7lL9tOZXfK60HlWnKrvHMllf1A6ivWfsr9at4Tla2/dG/Mf1n5czWR9b/tNWn0vZX+o33z8rP2k31fyozMXV+GvQ3Wfmz7Vpq/6X+D8uf3W26a/mVfqlMNJO/Kz+S9VPY/6nxH2v/sH817im119JxW9aO1Phf9f9qHIh+lfmr0v5K+f/S8Z+Sf97xZ7afYu2l9F+NJ7LjaWcajTHGGGOMMcZQejdv3jx+/efT2j/xzVllqlRmAud0q/Po1Lkn+Hv1po+/P/xgq/a5K/mzz7f888mP5/u5/euRPkZEkqz/lt/yt5cfI8Bu/9WSP5thDTAjtGry47l1pe2/6vJb/1dDfpa5dfsvl/zONBpjjDHGGGOMoXR6oNyynFNj3m8iw2hy9rdxxudGGvM+s2znjZoy1tbqsXIVaf8wuZvj+6qvqy6/Wa1xncqcmXP2n64CY4wxxhhjjDGM3o1rW1O7p6rdDhXqHDc8l4btJpp9Pj5P3V9h+S2/5bf8lt/yW37Lb/ktv+W3/Jb/BGcajTHGGGOMMcZQ/NJojDHGGGOMMYbyH/MiQZyrKGtkAAAAAElFTkSuQmCC)

**Comment by kappa-maintainer** [comment]
Try default OpenGL and other options and see if there are different
I assume it's using some kind of wrapper and is breaking lwjgl

**Comment by XZYawa** [comment]
> Try default OpenGL and other options and see if there are different I assume it's using some kind of wrapper and is breaking lwjgl

Problem disappeared!
Thanks!
But this is not a perfect solution,and no problems on original Forge(I remembered).
May I should send a issue to HMCL?

**Comment by kappa-maintainer** [comment]
The LWJGL we are using is a custom one and known to be buggy, using LWJGL3 on 1.12 is new to many launchers too
Since HMCL is not a support target, I will close this issue. But next LWJGL release may fix the problem, so stay tune

**Comment by XZYawa** [comment]
> The LWJGL we are using is a custom one and known to be buggy, using LWJGL3 on 1.12 is new to many launchers too Since HMCL is not a support target, I will close this issue. But next LWJGL release may fix the problem, so stay tune

Ok.
