### ISSUE TITLE
和星空（GalaxySpace）不兼容

### ISSUE THREAD

**Issue by FuBangkun** [CleanroomMC/Cleanroom#166]
### Cleanroom Version

0.2.2-alpha

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

crash-reports、latest.log和debug.log：[https://wwi.lanzoup.com/iRFxx239e69e](https://wwi.lanzoup.com/iRFxx239e69e)
不是星空前置Asmodeus Core的问题

### Mod List

Galacticraft4.0.6
Asmodeus Core1.0.2
Galaxy Space2.1.4
fugue0.15.7
scalar2.11.1

### MMC Instance Notes

Plain Craft Launcher 2

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by Oganesson897** [comment]
下次记得用 [Pastebin](mclo.gs) 把报错文件发上来

**Comment by FuBangkun** [comment]
[https://mclo.gs/RPdfvRQ](https://mclo.gs/RPdfvRQ)

**Comment by kappa-maintainer** [comment]
这种的一眼没用prism
建议参照mcmod教程删除老版本的库
