### ISSUE TITLE
5zig/5zig reborn崩溃及询问黑白名单功能

### ISSUE THREAD

**Issue by xx146542xx** [CleanroomMC/Cleanroom#167]
### Cleanroom Version

cleanroom-0.2.2-alpha release页面下载的

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

[2024-06-27-5.log](https://github.com/user-attachments/files/16060052/2024-06-27-5.log)
https://github.com/5zig/The-5zig-Mod
https://github.com/5zig-reborn
顺便问下有没有办法通过加特殊关键词前缀使得mod cleanroom不加载 但是原版forge可以加载 以及在特殊路径加载cleanroom专用mod[fugue scalar等]但原版forge不加载

### Mod List

"Xtones-1.2.2.jar" "![___MixinCompat-1.1-1.12.2___].jar" "!configanytime-1.0.jar.disabled" "!Red-Core-MC-1.7-1.12-0.5.1.jar" "_MixinBootstrap-1.1.0.jar" "+Fugue-1.12.2-0.15.7.jar" "ActuallyAdditions-1.12.2-r152.jar" "ActuallyBaubles-1.12-1.1.jar" "AdvancedRocketry-1.12.2-1.7.0-232-universal.jar" "advsolars-1.0.jar" "ae2stuff-0.7.0.4-mc1.12.2.jar" "AE2WTLib-1.12.2-1.0.34.jar" "Alfheim-1.1.1.jar" "AppleSkin-mc1.12-1.0.14.jar" "appliedenergistics2-rv6-stable-7-extended_life-v0.55.27.jar" "architecturecraft-1.12-3.98.jar" "armorplus-1.12.2-11.25.1.62.jar" "AutoRegLib-1.3-32.jar" "Avaritia-1.12.2-3.3.0.37-universal.jar" "base-1.12.2-3.14.0.jar" "Baubles-1.12-1.5.2.jar" "bdlib-1.14.4.1-mc1.12.2.jar" "betterchat-1.4.jar" "BetterFps-1.4.8.jar" "betterp2p-1.12.2-1.2.3-extended_life.jar" "BetterQuestingUnofficial-4.2.1.jar" "bogosorter-1.4.6.jar" "Bookshelf-1.12.2-2.3.590.jar" "Bountiful-2.2.2.jar" "BrandonsCore-1.12.2-2.4.20.162-universal.jar" "BuildingGadgets-2.8.4.jar" "censoredasm5.18.jar" "Chameleon-1.12-4.1.3.jar" "ChestTransporter-1.12.2-2.8.8.jar" "Chisel-MC1.12.2-1.0.2.45.jar" "ClientTweaks_1.12.2-3.1.11.jar" "Clumps-3.1.2.jar" "CodeChickenLib-1.12.2-3.2.3.358-universal.jar" "CoFHCore-1.12.2-4.6.6.1-universal.jar" "CoFHWorld-1.12.2-1.4.0.1-universal.jar" "collective-1.12.2-3.0.jar" "Controlling-3.0.12.2.jar" "CraftableElytra-1.1.jar" "CraftingNetherStar 1.12.1 -1.1.jar" "CraftingTweaks_1.12.2-9.0.1.jar" "CraftPresence-2.3.5+1.12.2.jar" "CraftTweaker2-1.12-4.1.20.692.jar" "CreativeCore_v1.10.71_mc1.12.2.jar" "CTM-MC1.12.2-1.0.2.31.jar" "Cucumber-1.12.2-1.1.3.jar" "customfov-1.12.2-1.0.jar" "CustomMainMenu-MC1.12.2-2.0.9.1.jar" "CustomSelectionBox-1.12.2-1.4.6.jar" "DarkUtils-1.12.2-1.8.230.jar" "DeepMobEvolution-1.12.2-1.2.1.jar" "DefaultWorldGenerator-port-1.12-2.3.1.jar" "DenseMetals-1.12.2-2.0.0.30.jar" "difficultylock_1.12.2-1.2.jar" "DimensionalEdibles-1.12.2-1.6.4.jar" "Draconic-Evolution-1.12.2-2.3.28.354-universal.jar" "dynamistics-1.0.2.jar" "effortlessbuilding-1.12.2-2.16.jar" "ElevatorMod-1.12.2-1.3.14.jar" "EnchantmentDescriptions-1.12.2-1.1.15.jar" "EnderCore-1.12.2-0.5.78.jar" "EnderIO-1.12.2-5.3.72.jar" "EnderIO-endergy-1.12.2-5.3.72.jar" "EnderStorage-1.12.2-2.4.6.137-universal.jar" "extendedcrafting-nomifactory-edition-1.7.0.6.jar" "extrautils2-1.12-1.9.9.jar" "FasterLadderClimbing-1.12-0.1-146.jar" "Forgelin-1.8.4.jar" "ForgeMultipart-1.12.2-2.6.2.83-universal.jar" "ForgivingVoid_1.12.2-1.1.0.jar" "FpsReducer-mc1.12.2-1.20.jar" "framedcompactdrawers-1.2.7.jar" "FTBBackups-1.1.0.1.jar" "FTBLib-5.4.7.2.jar" "ftb-ultimine-1202.3.5.jar" "FTBUtilities-5.4.1.131.jar" "GregicalityMultiblocks-1.2.8.jar" "gregtech-1.12.2-2.8.7-beta.jar" "gregtech-drawers-1.12.2-1.0.7.jar" "groovyscript-0.8.0.jar" "HadEnoughItems_1.12.2-4.25.0.jar" "hecharacters-1.12.2-1.4.1.jar" "hooked-1.0.3.jar" "I18nUpdateMod-3.4.2-all.jar" "jecharacters-1.12.0-3.7.2.jar" "JEI-Utilities-1.12.2-0.2.12.jar" "journeymap-1.12.2-5.7.1.jar" "JustEnoughCalculation-1.12.2-3.2.7.jar" "justenoughdimensions-1.12.2-1.6.0-dev.20200416.184714.jar" "JustEnoughResources-1.12.2-0.9.2.60.jar" "librarianlib-1.12.2-4.22.jar" "LibVulpes-1.12.2-0.4.2-75-universal.jar" "LittleTiles_v1.5.81_mc1.12.2.jar" "lootcapacitortooltips-1.3.jar" "lostcities-1.12-2.0.22.jar" "modnametooltip_1.12.2-1.10.1.jar" "modtweaker-4.0.20.5.jar" "modularui-2.4.2.jar" "MoreFurnaces-Nomifactory-Edition-1.12.2-1.11.0.jar" "morelibs-1.12.2-1.2.2.jar" "moreoverlays-1.15.1-mc1.12.2.jar" "moreplates-1.12.2-5.5.2.jar" "moresoundconfig-1.0.4.jar" "Morpheus-1.12.2-3.5.106.jar" "mousetweaks-1.12.2-3.1.4.jar" "MrTJPCore-1.12.2-2.1.4.43-universal.jar" "MTLib-3.0.7.jar" "nae2-1.3.1.jar" "NaturesCompass-1.12.2-1.8.5.jar" "NomiLabs-0.6.28.jar" "nonetherportals-1.1.0.jar" "NuclearCraft-2.18y-1.12.2.jar" "oauth-1.06.4.jar" "OpenGlider-1.12.1-1.1.0.jar" "p455w0rdslib-1.12.2-2.3.161.jar" "PackagedAuto-1.12.2-1.0.11.40.jar" "PackagedExCrafting-1.12.2-1.0.2.10.jar" "packmode-1.12.2-1.2.0.jar" "Patchouli-1.0-23.6.jar" "Placebo-1.12.2-1.6.0.jar" "ProjectIntelligence-1.12.2-1.0.9.28-universal.jar" "ProjectRed-1.12.2-4.9.4.120-Base.jar" "ProjectRed-1.12.2-4.9.4.120-integration.jar" "randompatches-1.12.2-1.22.1.10.jar" "RealBench-Nomi-CEu-1.0.4.jar" "RedstoneArsenal-1.12.2-2.6.6.1-universal.jar" "RedstoneFlux-1.12-2.1.1.1-universal.jar" "ResourceLoader-MC1.12.1-1.5.3.jar" "scalar-1.12.2-2.11.1.jar" "scalar-1.12.2-2.11.1-dev.jar.disabled" "scalingguis-1.12.2-1.0.3.0.jar" "serializationisbad-1.5.2.jar" "SimplyJetpacks2-1.12.2-2.2.15.69.jar" "SmoothFont-mc1.12.2-2.1.4.jar" "Snad-1.12.1-1.7.09.16a.jar" "SolarFluxReborn-1.12.2-12.4.11.jar" "spark-forge1122.jar" "StorageDrawers-1.12.2-5.5.0.jar" "supersoundmuffler-revived_1.12.2_1.0.2.10.jar" "thedragonlib-1.12.2-5.3.0.jar" "theoneprobe-1.12-1.4.28.jar" "ThermalCultivation-1.12.2-0.3.6.1-universal.jar" "ThermalExpansion-1.12.2-5.5.7.1-universal.jar" "ThermalFoundation-1.12.2-2.6.7.1-universal.jar" "ThermalInnovation-1.12.2-0.3.6.1-universal.jar" "TipTheScales-1.12.2-1.0.4.jar" "TombManyGraves-1.12-4.2.0.jar" "ToolBelt-1.12.2-1.9.14.jar" "topaddons-1.12.2-1.13.0.jar" "torchmaster_1.12.2-1.8.5.0.jar" "TrashSlot_1.12.2-8.4.10.jar" "ULVCovers-1.12.2-2.8.0.jar" "UniversalTweaks-1.12.2-1.11.0.jar" "vintagefix-0.5.0-19-g9b42645.jar" "visualores-0.2.4.jar" "WirelessCraftingTerminal-1.12.2-3.12.97.jar" "wi-zoom-v1.1-MC1.12.2-release.jar" "worleycaves-1.12.2-1.5.2.jar" "chunkgenlimiter-1.1-core.jar" "codecjlayermp3-1.0.0-SNAPSHOT.jar" "config-1.2.1.jar" "config-1.4.3.jar" "jlayer-1.0.1.jar" "nashorn.jar" "scala-actors-2.11.0.jar" "scala-actors-migration_2.11-1.1.0.jar" "scala-compiler-2.11.1.jar" "scala-continuations-library_2.11-1.0.2_mc.jar" "scala-continuations-plugin_2.11.1-1.0.2_mc.jar" "scala-library-2.11.1.jar" "scala-library-2.13.13.jar" "scala-parser-combinators_2.11-1.0.1.jar" "scala-reflect-2.11.1.jar" "scala-swing_2.11-1.0.1.jar" "scala-xml_2.11-1.0.2.jar" "WrapUp-1.12-1.1.3.jar" "akka-actor_2.11-2.3.3.jar" "cats-core_3-2.10.0.jar" "cats-kernel_3-2.10.0.jar" "ChickenASM-1.12-1.0.2.7.jar" 

### MMC Instance Notes

/

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by ZZZank** [comment]
- 模组列表也太大了，没有测试过只安装5zig的情况？
- log可以用mclo.gs之类的网站上传，单传文件对接受者来说并不方便

> 有没有办法通过加特殊关键词前缀使得mod cleanroom不加载

当然不可能，你在用的可不就是Cleanroom，为什么要Cleanroom不加载

---

related parts in latest.log:
```
[19:57:57] [main/WARN]: eu.the5zig.mod.asm.transformers.PatchGuiChat$PatchGuiClosed can't handle Java 21 class, please port the mod (if you are the author)!
[19:57:57] [main/WARN]: eu.the5zig.mod.asm.transformers.PatchGuiChat$PatchKeyTyped can't handle Java 21 class, please port the mod (if you are the author)!
[19:57:57] [main/WARN]: eu.the5zig.mod.asm.transformers.PatchGuiChat$PatchHandleMouseInput can't handle Java 21 class, please port the mod (if you are the author)!
[19:57:57] [main/WARN]: eu.the5zig.mod.asm.transformers.PatchGuiChat$PatchMouseClicked can't handle Java 21 class, please port the mod (if you are the author)!
[19:57:57] [main/WARN]: eu.the5zig.mod.asm.transformers.PatchGuiChat$PatchDrawScreen can't handle Java 21 class, please port the mod (if you are the author)!
[19:57:57] [main/WARN]: eu.the5zig.mod.asm.transformers.PatchGuiIngameMenu$ClassPatcher can't handle Java 21 class, please port the mod (if you are the author)!
[19:57:57] [main/WARN]: eu.the5zig.mod.asm.transformers.PatchGuiIngameMenu$PatchActionPerformed can't handle Java 21 class, please port the mod (if you are the author)!
[19:57:58] [main/WARN]: eu.the5zig.mod.asm.transformers.PatchGuiIngame$ClassPatcher can't handle Java 21 class, please port the mod (if you are the author)!
[19:57:58] [main/WARN]: eu.the5zig.mod.asm.transformers.PatchGuiIngame$PatchRenderGameOverlay can't handle Java 21 class, please port the mod (if you are the author)!
[19:57:58] [main/WARN]: eu.the5zig.mod.asm.transformers.PatchGuiIngame$PatchPotionEffectIndicator can't handle Java 21 class, please port the mod (if you are the author)!
[19:57:58] [main/WARN]: eu.the5zig.mod.asm.transformers.PatchGuiIngame$PatchRenderHotbar can't handle Java 21 class, please port the mod (if you are the author)!
[19:57:58] [main/WARN]: eu.the5zig.mod.asm.transformers.PatchGuiIngame$PatchFood can't handle Java 21 class, please port the mod (if you are the author)!
[19:57:58] [main/WARN]: eu.the5zig.mod.asm.transformers.PatchGuiIngame$PatchVignette can't handle Java 21 class, please port the mod (if you are the author)!
[19:57:58] [main/WARN]: eu.the5zig.mod.asm.transformers.PatchGuiIngame$PatchTick can't handle Java 21 class, please port the mod (if you are the author)!
[19:57:58] [main/FATAL]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at top.outlands.foundation.LaunchHandler.launch(LaunchHandler.java:119) [LaunchHandler.class:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at top.outlands.foundation.boot.Foundation.main(Foundation.java:41) [foundation-0.13.7.jar:?]
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraft/client/Minecraft.func_71384_a()V @1064: putfield
  Reason:
    Type 'net/minecraftforge/client/GuiIngameForge' (current frame, stack[1]) is not assignable to 'net/minecraft/client/gui/GuiIngame'
  Current Frame:
    bci: @1064
    flags: { }
    locals: { 'net/minecraft/client/Minecraft', 'net/minecraftforge/fml/common/ProgressManager$ProgressBar' }
    stack: { 'net/minecraft/client/Minecraft', 'net/minecraftforge/client/GuiIngameForge' }
```

**Comment by xx146542xx** [comment]
> * 模组列表也太大了，没有测试过只安装5zig的情况？
> * log可以用mclo.gs之类的网站上传，单传文件对接受者来说并不方便
> 
> > 有没有办法通过加特殊关键词前缀使得mod cleanroom不加载
> 
> 当然不可能，你在用的可不就是Cleanroom，为什么要Cleanroom不加载
> 
> related parts in latest.log:
> 
> ```
> [19:57:57] [main/WARN]: eu.the5zig.mod.asm.transformers.PatchGuiChat$PatchGuiClosed can't handle Java 21 class, please port the mod (if you are the author)!
> [19:57:57] [main/WARN]: eu.the5zig.mod.asm.transformers.PatchGuiChat$PatchKeyTyped can't handle Java 21 class, please port the mod (if you are the author)!
> [19:57:57] [main/WARN]: eu.the5zig.mod.asm.transformers.PatchGuiChat$PatchHandleMouseInput can't handle Java 21 class, please port the mod (if you are the author)!
> [19:57:57] [main/WARN]: eu.the5zig.mod.asm.transformers.PatchGuiChat$PatchMouseClicked can't handle Java 21 class, please port the mod (if you are the author)!
> [19:57:57] [main/WARN]: eu.the5zig.mod.asm.transformers.PatchGuiChat$PatchDrawScreen can't handle Java 21 class, please port the mod (if you are the author)!
> [19:57:57] [main/WARN]: eu.the5zig.mod.asm.transformers.PatchGuiIngameMenu$ClassPatcher can't handle Java 21 class, please port the mod (if you are the author)!
> [19:57:57] [main/WARN]: eu.the5zig.mod.asm.transformers.PatchGuiIngameMenu$PatchActionPerformed can't handle Java 21 class, please port the mod (if you are the author)!
> [19:57:58] [main/WARN]: eu.the5zig.mod.asm.transformers.PatchGuiIngame$ClassPatcher can't handle Java 21 class, please port the mod (if you are the author)!
> [19:57:58] [main/WARN]: eu.the5zig.mod.asm.transformers.PatchGuiIngame$PatchRenderGameOverlay can't handle Java 21 class, please port the mod (if you are the author)!
> [19:57:58] [main/WARN]: eu.the5zig.mod.asm.transformers.PatchGuiIngame$PatchPotionEffectIndicator can't handle Java 21 class, please port the mod (if you are the author)!
> [19:57:58] [main/WARN]: eu.the5zig.mod.asm.transformers.PatchGuiIngame$PatchRenderHotbar can't handle Java 21 class, please port the mod (if you are the author)!
> [19:57:58] [main/WARN]: eu.the5zig.mod.asm.transformers.PatchGuiIngame$PatchFood can't handle Java 21 class, please port the mod (if you are the author)!
> [19:57:58] [main/WARN]: eu.the5zig.mod.asm.transformers.PatchGuiIngame$PatchVignette can't handle Java 21 class, please port the mod (if you are the author)!
> [19:57:58] [main/WARN]: eu.the5zig.mod.asm.transformers.PatchGuiIngame$PatchTick can't handle Java 21 class, please port the mod (if you are the author)!
> [19:57:58] [main/FATAL]: Unable to launch
> java.lang.reflect.InvocationTargetException: null
> 	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118) ~[?:?]
> 	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
> 	at top.outlands.foundation.LaunchHandler.launch(LaunchHandler.java:119) [LaunchHandler.class:?]
> 	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
> 	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
> 	at top.outlands.foundation.boot.Foundation.main(Foundation.java:41) [foundation-0.13.7.jar:?]
> Caused by: java.lang.VerifyError: Bad type on operand stack
> Exception Details:
>   Location:
>     net/minecraft/client/Minecraft.func_71384_a()V @1064: putfield
>   Reason:
>     Type 'net/minecraftforge/client/GuiIngameForge' (current frame, stack[1]) is not assignable to 'net/minecraft/client/gui/GuiIngame'
>   Current Frame:
>     bci: @1064
>     flags: { }
>     locals: { 'net/minecraft/client/Minecraft', 'net/minecraftforge/fml/common/ProgressManager$ProgressBar' }
>     stack: { 'net/minecraft/client/Minecraft', 'net/minecraftforge/client/GuiIngameForge' }
> ```

我的意思是我想打包一份forge+cleanroom双版本的让玩家自主选择,但是做版本隔离占用空间就太大了 想通过特殊手段让加载器不加载/从别的目录加载某些mod来实现兼容共存

**Comment by xx146542xx** [comment]
久等了 三件套全换了最新的action的文件 还是无法启动 只有一个5zig https://mclo.gs/boNjluu

**Comment by kappa-maintainer** [comment]
试试这个
https://github.com/CleanroomMC/Fugue/actions/runs/9758874349

**Comment by xx146542xx** [comment]
这次的可以了 那关于mod黑白名单的事情是没法实现还是?

**Comment by kappa-maintainer** [comment]
目前已经有避免Cleanroom模组被Forge加载的机制，但反向的机制仍未实现
这部分内容适宜在别的地方讨论
