### ISSUE TITLE
大量mod报错

### ISSUE THREAD

**Issue by chenming0v0** [CleanroomMC/Cleanroom#168]
### Your CleanroomMC Discord Username

chenming#3549

### Cleanroom Version

0.2.2-alpha

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

我在将clr切换为新版本时:
![ffcc1e94538510b99559bc502143b452](https://github.com/CleanroomMC/Cleanroom/assets/122023652/7b5a9dd7-7c6e-4818-bfc2-74bae8a4535c)

https://mclo.gs/S0ssnMi爆了（Into The Maelstrom）
https://mclo.gs/4H6s71l爆了（moretcon）
https://mclo.gs/BVGPtBJ（Extra Utilities 2）
https://mclo.gs/Ht2H8mF（Avaritia）
https://mclo.gs/QaMUNor（Random Things）
https://mclo.gs/gVEtwe7（CodeChicken Lib Crl修复版）

### Mod List

见报错日志中的mod

### MMC Instance Notes

没有

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by Oganesson897** [comment]
你的链接是人能发出来的？

**Comment by LonelyxiyaOVO** [comment]
逆天

**Comment by kappa-maintainer** [comment]
建议切换到CRL最新的action build试试

**Comment by kappa-maintainer** [comment]
有无更新

**Comment by chenming0v0** [comment]
问题已经解决，请使用原版的鸡块核心而不是早期修复版的，并且用最新的Fugue，Scalar即可解决
