### ISSUE TITLE
Incompatible with Ears mod/Rotn modpack

### ISSUE THREAD

**Issue by Xplodin** [CleanroomMC/Cleanroom#169]
### Your CleanroomMC Discord Username

autismo bean

### Cleanroom Version

0.2.2

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

https://mclo.gs/e9iGMcM

game crashes during loading.
also incompatible with Sampler. (which is why its disabled in this instance)

### Mod List

  [✔] !configanytime-1.0
  [✔] !mixinbooter-8.8
  [✔] !mod-director-launchwrapper-1.8.2-all
  [✔] [___MixinCompat-1.1-1.12.2___]
  [✔] _MixinBootstrap-1.1.0
  [✔] `FermiumBooter-1.1.0
  [✔] +Fugue-1.12.2-0.15.8
  [✔] aactadapter-1.12.2-0.1.0
  [✔] AdPother-1.12.2-1.2.25.0-build.0673
  [✔] AdvancedLiftingMethods-1.12.2-1.0.0
  [✔] advancedmortars-1.12.2-1.7.1
  [✔] AdvancementPlaques-1.12.2-1.4.10
  [✔] aeble_v1.4.3
  [✔] aesthetics-1.12.2-1.6.0.23
  [✔] Aether Continuation v1.3.0
  [✔] aether-1.12.2-v1.5.4.0
  [✔] AggroTP-0.4.1
  [✔] AIReducer-1.12.2-0.3.0
  [✔] ancientbeasts-1.9.99999
  [✔] animania-1.12.2-1.7.3
  [✔] antighost-1.12-forge14.21.1.2387-1.1.1
  [✔] antiqueatlas-1.12.2-4.6.3
  [✔] anvilpatch-1.1.1
  [✔] AppleCore-mc1.12.2-3.4.0
  [✔] AppleSkin-mc1.12-1.0.14
  [✔] AquaAcrobatics-1.15.3
  [✔] arcanearchives-0.2.0.25-mixins8
  [✔] arcaneworld-1.12.2-0.1.0
  [✔] arrowharvest-1.12.2-1.0.3
  [✔] artifacts-1.12.2-1.2.4
  [✔] artisanintegrations-1.12.2-1.3.0
  [✔] artisanworkstumps-1.12.2-1.1.4
  [✔] artisanworktables-1.12.2-1.24.2
  [✔] athenaeum-1.12.2-1.19.6
  [✔] Atlas-Lib-1.12.2-1.1.5a
  [✔] ATOP-1.12.2-v.1.6
  [✔] AutoRegLib-1.3-32
  [✔] base-1.12.2-3.14.0
  [✔] basketcase-v2.1.109-mc1.12.2
  [✔] Baubles-1.12-1.5.2
  [✔] behgameon-1.1.2-1.12.2
  [✔] Better With Addons-0.51
  [✔] BetterAdvancements-1.12.2-0.1.0.77
  [✔] betteranimals-1.12.2-5.5.0
  [✔] betteranimalsplus-1.12.2-9.0.1
  [✔] betterbiomeblend-1.12.2-1.1.7-forge
  [✔] bettercaves-1.12.2-2.0.4
  [✔] BetterFps-1.4.8
  [✔] betterhud-1.12.2-1.4.4
  [✔] betterinvisibility-1.0.1
  [✔] BetterMineshaftsForge-1.12.2-2.2.1
  [✔] BetterNetherRotN-1.12.2-0.1.9.4
  [✔] BetterSlimes-1.12.2-1.3.4
  [✔] BetterThanMending-1.1.2
  [✔] BetterWaterSplash-1.0
  [✔] BetterWithLib-1.12-1.5
  [✔] BetterWithMods-1.12-2.3.24
  [✔] BHMenu-Forge-1.12.2-2.4.1
  [✔] biomeinfo-1.12.2-v1.2.5
  [✔] BiomesOPlenty-1.12.2-7.0.1.2445-universal
  [✔] BiomeTweaker-1.12.2-3.2.369
  [✔] BiomeTweakerCore-1.12.2-1.0.39
  [✔] Blur-1.0.4-14
  [✔] BNBGamingCore-1.12.2-0.12.0
  [✔] BNBGamingLib-1.12.2-2.17.6
  [✔] Bookshelf-1.12.2-2.3.590
  [✔] Bountiful Baubles-1.12.2-0.1.8
  [✔] Bountiful-1.12.2-2.2.3
  [✔] Bundles-1.1
  [✔] butterflies-1.12.2-1.0.3
  [✔] Caliper-1.12.2-1.1.46
  [✔] carryon-1.12.2-1.12.7.23
  [✔] CaveGenerator-1.2-1.12.2
  [✔] CD4017BE_lib-1.12.2-6.5.1
  [✔] Ceramics-1.12-1.3.7b
  [✔] chargethrower-1.0.1
  [✔] Charm-1.12.2-1.4.1
  [✔] Charset-Lib-0.5.6.6
  [✔] Charset-StorageChests-0.5.6.6
  [✔] Charset-ToolsEngineering-0.5.6.0
  [✔] Charset-TransportCartsRails-0.5.6.4
  [✔] ChatFlow-1.4-7
  [✔] cherishedworlds-1.12.2-1.0.1
  [✔] ChunkAnimator-1.12.2-1.2.1
  [✔] chutes-1.12.2-1.0.0
  [✔] ClientTweaks_1.12.2-3.1.11
  [✔] Clipboard-1.12-1.3.0
  [✔] Clumps-3.1.2
  [✔] CoFHWorld-1.12.2-1.4.0.1-universal
  [✔] collective-1.12.2-3.0
  [✔] ColouredTooltips-1.12.2-1.0.9
  [✔] combatrefined-1.4.1
  [✔] ConsoleHUD-v1.4.2-1.12.2
  [✔] ContentCreator-1.3.7-fix2
  [✔] ContentTweaker-1.12.2-4.10.0
  [✔] Controlled Burn-1.12.2.022
  [✔] Controlling-3.0.12.2
  [✔] copypaste-1.1
  [✔] coroutil-1.12.1-1.2.37
  [✔] corpsecomplex-1.12.2-1.0.12.0
  [✔] CosmeticArmorReworked-1.12.2-v5a
  [✔] CraftingCraft_1.12-6.1.3
  [✔] CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha
  [✔] CraftTweaker2-1.12-4.1.20.698
  [✔] crafttweakerutils-0.7
  [✔] CTM-MC1.12.2-1.0.2.31
  [✔] customdisc-1.3
  [✔] CustomLoadingScreen-1.12.2-1.5.7
  [✔] customnausea-1.12.2-1.0
  [✔] Cyclic-1.12.2-1.20.14
  [✔] DamageControl-1.12.2-1.3.17
  [✔] DefaultOptions_1.12.2-9.2.8
  [✔] defiledlands-1.12.2-1.4.3
  [✔] demonic_scythe-1.3
  [✔] DimensionStages-1.12.2-2.0.23
  [✔] discordrpc-1.3.3-1.12
  [✔] DoggyTalents-1.12.2-1.15.1.6
  [✔] DramaticTrees-1.12.2-0.13.3
  [✔] dropt-1.12.2-1.19.3
  [✔] dropt-bed-1.12.2-1.0.1
  [✔] Dung Pipe-1.2
  [✔] DungeonTactics-1.12.2-0.16.9
  [✔] DynamicSurroundings-1.12.2-3.6.1.0
  [✔] DynamicTreesBOP-1.12.2-1.5.2
  [✔] dynamictreesdefiledlands-1.12.2-1.0.0
  [✔] DynamicTreesPHC-1.12.2-2.0.6
  [✔] DynamicTreesQuark-1.12.2-1.0.6
  [✔] DynamicTreesTheAether-1.12.2-1.0.14
  [✔] dynamictreesTheTwilightForest-1.12.2-1.2.3
  [✔] ears-forge-1.12-1.4.6
  [✔] Earthworks-1.12-1.3.6
  [✔] eguilib-0.1.2
  [✔] ElenaiDodge2-1.12.2-1.1.0
  [✔] EnchantingPlusPlus-1.12.2-5.1.0
  [✔] enchcontrol-1.12.2-1.1.5-0
  [✔] EndReborn [0.3.9]
  [✔] EnhancedSnowman-1.12-1.0.1
  [✔] Entifier-2.0.0
  [✔] EntityCulling-1.12.2-6.4.2
  [✔] EpicSiegeMod-13.169
  [✔] EquipmentTooltips-1.12.2-1.0.3-4
  [✔] estop-1.12.1
  [✔] exsartagine-1.12.2-0.3.12
  [✔] ExtendedDays-1.12.2-0.2.9-28
  [✔] extraalchemy-forge-1.12-build11-0.5.4
  [✔] ExtraGolems-1.12-7.1.9
  [✔] ExtraSounds-1.12.2-1.4.1
  [✔] fairylights-2.2.0-1.12.2
  [✔] fancymenu_forge_2.14.9_MC_1.12-1.12.2
  [✔] FantasticLib-1.12.2.047
  [✔] FastFurnace-1.12.2-1.3.1
  [✔] fermiumasm-5.23
  [✔] fireproofitems-1.0
  [✔] fireresistancetiers-1.0
  [✔] Fish's Undead Rising-1.3.2
  [✔] foamfix-0.10.15-1.12.2
  [✔] fogger-1.12.2-1.1.2.0
  [✔] ForgeEndertech-1.12.2-4.5.6.1-build.0648
  [✔] Forgelin-1.8.4
  [✔] FpsReducer-mc1.12.2-1.20
  [✔] from_the_depths-1.3.0.1
  [✔] Frozen-Fiend-1.5.2
  [✔] FTBBackups-1.1.0.1
  [✔] FullscreenWindowed-1.12-1.6.0
  [✔] future-mc-0.2.15
  [✔] fxcontrol-1.12-0.1.15
  [✔] GamblingStyle-v1.1.3-1.12.2
  [✔] GameStages-1.12.2-2.0.123
  [✔] geckolib-forge-1.12.2-3.0.31
  [✔] GeographiCraft-1.12-0.8.9b
  [✔] GlareTorch_Ver.8.11_[MC1.12](forge-1.12-14.21.1.2387)
  [✔] globalxp-1.12.2-v1.4.10
  [✔] growthcraft-1.12.2-4.2.2.1
  [✔] guicompass_1.12.2-1.5
  [✔] HadEnoughItems_1.12.2-4.25.1
  [✔] HardcoreDarkness-MC1.12.2-2.0
  [✔] harvestcrafttweaker-1.2c
  [✔] harvestersnight-1.12.2-1.1.0
  [✔] Hit With Axe-1.12.2-1.5.1
  [✔] hitindication-1.12.2-1.3.1
  [✔] horseinfo-1.0.1
  [✔] HorsePower-1.12.2-2.6.4.74
  [✔] HungerOverhaul-1.12.2-1.3.3.jenkins148
  [✔] HungerTweaker-1.12.2-1.3.0
  [✔] hunterillager-1.12.2-1.2
  [✔] Hwyla-1.8.26-B41_1.12.2
  [✔] IceAndFireRotN-1.9.1-1.2.1
  [✔] ImmersiveCombat-3-22-2024
  [✔] incontrol-1.12-3.9.18
  [✔] Inspirations-1.12.2-0.2.9
  [✔] interactions-1.9.2
  [✔] InventoryTweaks-1.63
  [✔] inworldcrafting-1.12.2-1.2.0-universal
  [✔] ironfurnaces-1.3.5
  [✔] itlt-1.12.x-1.0.4
  [✔] IvToolkit-1.3.3-1.12
  [✔] JSON-Paintings-v1.3.0-mc1.12.2
  [✔] justenoughdimensions-1.12.2-1.6.0-dev.20200416.184714
  [✔] JustEnoughEffects-1.0.3
  [✔] just-enough-harvestcraft-1.12.2-1.7.2
  [✔] JustEnoughIDs-1.0.4-SNAPSHOT-thin
  [✔] konkrete_forge_1.6.1_MC_1.12-1.12.2
  [✔] LegendaryTooltips-1.12.2-1.1.10
  [✔] lemonlib-1.12.2-1.3.0
  [✔] LetMeSleep-v1.2.3-1.12.2
  [✔] LibraryEx-1.12.2-1.2.2
  [✔] lifescroll-1.0
  [✔] living_enchantment-3.2.3
  [✔] llibrary-1.7.20-1.12.2
  [✔] LoadingProfiler-MC1.12-1.3
  [✔] LoadingScreens-1.12.2-0.3.1
  [✔] loadmyresources_forge_1.0.4_MC_1.12-1.12.2
  [✔] logimmune-0.1
  [✔] LootTableTweaker-1.12.2-1.1.14
  [✔] LootTweaker-0.3.1+MC1.12.2
  [✔] MagmaMonsters-0.3.0
  [✔] maleksinfinitygauntlet
  [✔] MaleksMultiblockMobs-1.7
  [✔] malisiscore-1.12.2-6.5.1
  [✔] malisisdoors-1.12.2-7.3.0
  [✔] Mantle-1.12-1.3.3.55
  [✔] Mapmaker's Gadgets-1.2_for_1.12.x
  [✔] materialchanger1.0.3-1.12.2
  [✔] Mclogs-forge-1.0.5-for-1.12.2
  [✔] MCMultiPart-2.5.3
  [✔] mcw-bridges-1.0.6b-mc1.12.2
  [✔] minerva-library-1.0.13
  [✔] MineTraps-1.12.2-(v.1.0.4)
  [✔] MoBends_1.12.2-1.2.1-19.12.21
  [✔] Modpack Configuration Checker-1.12.2-v1.9.5
  [✔] modtweaker-4.0.20.11
  [✔] moresoundconfig-1.0.4
  [✔] MoreSwordsLegacy-1.12.2-1.0.7
  [✔] mousetweaks-1.12.2-3.1.4
  [✔] mowziesmobs-1.5.8
  [✔] MTLib-3.0.7
  [✔] multiblocked-0.8.5
  [✔] multimob-1.0.5
  [✔] MultithreadedNoise-1.12.2-0.0.2
  [✔] musictriggers-1.12.2-6.3.1
  [✔] mysticallib-1.12.2-1.13.0
  [✔] NaturesCompass-1.12.2-1.8.5
  [✔] Neat 1.4-17
  [✔] netherchest-1.1.1
  [✔] NetherEx-1.12.2-2.2.5
  [✔] noarcher-1.0.0
  [✔] nolavabuild-1.12.2-1.0.0
  [✔] normalasm-5.19
  [✔] Nyx-1.6.1
  [✔] obfuscate-0.4.2-1.12.2
  [✔] opticheck-1.12.2-1.0.1
  [✔] OptiFine_1.12.2_HD_U_G6_pre1
  [✔] Ore Stone Variants-5.14
  [✔] OreLib-1.12.2-3.6.0.1
  [✔] OreStages-1.12.2-2.0.37
  [✔] outfox-0.1.5-mc1.12.2
  [✔] packupdater-0.1.2
  [✔] paintingselgui-PSG Revamed-1.12.2-1.1.0.1
  [✔] Pam's HarvestCraft 1.12.2zg
  [✔] particleculling-1.12.2-v1.4.1
  [✔] Patchouli-1.0-26
  [✔] Placebo-1.12.2-1.6.1
  [✔] pollutantpump-1.12.2-1.3.0
  [✔] PotionCore-1.9_for_1.12.2
  [✔] PowerDrop-MC1.12.2-1.1.3
  [✔] primallib-v1.1.60-mc1.12.2
  [✔] primitivemobs-1.2.3a
  [✔] ProportionalDestructionParticles-1.12.2-1.2.4
  [✔] Pyrotech Compat-1.0.3
  [✔] pyrotech-1.12.2-1.5.25
  [✔] QualityTools-1.0.7_for_1.12.2
  [✔] QuarkOddities-1.12.2
  [✔] QuarkRotN-r1.6-188
  [✔] randomenchants-0.1.5
  [✔] randompatches-1.12.2-1.22.1.10
  [✔] randomportals-1.12.2-1.8.2.4
  [✔] RandomThings-MC1.12.2-4.2.7.4
  [✔] rats-3.2.21-1.12.2
  [✔] ReAuth-1.12-Forge-4.0.7
  [✔] rebind-1.12.2-2.7.5-0
  [✔] RecipeStages-1.1.3.8
  [✔] RecurrentComplex-1.4.8.5
  [✔] Redstone++ ver1.3e
  [✔] RedstoneFlux-1.12-2.1.1.1-universal
  [✔] RedstoneMinusRedstone-0.3.1
  [✔] RenderLib-1.12.2-1.3.3
  [✔] Requious Frakto-0.12
  [✔] ResourceLoader-MC1.12.1-1.5.3
  [✔] ResourceReloader-1.0.2.5
  [✔] respawntimer-1.12.2-2.0.2.0
  [✔] RLFoliage-MC1.12-2.4.0
  [✔] RLMixins-1.3.2
  [✔] RLTweaker-1.12.2-0.5.12
  [✔] rockytweaks-1.12.2-0.6.1
  [✔] RoguelikeDungeons-1.12.2-1.8.0
  [✔] rotm-1.12.2-1.1.4
  [✔] RotN-Blocks-1.0.3
  [✔] RotN-Tweaker-0.0.1
  [✔] roughmobsrevamped-1.12.2-2.3.23
  [✔] rustic-1.1.7
  [✔] rusticbopwoods-1.0
  [✔] RusticCompat-1.3
  [✔] SaltLampsReforged-1.12.2-1.1.0
  [✘] sampler-1.84.jar (disabled)
  [✔] SBM-Dead-Mans-Satchel-1.12.2-1.0.0b20190226202928
  [✔] scalar-1.12.2-2.11.1
  [✔] ScalingHealth-1.12.2-1.3.42+147
  [✔] ScreenshotToClipboard-1.12.2-1.0.1
  [✔] SereneSeasons-1.12.2-1.2.18-universal
  [✔] SereneTweaks-1.0
  [✔] SetBonus-1.12.2.020
  [✔] ShadowMC-1.12-3.8.0
  [✔] shetiphiancore-1.12.0-3.5.9
  [✔] ShoulderSurfing-1.12.2-2.8.2
  [✔] SilentLib-1.12.2-3.0.14+168
  [✔] simple_paraglider-1.1.0
  [✔] simplecore-1.12.2-1.7.3.4
  [✔] SimpleLogic-Gates-0.5.6.1
  [✔] SimpleLogic-Wires-0.5.6.3
  [✔] simpleores-1.12.2-1.11.2.2
  [✔] simplyhotsprings-0.2.5
  [✔] SmoothFont-mc1.12.2-2.1.4
  [✔] SmoothWater-0.1.4
  [✔] SnowRealMagic-1.12.2-0.7.1
  [✔] solcarrot-1.12.2-1.8.4
  [✔] Sound-Physics-1.12.2-1.0.10-1
  [✔] soundreloader-1.2-1.12.2
  [✔] spartancompat-1.2.3
  [✔] spartanfire-0.08
  [✔] SpartanShields-1.12.2-1.5.5
  [✔] spartantwilight-1.12.2-1.2.0
  [✔] SpartanWeaponry-1.12.2-1.4.1
  [✔] specialai-1.1.0_for_mc1.12.2
  [✔] specialmobs-1.0.4_for_mc1.12.2
  [✔] spectral_edge-forge-1.6
  [✔] SplashAnimation-0.2.1
  [✔] StackUp-0.2.5
  [✔] StuffASockInIt-1.12.2-1.1.30
  [✔] stygian-1.0.4
  [✔] superflatcaves-1.3.1
  [✔] teamsmod-1.12.2-Rfinal-fixed
  [✔] tellme-1.12.2-0.7.0-dev.20200919.184303
  [✔] The Beneath-1.12.2-1.7.1
  [✔] The-Hordes-1.12.2-1.1.6b
  [✔] theimpossiblelibrary-1.12.2-0.3.0
  [✔] ThirstyBottles-1.12.2-2.0.1
  [✔] tnt_utilities-mc1.12-1.2.3
  [✔] Toast Control-1.12.2-1.8.1
  [✔] ToolBelt-1.12.2-1.9.14
  [✔] toolprogression-1.12.2-1.6.12
  [✔] ToroQuest-Revamped-3-25-2022-fix
  [✔] totemexpansion-1.2.2-1.12.2
  [✔] TP+-1.12.2-1.0.1.1
  [✔] TrashSlot_1.12.2-8.4.10
  [✔] Trident-1.0.5
  [✔] Triumph-1.12.2-3.19.2
  [✔] trumpetskeleton-1.12-1.0.2.1
  [✔] twilightforest-1.12.2-3.11.1021-universal
  [✔] UndergroundBiomesConstructs-1.12-1.3.14
  [✔] UniversalTweaks-1.12.2-1.9.0
  [✔] vanillaanvilrepair-1.1
  [✔] VerticallyStackedDimensions-1.12.2-0.1.9
  [✔] Vials-MC1.12-1.2.1.5
  [✔] VillageNames-1.12.2-4.4.7
  [✔] VillagerTrades-1.12-0.6.4
  [✔] wards-1.3.1
  [✔] weakerspiderwebs_1.12.2-2.0
  [✔] Well-Mod-v1.0.1-mc1.12.2
  [✔] world_generation_profiler-[1.8-1.12.2]-1.2.1.5
  [✔] worldprimer-1.12.2-0.6.0-dev.20200122.211517
  [✔] World-Stripper-1.6.0-1.12.2
  [✔] ZenFoundry-1.7.18
  [✔] zenrecipereloading-1.2.2
  [✔] zenutils-1.14.15
  [✔] zombie_players-1.12.1-1.2.7
  [✔] zombieawareness-1.12.1-1.11.16

### MMC Instance Notes

NA

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Can confirm this mod packed a fxxking outdated ASM itself

**Comment by Xplodin** [comment]
> Can confirm this mod packed a fxxking outdated ASM itself

Is there a mod or mods I can remove thatll make it work? Im guessing its one of the few mixin booter mods

**Comment by kappa-maintainer** [comment]
Try this Fugue build
https://github.com/CleanroomMC/Fugue/actions/runs/9906109791

**Comment by Xplodin** [comment]
> Try this Fugue build https://github.com/CleanroomMC/Fugue/actions/runs/9906109791

That seemed to fix the boot issue :) gonna test the Ears mod in-game and look for bugs (if any)

**Comment by Xplodin** [comment]
that fixed that issue but I have a few more. Ill open a new ticket as its a different issue
