### ISSUE TITLE
Unable to launch on MacOS

### ISSUE THREAD

**Issue by MCTian-mi** [CleanroomMC/Cleanroom#171]
### Your CleanroomMC Discord Username

Tian_mi

### Cleanroom Version

0.2.2-alpha #2446b52

### Java Version

Java 21

### Graphics Card Vendor

M2

### Bug Report

https://mclo.gs/9jTjDeo

### Mod List

None

### MMC Instance Notes

N/A

### Final Checklist

- [x] I have searched the issues and haven't found a similar issue.
- [x] I have read the known incompatibilities and this is not related to one of those.
- [ ] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [ ] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [ ] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by KorewaLidesu** [comment]
Fixed in https://github.com/CleanroomMC/CleanroomMMC/commit/4d9ad14912e7c4ffe54a62b7f9d94169984941b9
