### ISSUE TITLE
Cannot launch on my drive.

### ISSUE THREAD

**Issue by lava191810** [CleanroomMC/Cleanroom#172]
### Cleanroom Version

0.2.2-alpha

### Java Version

Java 21

### Graphics Card Vendor

Other (Please Specify)

### Bug Report

Minecraft log:
[latest.log](https://github.com/user-attachments/files/16170710/latest.log)
Launcher log:
[latestlog.txt](https://github.com/user-attachments/files/16170715/latestlog.txt)

### Mod List

No mods.

### MMC Instance Notes

N/A

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Latest log is too short for any launcher, are you sure that's all you got?

**Comment by lava191810** [comment]
I've tested it three times and the log output is the same each time, so here it is.

**Comment by kappa-maintainer** [comment]
PojavLauncher is not officially supported, please consult in their repository
