### ISSUE TITLE
Cannot launch modpack with RLMixins 

### ISSUE THREAD

**Issue by Xplodin** [CleanroomMC/Cleanroom#173]
### Your CleanroomMC Discord Username

autismo bean

### Cleanroom Version

0.2.2

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

https://mclo.gs/TpcEMak

### Mod List

Included in log

### MMC Instance Notes

N/A - there is no notes
The mod RLMixins fails ONLY with cleanroom and fugue + scalar due to it requiring fermiumbooter/asm
Not sure why cleanroom makes the mod want it, but normal forge instance does not require it

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by KorewaLidesu** [comment]
What do you mean about "requiring"?
Is it missing dependency errors, or that the game can't launch without suggested mods?

**Comment by Xplodin** [comment]
> What do you mean about "requiring"? Is it missing dependency errors, or that the game can't launch without suggested mods?
> 
> P/s: RLMixin is relied on FermiumBooter API, you can see [here](https://github.com/fonnymunkey/RLMixins/blob/main/src/main/java/rlmixins/RLMixinsPlugin.java#L216-L230)

on ROTN modpack, it doesnt need fermiumbooter or fermiumasm with forge. With cleanroom, itll crash saying it needs those mods

**Comment by KorewaLidesu** [comment]
Can you confirm if both mods file are identical same version?

**Comment by KorewaLidesu** [comment]
Can you check if both version you using are identical same?
As RLMixin start hard depend on FerrmiumBooter since 1.3.1

**Comment by Xplodin** [comment]
rlmixins is on 1.3.2 with a clean install of ROTN
without cleanroom, it launches normally and has normalasm.
With cleanroom, it crashes saying it needs fermiumbooter

**Comment by jchung01** [comment]
I would assume ROTN updated RLMixins from before it needed FermiumBooter, so they forgot to add FermiumBooter. The reason it launches fine on Forge is because the mixin loader used (included in MixinBooter) catches the error of RLMixins being unable to find FermiumBooter. 

Cleanroom loads coremods differently, so it probably doesn't catch the error, thus the hard crash. In both cases, though, this means RLMixins has never loaded correctly in the modpack since RLMixins was updated. You should **report to the modpack author** that they need FermiumBooter for RLMixins.

**Comment by Xplodin** [comment]
> I would assume ROTN updated RLMixins from before it needed FermiumBooter, so they forgot to add FermiumBooter. The reason it launches fine on Forge is because the mixin loader used (included in MixinBooter) catches the error of RLMixins being unable to find FermiumBooter.
> 
> Cleanroom loads coremods differently, so it probably doesn't catch the error, thus the hard crash. In both cases, though, this means RLMixins has never loaded correctly in the modpack since RLMixins was updated. You should **report to the modpack author** that they need FermiumBooter for RLMixins.

gotcha, that makes more sense. Strange they have the dependency wrong

**Comment by Xplodin** [comment]
Duplicate Mods:
	configanytime : C:\Users\somet\AppData\Roaming\PrismLauncher\instances\ROTN Cleanroom\.minecraft\mods\!configanytime-3.0.jar
	configanytime : C:\Users\somet\AppData\Roaming\PrismLauncher\instances\ROTN Cleanroom\libraries\cleanroom-0.2.2-alpha-universal.jar
	mixinbooter : C:\Users\somet\AppData\Roaming\PrismLauncher\instances\ROTN Cleanroom\.minecraft\minecraft.jar
	mixinbooter : C:\Users\somet\AppData\Roaming\PrismLauncher\instances\ROTN Cleanroom\libraries\cleanroom-0.2.2-alpha-universal.jar


not sure if configanytime is supposed to work with cleanroom or if its included in cleanroom already

**Comment by KorewaLidesu** [comment]
MixinBooter and ConfigAnytime are implemented in Cleanroom.

**Comment by Xplodin** [comment]
> MixinBooter and ConfigAnytime are implemented in Cleanroom.

is there a way to change configanytime version for cleanroom? It seems ROTN uses an outdated version of it. (1.0)

**Comment by valiray** [comment]
> > MixinBooter and ConfigAnytime are implemented in Cleanroom.
> 
> is there a way to change configanytime version for cleanroom? It seems ROTN uses an outdated version of it. (1.0) EDIT: nvm i downgraded the version number and custom built the jar

i see you already did it but for anyone else that needs it check [here for cleanroom with 1.0 config anytime](https://github.com/valiray/Cleanroom/actions)

**Comment by kappa-maintainer** [comment]
If any mod require configanytime version (currently 3.0) to be equals to 1.0, that their fault, not Cleanroom's
And iirc only an old version of UniversalTweaks did this

**Comment by valiray** [comment]
its more packs that you want to join servers on that haven't updated that is the issue

**Comment by kappa-maintainer** [comment]
Then just update it, it's not like you can't get a ConfigAnyTime 3.0 jar working on Forge

**Comment by valiray** [comment]
the issue is that the server and the client need the same version of ConfigAnyTime so both need to update which is not easily done a lot of the time

**Comment by kappa-maintainer** [comment]
You can custom cat version in latest Cleanroom action build

**Comment by Xplodin** [comment]
also another strange issue I encountered. Neat (health bar mod) does not show healthbars for cleanroom instance.
