### ISSUE TITLE
Crash when put on botania:flighttiara manually.

### ISSUE THREAD

**Issue by XZYawa** [CleanroomMC/Cleanroom#174]
### Cleanroom Version
0.2.2-alpha and #663 both
### Java Version
LibericaJDK21.0.3
### Graphics Card Vendor
NVidia
### Bug Report
If just right-click at toolbar,game will not crash,but then you will get two tiara.
The specific situation is shown in the following gif(direct link:https://github.com/user-attachments/assets/6a539572-3a46-41cf-9ee6-9d23ca29772c):
![output](https://github.com/user-attachments/assets/6a539572-3a46-41cf-9ee6-9d23ca29772c)
And game log here:
> [latest.log](https://github.com/user-attachments/files/16318554/latest.log)
### Mod List
Fugue-1.12.2-0.15.5
Baubles-1.12-1.5.2
Botania+r1.10-364.4
scalar-1.12.2-2.11.1
### Final Checklist
- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Add `vazkii.botania.common.core.helper.StringObfuscator` to javax list in fugue.cfg

**Comment by XZYawa** [comment]
> Add `vazkii.botania.common.core.helper.StringObfuscator` to javax list in fugue.cfg
Thanks!
