### ISSUE TITLE
Elytra given to armor does not work perfectly.

### ISSUE THREAD

**Issue by erialsan** [CleanroomMC/Cleanroom#175]
### Your CleanroomMC Discord Username

erialsan

### Cleanroom Version

0.2.2-alpha build.22.run.662

### Java Version

Java 22

### Graphics Card Vendor

Intel iGPU

### Bug Report

https://mclo.gs/hzpL2Fu

### Mod List

Colytra（https://www.curseforge.com/minecraft/mc-mods/colytra）
Fugue
Scalar2.11
The bottom two results are the same with or without.

### MMC Instance Notes

Use MMC instance

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by erialsan** [comment]
> ### Your CleanroomMC Discord Username
> erialsan
> 
> ### Cleanroom Version
> 0.2.2-alpha build.22.run.662
> 
> ### Java Version
> Java 22
> 
> ### Graphics Card Vendor
> Intel iGPU
> 
> ### Bug Report
> https://mclo.gs/hzpL2Fu
> 
> ### Mod List
> Colytra[https://www.curseforge.com/minecraft/mc-mods/colytra](https://www.curseforge.com/minecraft/mc-mods/colytra )Fugue Scalar2.11 The bottom two results are the same with or without.
> 
> ### MMC Instance Notes
> Use MMC instance
> 
> ### Final Checklist
> * [x]  I have searched the issues and haven't found a similar issue.
> * [x]  I have read the known incompatibilities and this is not related to one of those.
> * [x]  I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
> * [x]  I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
> * [x]  I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by erialsan** [comment]
The link is not working.
https://www.curseforge.com/minecraft/mc-mods/colytra

**Comment by erialsan** [comment]
Forge results: The elytra attached to the back of the diamond armor behaved like a normal elytra, gliding with two space keys.
Cleanroom results: The elytra attached to the back of the diamond armor did not open after two spacebar executions in mid-air, and the player landed in the river.
The information in the part of the log that is not available is correct.

**Comment by kappa-maintainer** [comment]
Fixed in latest action build of Fugue. You need to enable the patch in fugue.cfg manually

**Comment by erialsan** [comment]
Now the same mod, Elytra given in Baubles is not working. This could be due to the fact that I am using a fork called BaublesEX, so I will investigate with the minimum configuration
