### ISSUE TITLE
Better quest font render bug

### ISSUE THREAD

**Issue by kaspertfg** [CleanroomMC/Cleanroom#177]
### Your CleanroomMC Discord Username

kasper_tfg

### Cleanroom Version

0.2.2-alpha

### Java Version

Java 21

### Graphics Card Vendor

AMD/ATI

### Bug Report

When clicking on the Electric blast furnace quest in chapter two in Nomifactory CEu it causes a hard crash.

crash log: https://mclo.gs/4fWaUtX

As discussed on discord appears as the crash is from this line:
https://github.com/CleanroomMC/Cleanroom/blob/main/patches/minecraft/net/minecraft/client/gui/FontRenderer.java.patch#L281

### Mod List

Standard Nomifactory CEu latest 1.7.5c Alpha realease

### MMC Instance Notes

N/A

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Try latest build from action
