### ISSUE TITLE
与B3M不兼容

### ISSUE THREAD

**Issue by raitpor** [CleanroomMC/Cleanroom#178]
### Cleanroom Version

0.2.2-alpha

### Java Version

Java 21

### Graphics Card Vendor

Intel iGPU

### Bug Report

https://mclo.gs/4m36WCE

### Mod List

[b3m ](https://www.curseforge.com/minecraft/mc-mods/time-speed-mod)

### MMC Instance Notes

无

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
将 `sedridor.B3M.ClientProxy` 添加到fugue.cfg的reflection列表中
