### ISSUE TITLE
Client crash on ARM Macs due to trying to load x86_64 native lib for Narrator during launch

### ISSUE THREAD

**Issue by eternitymoe** [CleanroomMC/Cleanroom#182]
### Your CleanroomMC Discord Username

bakamoe

### Cleanroom Version

0.2.2-alpha

### Java Version

Java 21

### Graphics Card Vendor

Other (Please Specify)

### Bug Report

The Cleanroom client will crash due to it's trying to load a x86_64 native lib for Mojang's Narrator on ARM Mac
The Crash happens while FML finished mod loading (just before game's Main menu appears)
I tried both build on Action (0.2.2-alpha+build.26.run.669) and Release, they crashed for same reason as quoted from debug.log below:
> [09:18:05] [Client thread/INFO] [STDERR]: [ca.weblite.objc.RuntimeUtils:<clinit>:67]: java.lang.UnsatisfiedLinkError: /private/var/folders/yt/5y9w91kd1mvc7885bm7cvs080000gn/T/libjcocoa16911818140233790691.dylib: dlopen(/private/var/folders/yt/5y9w91kd1mvc7885bm7cvs080000gn/T/libjcocoa16911818140233790691.dylib, 0x0001): tried: '/private/var/folders/yt/5y9w91kd1mvc7885bm7cvs080000gn/T/libjcocoa16911818140233790691.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/yt/5y9w91kd1mvc7885bm7cvs080000gn/T/libjcocoa16911818140233790691.dylib' (no such file), '/private/var/folders/yt/5y9w91kd1mvc7885bm7cvs080000gn/T/libjcocoa16911818140233790691.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))

Below is the full logs & crash report files:
[latest.log](https://github.com/user-attachments/files/16511271/latest.log)
[debug.log](https://github.com/user-attachments/files/16511272/debug.log)
[crash-2024-08-06_09.50.05-client.txt](https://github.com/user-attachments/files/16511240/crash-2024-08-06_09.50.05-client.txt)

System info:
> MacBook Pro 13-inch, M2, 2022
macOS Version 14.5 (Build 23F79) arm64
GPU Vendor 'Apple' Version: '2.1 Metal - 88.1' Renderer: 'Apple M2'

Java version:
> openjdk version "21.0.4" 2024-07-16
OpenJDK Runtime Environment Homebrew (build 21.0.4)
OpenJDK 64-Bit Server VM Homebrew (build 21.0.4, mixed mode, sharing)

### Mod List

	| State  | ID            | Version      | Source                    | Signature |
	|:------ |:------------- |:------------ |:------------------------- |:--------- |
	| LCHIJA | minecraft     | 1.12.2       | minecraft.jar             | None      |
	| LCHIJA | mcp           | 9.42         | minecraft.jar             | None      |
	| LCHIJA | configanytime | 3.0          | cleanroom-0.2.2-alpha.jar | None      |
	| LCHIJA | cleanroom     | 0.2.2-alpha  | cleanroom-0.2.2-alpha.jar | None      |
	| LCHIJA | FML           | 8.0.99.99    | cleanroom-0.2.2-alpha.jar | None      |
	| LCHIJA | forge         | 14.23.5.2860 | cleanroom-0.2.2-alpha.jar | None      |
	| LCHIJA | mixinbooter   | 10.0         | cleanroom-0.2.2-alpha.jar | None      |

### MMC Instance Notes

(none)

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by KorewaLidesu** [comment]
Duplicate https://github.com/CleanroomMC/Cleanroom/issues/171
