### ISSUE TITLE
Cleanroom crashed with Dungeons2!(Caused by: java.lang.ExceptionInInitializerError/Caused by: java.lang.IllegalArgumentException: Path component should be '/')

### ISSUE THREAD

**Issue by lqr2007** [CleanroomMC/Cleanroom#184]
### Cleanroom Version

cleanroom-0.2.2-alpha+build.26.run.669

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

https://mclo.gs/t2Ddx6C
[latest.log](https://github.com/user-attachments/files/16568868/latest.log)
And,could I use Chinese?My English isn't good.

### Mod List

Fugue 0.15.9
Dungeons2! 1.7.5
GottschCore 1.15.1

### MMC Instance Notes

This instance is built using Github Action.
Using installer artifact from commit: https://github.com/CleanroomMC/Cleanroom/commit/0ac9e4b910f0163740ef8162a3c75b1e5d6aa4bf
Action URL: https://github.com/CleanroomMC/Cleanroom/actions/runs/10196576930

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Try to add `com.someguyssoftware.dungeonsengine.config.DungeonConfigLoader` to getCodeSource() list in fugue.cfg

**Comment by lqr2007** [comment]
OK, I will try it tomorrowm.

**Comment by lqr2007** [comment]
I'm sorry, but it didn't work.The crash report have no changes occurred.

**Comment by lqr2007** [comment]
And I found that `com.someguyssoftware.dungeonsengine.config.DungeonConfigLoader` was already on the list.
![image](https://github.com/user-attachments/assets/d394cf40-520f-499c-9910-47b34a9eb563)

**Comment by lqr2007** [comment]
It didn't work either.

**Comment by kappa-maintainer** [comment]
Use 2.0.0 + remove that line from config
I don't remember why it is there
