### ISSUE TITLE
SpongeForge crashing

### ISSUE THREAD

**Issue by gravit0** [CleanroomMC/Cleanroom#188]
### Your CleanroomMC Discord Username

Gravita

### Cleanroom Version

0.2.2-alpha

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

https://mclo.gs/NPIS5lB

### Mod List

spongeforge-1.12.2-2838-7.4.8-RC4142.jar
scalar-1.12.2-2.11.1.jar
+Fugue-1.12.2-0.15.9.jar

### MMC Instance Notes

-

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Duplicated with #30
