### ISSUE TITLE
crashed with dragoncore

### ISSUE THREAD

**Issue by wangyu2333333** [CleanroomMC/Cleanroom#190]
### Cleanroom Version

0.2.3

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

crashed with dragoncore
It's a mod for RPG server
[latest (1).log](https://github.com/user-attachments/files/16733289/latest.1.log)
[[Mod]DragonCore-2.6.2.9.jar.zip](https://github.com/user-attachments/files/16733272/Mod.DragonCore-2.6.2.9.jar.zip)

### Mod List

fugue scalar dragoncore

### MMC Instance Notes

none

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Add `eos.moe.dragoncore.tweaker.ForgePlugin` to getCodeSource list in fugue.cfg

**Comment by mczph** [comment]
@kappa-maintainer 
After modifying the fugue configuration, it can be loaded normally, but it will crash on 6/7
https://mclo.gs/lQqsFNN

**Comment by kappa-maintainer** [comment]
Add `eos.moe.dragoncore.za` to Field.set() list

**Comment by mczph** [comment]
Fine now
