### ISSUE TITLE
Conflict with the concept of 'Ka Blades'

### ISSUE THREAD

**Issue by DALENER** [CleanroomMC/Cleanroom#194]
### Cleanroom Version

0.2.2-alpha

### Java Version

Java 21

### Graphics Card Vendor

Intel iGPU

### Bug Report

[latest.log](https://github.com/user-attachments/files/16784094/latest.log)
[debug.log](https://github.com/user-attachments/files/16784095/debug.log)
[2024-08-28-7.log.gz](https://github.com/user-attachments/files/16784099/2024-08-28-7.log.gz)

### Mod List

[斩无不断KaBlade](https://github.com/WJXhhh/KaBlade)

### MMC Instance Notes

none

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [x] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by Ecdcaeb** [comment]
the [latest.log](https://github.com/user-attachments/files/16784094/latest.log)  [21:05:37] [Client thread/INFO] [FML]: The game window is being closed by the player, exiting.

please provide valid logs. A real crash, not a manual shutdown.

**Comment by DALENER** [comment]
> [latest.log](https://github.com/user-attachments/files/16784094/latest.log) [21：05：37] [客户端线程/信息] [FML]：玩家正在关闭游戏窗口，正在退出。
> 
> 请提供有效的日志。真正的崩溃，而不是手动关机。

In fact, the game crashed before the window appeared, and I did not manually terminate the process

**Comment by Ecdcaeb** [comment]
try Add `com.wjx.kablade.mixin.KabladeMixinTweak` to `getCodeSource` list in `fugue.cfg`

**Comment by DALENER** [comment]
> 真正的崩溃[2024-08-28-7.log.gz](https://github.com/user-attachments/files/16784099/2024-08-28-7.log.gz)
> 
> 尝试 Add to list in`com.wjx.kablade.mixin.KabladeMixinTweak``getCodeSource``fugue.cfg`
The problem has been resolved，thank you for your help

**Comment by DALENER** [comment]
> Real crash https://mclo.gs/y48DNZB try Add to list in `com.wjx.kablade.mixin.KabladeMixinTweak``getCodeSource``fugue.cfg`


The problem has been resolved，thank you for your help
