### ISSUE TITLE
Adding the ItemLocks mod cannot start the game

### ISSUE THREAD

**Issue by Hlwyefeng** [CleanroomMC/Cleanroom#195]
### Your CleanroomMC Discord Username

hlw_yefeng

### Cleanroom Version

cleanroom-0.2.3-alpha

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

https://mclo.gs/ekZuGm2
There is currently no alternative found for this mod, and I hope it can be fixed. Thank you very much

### Mod List

ItemLocks-1.0.jar
+Fugue-1.12.2-0.16.3.jar
scalar-1.12.2-2.11.1.jar

### MMC Instance Notes

no

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by Hlwyefeng** [comment]
https://www.curseforge.com/minecraft/mc-mods/itemlocks

**Comment by Rongmario** [comment]
Add `com.kirdow.itemlocks.util.reflect.ReflectClass` to `fugue.cfg`'s `Reflection Patch Target List`

**Comment by Rongmario** [comment]
Assumed fixed.
