### ISSUE TITLE
Fluidlogged API and Aqua Acrobatics incompatible

### ISSUE THREAD

**Issue by dimpunx** [CleanroomMC/Cleanroom#197]
### Cleanroom Version

0.2.3

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

These mods just doesn't work properly with cleanroom mod

### Mod List

Aqua Acrobatics
Fluidlogged API

### MMC Instance Notes

-

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
log?

**Comment by dimpunx** [comment]
[Uploading debug.log…]()



> log?

**Comment by dimpunx** [comment]
> log?

Which one? Sorry, I'm a newbie

**Comment by dimpunx** [comment]
[debug.log](https://github.com/user-attachments/files/16828922/debug.log)
[latest.log](https://github.com/user-attachments/files/16828923/latest.log)

**Comment by dimpunx** [comment]
> > > log?
> > 
> > 
> > [debug.log](https://github.com/user-attachments/files/16828922/debug.log) [latest.log](https://github.com/user-attachments/files/16828923/latest.log)
> 
> please upload on https://mclo.gs, it can help us locate problem :)

https://mclo.gs/b6ycFWn
https://mclo.gs/dt4Q9ID

**Comment by dimpunx** [comment]
Just discovered that Galacticraft in combination with CleanroomMC messes up Aqua Acrobatics movement, and Fluidlogged API messes up when Vintagium is installed. Yeah...

**Comment by kappa-maintainer** [comment]
Sounds like ASM problem
The issue could be reproduced by just AA + GC, right

**Comment by dimpunx** [comment]
> Sounds like ASM problem The issue could be reproduced by just AA + GC, right

Issue with Galacticraft was fixed by adding this Player-API in modpack https://github.com/GTNewHorizons/Player-API/releases/tag/1.5.0 
Now it works properly.
