### ISSUE TITLE
FML freezes after removing mod while loading world

### ISSUE THREAD

**Issue by G1ll0u** [CleanroomMC/Cleanroom#199]
### Cleanroom Version

0.2.3a

### Java Version
Java 21 (latest temurin jre on linux)

### Bug Report

Hello everybody,

I have a ubuntu server hosted in the cloud with my good old world using Millenaire but millenaire is a shitty closed-source mod that corrupts itself and devs don't want to work on it anymore, preferring latest versions of MC. 

So when my Millenaire village get corrupted I... :
1. remove Millenaire entirely
2. start the server without it
3. do /fml confirm, the server loads up 
4. load all affected chunks (I just tp to my village and explore)
5. close the server 
6. re-add the mod 
7. restart the server
8. start my villages from scratch.

But when I do it since I use Cleanroom, everything loads until the above step 3 :
![image](https://github.com/user-attachments/assets/edbc857b-c4da-498a-9929-16bdb231b10d)

- It just stucks to preparing level "world" and doesn't ask me confirmation.
- I tried to type /fml confirm + enter and nothing happens.
- I did wait 10min to see, nothing happens
- htop shows no significant CPU activity from java process

I did it a lot of times before and it always worked... So I think it is caused by my recent migration from forge 2860 to Cleanroom.
Here's my debug log (latest) :
https://mclo.gs/F8URxO5

Oh, and I don't know how to use "test builds" from actions tab

PS : 
- I didn't test in client-side (copying server map to single player and test in client-only)
- I didn't try with forge 2860
- Isn't there a way to enable "verbose" mode ?
- I don't see notes in your MMC instance but I used the latest MMC release from your GitHub releases
- Same problem if I remove other mod (I tried to remove OTG because my world doesn't use it and the problem is the same)
- Tested on client :
I copied my whole world to my mc client, loaded it without OTG and my world **loaded up successfully**, I've been able to remove my mod and import my world back to my server BUT it does the exact same problem.

So the problem seems to appear only on server-side...

Have an excellent day.

### Mod List

Guys please help me how to export modlist, in client I do F3+C and it makes a comfy crash report but I don't know how to do it server-side.
For the moment, here's a sort of list (I'm really sorry) :
<details><summary>full mod list</summary>

14.07.2024  00:19           130’772 !Red-Core-MC-1.7-1.12-0.5.1.jar
14.07.2024  00:19             5’201 !configanytime-3.0.jar
13.07.2024  19:20         1’799’352 !mixinbooter-9.1.jar
27.08.2024  05:53           167’694 +Fugue-1.12.2-0.16.3.jar
31.08.2024  05:36    <DIR>          .index
02.09.2024  17:21    <DIR>          1.12.2
14.07.2024  01:51         8’690’872 A_Little_Extra_Tiles-1.1.0-pre029.jar
14.07.2024  01:51         4’388’438 Age-of-Weapons-1.12.2-(v.0.13.6).jar
14.07.2024  00:17            33’683 AppleSkin-mc1.12-1.0.14.jar
14.07.2024  01:51           108’306 AutoRegLib-1.3-32.jar
14.07.2024  01:51            18’879 BackTools-1.12.2-7.0.1.jar
14.07.2024  01:51            62’668 BetterAdvancements-1.12.2-0.1.0.77.jar
14.07.2024  01:40            98’955 BetterCombat-1.12.2-1.5.6.jar
14.07.2024  01:36           943’468 BetterThirdPerson-Forge-1.12.2-1.9.0.jar
14.07.2024  01:36         5’185’177 BiblioCraft[v2.4.6][MC1.12.2].jar
14.07.2024  00:17         4’746’208 BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar
14.07.2024  01:51            94’972 Chameleon-1.12.2-4.1.3.jar.disabled
14.07.2024  01:51         2’383’353 Charm-1.12.2-1.4.1.jar
14.07.2024  01:51           704’330 CodeChickenLib-1.12.2-3.2.3.358-universal.jar
14.07.2024  01:36            34’383 Controlling-3.0.12.4.jar
14.07.2024  01:36         1’321’137 CreativeCore_v1.10.71_mc1.12.2.jar
14.07.2024  01:36         9’911’871 CustomNPCs_1.12.2-(05Jul20).jar
14.07.2024  01:36        16’976’718 Decocraft-2.6.3.7_1.12.2.jar
14.07.2024  01:36           801’797 DoggyTalents-1.12.2-1.15.1.6.jar
14.07.2024  01:36        25’544’042 DrZharks-MoCreatures-Extended-12.4.3.jar
14.07.2024  01:36        15’778’870 DynamicSurroundings-1.12.2-3.6.3.jar
14.07.2024  23:09         2’349’948 Exotic Birds 1.12.2-3.2.0.jar
14.07.2024  01:36            43’764 FTBBackups-1.1.0.1.jar
14.07.2024  01:36           934’370 FTBLib-5.4.7.2.jar
14.07.2024  01:36           425’832 FTBUtilities-5.4.1.131.jar
14.07.2024  01:36           168’418 FallingTree-1.12.2-2.4.0.jar
01.09.2024  21:41           200’152 Fixeroo-2.2-hotfix.1.jar
01.09.2024  21:43           368’548 Fluidlogged-API-v2.2.7-mc1.12.2.jar
14.07.2024  00:58         7’056’006 Forgelin-Continuous-2.0.0.1.jar
14.07.2024  01:36        14’321’557 Future-MC-0.2.19.jar
14.07.2024  00:54           687’649 HadEnoughItems_1.12.2-4.25.5.jar
14.07.2024  00:49           453’778 Hwyla-1.8.26-B41_1.12.2.jar
14.07.2024  01:36           286’144 InventoryTweaks-1.64+dev.151.jar
14.07.2024  01:36            52’615 ItemPhysic_Full_1.4.37_mc1.12.2.jar
14.07.2024  00:21            26’235 Ksyxis-1.3.2.jar
14.07.2024  00:49         1’994’663 LittleTiles_v1.5.87_mc1.12.2.jar
14.07.2024  01:36           128’880 Millenaire Extended-1.12.2-1.3.3.jar
14.07.2024  01:36           770’595 MoBends_1.12.2-1.2.1-19.12.21.jar
14.07.2024  21:24            21’508 Morpheus-1.12.2-3.5.106.jar
14.07.2024  01:36            80’528 MouseTweaks-2.10.1-mc1.12.2.jar
14.07.2024  01:43            11’368 MultithreadedNoise-1.12.2-0.0.2.jar
02.09.2024  16:48    <DIR>          OpenTerrainGenerator
14.07.2024  01:54           341’728 OreLib-1.12.2-3.6.0.1.jar
14.07.2024  01:36           169’749 PTRLib-1.0.5.jar
14.07.2024  02:19            77’207 Placebo-1.12.2-1.6.1.jar
14.07.2024  00:52         3’271’499 PolyPatcher-1.12.2-forge-1.9.1.jar.disabled
14.07.2024  01:51         3’877’577 Quark-r1.6-179.jar
14.07.2024  01:51         2’368’416 Sledgehammer-1.12.2-2.0.26.jar
02.09.2024  15:40            20’713 StuffASockInIt-1.12.2-1.1.32.jar
14.07.2024  01:51         1’205’052 Stupid Things-1.12.2-1.1.6.jar
14.07.2024  01:51           397’467 TravelersBackpack-1.12.2-1.0.35.jar
14.07.2024  01:51            19’899 Unifine-1.12.2-0.1.0.jar
14.07.2024  00:52         1’434’228 UniversalTweaks-1.12.2-1.12.0.jar
14.07.2024  00:49            94’115 Wawla-1.12.2-2.6.275.jar
14.07.2024  01:51           862’363 WorldEdit-CUI-FE3-1.12.2-3.0.9.jar
01.09.2024  18:04         7’270’292 [[valkyrien-skies-1.1.7-all]].jar
14.07.2024  00:19         1’201’209 `FermiumBooter-1.1.0.jar.disabled
14.07.2024  01:51        74’746’197 ancientwarfare-1.12.2-2.9.6..jar
14.07.2024  01:36         8’211’365 betteranimalsplus-1.12.2-9.0.1.jar
14.07.2024  01:36            37’657 betterbiomeblend-1.12.2-1.1.7-forge.jar
14.07.2024  01:36           105’052 blockcraftery-1.12.2-1.3.1.jar
13.07.2024  19:19         1’647’684 censoredasm5.20.jar
14.07.2024  02:12         2’838’523 cfm-legacy-1.12.2-6.5.0.jar
14.07.2024  01:36           737’407 chiselsandbits-14.33.jar
14.07.2024  01:36           167’301 comforts-1.12.2-1.4.1.3.jar
14.07.2024  01:36            67’966 corpse-1.12.2-1.0.8.jar
14.07.2024  00:17            41’478 entityculling-1.12.2-1.6.3.jar
14.07.2024  01:36           439’274 grappling_hook_mod-1.12.2-v13.jar
14.07.2024  01:51           581’963 iChunUtil-1.12.2-7.2.2.jar
14.07.2024  01:36            14’649 itlt-1.12.x-1.0.4.jar
14.07.2024  01:36         6’536’118 journeymap-1.12.2-5.7.1p2.jar
14.07.2024  01:36         1’412’141 kirosblocks-1.2.2.jar
14.07.2024  02:05           884’550 llibrary-1.7.20-1.12.2.jar
14.07.2024  01:36           373’298 mcw-bridges-1.0.6b-mc1.12.2.jar
14.07.2024  01:36           552’150 mcw-doors-1.0.3-mc1.12.2.jar
14.07.2024  01:36           165’452 mcw-fences-1.0.0-mc1.12.2.jar
14.07.2024  01:36           593’528 mcw-furniture-1.0.1-mc1.12.2beta.jar
14.07.2024  01:36           350’111 mcw-lights-1.0.6-mc1.12.2forge.jar
14.07.2024  01:36           141’397 mcw-paintings-1.0.5-1.12.2forge.jar
14.07.2024  01:36           154’179 mcw-paths-1.0.2forge-mc1.12.2.jar
14.07.2024  01:36           433’054 mcw-roofs-1.0.2-mc1.12.2.jar
14.07.2024  01:36           233’740 mcw-trapdoors-1.0.3-mc1.12.2.jar
14.07.2024  01:36           124’758 mcw-windows-1.0.0-mc1.12.2.jar
31.08.2024  05:36    <DIR>          memory_repo
31.08.2024  05:36    <DIR>          millenaire
14.07.2024  01:36        13’032’776 millenaire-8.1.2.jar
31.08.2024  05:36    <DIR>          millenaire-custom
08.07.2024  23:42           706’027 morepaintings-paintings-1.12.2-5.0.1.2.jar
14.07.2024  02:04         5’187’073 mowziesmobs_1.12.2_1.5.8.jar
14.07.2024  01:36           426’226 mysticallib-1.12.2-1.13.0.jar
02.09.2024  17:29             3’319 output.txt
24.07.2024  23:55           529’153 overworld_mirror-1.12.2-1.2.1.10.jar
14.07.2024  00:52             8’387 performant-1.11.jar
14.07.2024  01:51           774’236 r2s-Core-1.12.2-1.7.0.RELEASE.jar.disabled
14.07.2024  01:51         1’315’365 r2s-Radio-1.12.2-1.4.2.RELEASE.jar.disabled
14.07.2024  21:24           293’231 randompatches-1.12.2-1.22.1.10.jar
14.07.2024  21:24           288’481 randomtweaks-1.12.2-2.8.3.1.jar
14.07.2024  01:51           335’854 roost-1.12.2-2.0.10.jar
14.07.2024  21:24           124’416 rpintegration-1.12.2-1.5.1.0.jar
08.04.2024  14:11        25’467’221 scalar-1.12.2-2.11.1.jar
02.09.2024  16:09         2’228’992 spark-forge1122.jar
14.07.2024  01:51           282’258 tellme-1.12.2-0.7.0-dev.20200919.184303.jar
14.07.2024  01:51            87’400 tumbleweed-1.12-0.4.7.jar
24.07.2024  23:55           346’205 u_team_core-forge-1.12.2-2.2.5.305.jar
14.07.2024  01:51         1’479’535 worldedit-forge-mc1.12.2-6.1.10-dist.jar
14.07.2024  01:51           289’040 worldutils-1.12.2-0.5.0-dev.20210322.174648.jar
</details>
### MMC Instance Notes
Didn't find any but using your latest MMC release 

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [ ] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [ ] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by Rongmario** [comment]
Thank you for the report, can you try removing Ksyxis? Remember, make sure you have an original copy of the world copied somewhere else so it isn't tampered.

**Comment by G1ll0u** [comment]
I did it. Exact same behavior.
I didn't find any solution for the moment,

**Comment by G1ll0u** [comment]
Isolated : [StuffASockInIt](https://www.curseforge.com/minecraft/mc-mods/stuff-a-sock-in-it) is the problem

**Comment by G1ll0u** [comment]
This mod
