### ISSUE TITLE
NomiLabs configuration not loading correctly

### ISSUE THREAD

**Issue by lynxx131** [CleanroomMC/Cleanroom#200]
### Cleanroom Version

universal-0.2.3-alpha+build.5.run.696

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

For some reason the NomiLabs mod included with Nomifactory CEu does not load it's config correctly under Cleanroom, the pack ships a config file called `nomilabs.cfg` but when launching under Cleanroom this file is ignored and a new file called `nomilabs` is created in the config directly with what appears to be all default values.

This issue does not occur under vanilla Forge.

### Mod List

All mods included in Nomifactory 1.7a Curseforge pack + Fugue 0.16.3 and Scalar 2.11.

### MMC Instance Notes

This instance is built using Github Action.

Using installer artifact from commit: b132d863be3ca18b8f57d432e65402ef54491572
Action URL: https://github.com/CleanroomMC/Cleanroom/actions/runs/10658856743

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Try run.698 (when the build is out)

**Comment by lynxx131** [comment]
Upgraded to build 699 and this issue appears to have gone away and the config directory looks correct.

Thanks
