### ISSUE TITLE
Polyfrost's mods couldn't load OneConfig

### ISSUE THREAD

**Issue by XZYawa** [CleanroomMC/Cleanroom#204]
### Your CleanroomMC Discord Username

xzy9262

### Cleanroom Version

0.2.3 and #697

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

> [latest.log](https://github.com/user-attachments/files/16957856/latest.log)

It will always show "failed to download",even though I have already placed a complete OneConfig folder in .minecraft/

### Mod List

Aoneconfigbootstrap-1.12.2-forge-1.0.3(or any other mods by Polyfrost)
+Fugue-1.12.2-0.16.3
scalar-1.12.2-2.11.1

### MMC Instance Notes

(话说这一块到底是填啥的)

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by HowardZHY** [comment]
They don't support Java 9+

**Comment by XZYawa** [comment]
> They and their libs used don't support Java 9+ at all

Right?
Okay......

**Comment by kappa-maintainer** [comment]
Patchable, open this for now

**Comment by kappa-maintainer** [comment]
Try latest Fugue build in config

**Comment by mywar5** [comment]
> > They and their libs used don't support Java 9+ at all
> 
> Right? Okay......

![屏幕截图 2024-09-13 221613](https://github.com/user-attachments/assets/8be46d26-3634-4874-8dba-1a61d5ab9b09)

**Comment by mywar5** [comment]
> ### Your CleanroomMC Discord Username
> xzy9262
> 
> ### Cleanroom Version
> 0.2.3 and #697
> 
> ### Java Version
> Java 21
> 
> ### Graphics Card Vendor
> NVidia
> 
> ### Bug Report
> > [latest.log](https://github.com/user-attachments/files/16957856/latest.log)
> 
> It will always show "failed to download",even though I have already placed a complete OneConfig folder in .minecraft/
> 
> ### Mod List
> Aoneconfigbootstrap-1.12.2-forge-1.0.3(or any other mods by Polyfrost) +Fugue-1.12.2-0.16.3 scalar-1.12.2-2.11.1
> 
> ### MMC Instance Notes
> (话说这一块到底是填啥的)
> 
> ### Final Checklist
> * [x]  I have searched the issues and haven't found a similar issue.
> * [x]  I have read the known incompatibilities and this is not related to one of those.
> * [x]  I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
> * [x]  I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
> * [x]  I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

![屏幕截图 2024-09-13 221613](https://github.com/user-attachments/assets/5fb8b7fb-d433-4578-8ffc-467eeafd1fb9)
it will be added in oneconfig v1

**Comment by kappa-maintainer** [comment]
The patch should still work as long as those method names remain untouched, let me know if anything gone wrong after author patch it
