### ISSUE TITLE
Crash with BDLib

### ISSUE THREAD

**Issue by Bombliiv2** [CleanroomMC/Cleanroom#207]
### Your CleanroomMC Discord Username

bomblii

### Cleanroom Version

14.23.5.2860

### Java Version

Java 21

### Graphics Card Vendor

AMD iGPU

### Bug Report

Game crashes while loading BDLib
[debug.log](https://github.com/user-attachments/files/17049646/debug.log)
[latest.log](https://github.com/user-attachments/files/17049647/latest.log)

### Mod List

BDLib
Fugue
Scalar

### MMC Instance Notes

no notes

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by Wizzerinus** [comment]
you have installed the wrong version of scalar. 3.4.2 installed, need 2.x

**Comment by Bombliiv2** [comment]
oh
