### ISSUE TITLE
Borderless fullscreen mods don't work

### ISSUE THREAD

**Issue by Radk6** [CleanroomMC/Cleanroom#210]
### Your CleanroomMC Discord Username

radplay

### Cleanroom Version

0.2.3-alpha+build.15.run.709

### Java Version

Java 21

### Graphics Card Vendor

AMD/ATI

### Bug Report

Log: https://mclo.gs/iGiou51

This was already mentioned in the discord a while back but I also wanted to report this here for visibility.

### Mod List

- Fugue [0.16.3]
- Fullscreen Windowed [1.6.0]
- Scalar [2.11.1-2]

### MMC Instance Notes

This instance is built using Github Action.
Using installer artifact from commit: a1785a9b5e053bed234cdad81ce202ac9606ee7c
Action URL: https://github.com/CleanroomMC/Cleanroom/actions/runs/11014986399

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by Vrath** [comment]
Yeah, it seems just fulscreen doesn't seem to work.

**Comment by Rongmario** [comment]
Borderless Fullscreen is now integrated into one of the config options.

**Comment by xBioDreadx** [comment]
Thank you for that feature! It was really hard to find that config value, i would like to help people that will be looking for it like i did:
To make Fullscreen Borderless:
- Open config file in: \minecraft\config\forge_early.cfg
- Change value WINDOW_BORDERLESS_REPLACES_FULLSCREEN=false  --> true
- In game just press F11.
