### ISSUE TITLE
Crash with chatimage when selecting a local image

### ISSUE THREAD

**Issue by XZYawa** [CleanroomMC/Cleanroom#212]
### Your CleanroomMC Discord Username

xzy9262

### Cleanroom Version

#710

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

> [latest.log](https://github.com/user-attachments/files/17190973/latest.log)
> [crash-2024-09-30_21.47.35-client.txt](https://github.com/user-attachments/files/17190991/crash-2024-09-30_21.47.35-client.txt)

### Mod List

chatimage-1.6
+Fugue-1.12.2-0.16.3
scalar-1.12.2-2.11.1

### MMC Instance Notes

\

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by Rongmario** [comment]
Should be fixed with #216.
