### ISSUE TITLE
Thread#stop throws UnsupportedOperationException - evident in Better Records when taking out a record

### ISSUE THREAD

**Issue by XZYawa** [CleanroomMC/Cleanroom#213]
### Your CleanroomMC Discord Username

xzy9262

### Cleanroom Version

#710

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

logs here:

> [latest.log](https://github.com/user-attachments/files/17191415/latest.log)

The specific situation is shown in the following gif(direct link:https://github.com/user-attachments/assets/29068f6e-8340-4dd7-9851-ecc6ef16831d):
![output](https://github.com/user-attachments/assets/29068f6e-8340-4dd7-9851-ecc6ef16831d)

### Mod List

BetterRecords-1.12.2-1.6.2
Forgelin-Continuous-2.0.20.0
+Fugue-1.12.2-0.16.3
scalar-1.12.2-2.11.1

### MMC Instance Notes

\

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by Rongmario** [comment]
`Thread#stop` is deprecated since Java 8, and throws `UnsupportedOperationException`, will be looking to patch this.

**Comment by Rongmario** [comment]
Violating code is here: [latest viewable commit @ `f853262`](https://github.com/AngrySoundTech/BetterRecords/blob/f853262d20c323135f05342ac05c1468466b6a81/src/main/kotlin/tech/feldman/betterrecords/client/sound/SoundManager.kt#L60)

**Comment by kappa-maintainer** [comment]
Try this build
https://github.com/CleanroomMC/Fugue/actions/runs/11122652660

**Comment by XZYawa** [comment]
> Try this build https://github.com/CleanroomMC/Fugue/actions/runs/11122652660

Seem it doesn't work......
new log:

> [l.log](https://github.com/user-attachments/files/17211073/l.log)

**Comment by kappa-maintainer** [comment]
Shouldn't trust AI assistant...
Try the latest build

**Comment by XZYawa** [comment]
> Shouldn't trust AI assistant... Try the latest build

Again,with same exception......

> [latest.log](https://github.com/user-attachments/files/17211580/latest.log)

**Comment by kappa-maintainer** [comment]
I think I got the logic wrong... try the latest build

**Comment by XZYawa** [comment]
> I think I got the logic wrong... try the latest build

Haha,it's finally worked,thanks!
And should I wait for the repair of noumenon or close this issue now?

**Comment by kappa-maintainer** [comment]
Who's noumenon?
And you should try to play different music at the same time before closing the issue, I am not sure if it can work correctly under certain circumstance

**Comment by XZYawa** [comment]
> Who's noumenon? And you should try to play different music at the same time before closing the issue, I am not sure if it can work correctly under certain circumstance

Cleanroom loader noumenon,as mentioned above @Rongmario.
At present there seems to be no problem.
Except for if the record is taken out before the download is complete,the progress bar will not disappear and it will still play,but in forge the original mod also have similar bug.
