### ISSUE TITLE
Crash with Gregtech Food Option

### ISSUE THREAD

**Issue by ChenHaoYan1234** [CleanroomMC/Cleanroom#214]
### Cleanroom Version

cleanroom-0.2.3-alpha+build.16.run.710

### Java Version

Java 21

### Graphics Card Vendor

Intel iGPU

### Bug Report

[crash-2024-10-02_08.12.31-client.txt](https://github.com/user-attachments/files/17218348/crash-2024-10-02_08.12.31-client.txt)
[latest.log](https://github.com/user-attachments/files/17218349/latest.log)

### Mod List

codechickenlib
gregtech
gcym
gregtechfoodoption

### MMC Instance Notes

none

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Known bug, fixed in https://github.com/bruberu/GregTechFoodOption/pull/77
Please visit our Discord to get latest build

**Comment by kappa-maintainer** [comment]
Update: just use gtfo 1.12.1 (latest)

**Comment by Rongmario** [comment]
PR is merged, closing issue.
