### ISSUE TITLE
Crash with Chameleon 

### ISSUE THREAD

**Issue by G1ll0u** [CleanroomMC/Cleanroom#215]
### Your CleanroomMC Discord Username

jubitus.

### Cleanroom Version

0.2.3a

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

https://mclo.gs/10akEYn

### Mod List

       | State | ID                        | Version                   | Source                                                  | Signature                                |
       |:----- |:------------------------- |:------------------------- |:------------------------------------------------------- |:---------------------------------------- |
       | LCH   | minecraft                 | 1.12.2                    | minecraft.jar                                           | None                                     |
       | LCH   | mcp                       | 9.42                      | minecraft.jar                                           | None                                     |
       | LCH   | configanytime             | 3.0                       | cleanroom-0.2.3-alpha-universal.jar                     | None                                     |
       | LCH   | cleanroom                 | 0.2.3-alpha               | cleanroom-0.2.3-alpha-universal.jar                     | None                                     |
       | LCH   | FML                       | **.**.**.**                 | cleanroom-0.2.3-alpha-universal.jar                     | None                                     |
       | LCH   | forge                     | 14.23.5.2860              | cleanroom-0.2.3-alpha-universal.jar                     | None                                     |
       | LCH   | creativecoredummy         | 1.0.0                     | minecraft.jar                                           | None                                     |
       | LCH   | placeholdername           | 1.0.0                     | groovyscript-1.1.3.jar                                  | None                                     |
       | LCH   | itemphysic                | 1.4.0                     | minecraft.jar                                           | None                                     |
       | LCH   | littletilescore           | 1.0.0                     | minecraft.jar                                           | None                                     |
       | LCH   | otgcore                   | 1.12.2-v9.5-R2            | minecraft.jar                                           | None                                     |
       | LCH   | mixinbooter               | 10.0                      | cleanroom-0.2.3-alpha-universal.jar                     | None                                     |
       | LCH   | biometweakercore          | 1.0.39                    | minecraft.jar                                           | None                                     |
       | LCH   | rpintegration             | 1.12.2-1.5.1.0            | rpintegration-1.12.2-1.5.1.0.jar                        | None                                     |
       | LCH   | randompatches             | 1.12.2-1.22.1.10          | randompatches-1.12.2-1.22.1.10.jar                      | None                                     |
       | LCH   | redcore                   | 0.5.1                     | !Red-Core-MC-1.7-1.12-0.5.1.jar                         | None                                     |
       | LCH   | fugue                     | 1.12.2-0.16.3             |  Fugue-1.12.2-0.16.3.jar                                | None                                     |
       | LCH   | creativecore              | 1.10.0                    | CreativeCore_v1.10.71_mc1.12.2.jar                      | None                                     |
       | LCH   | littletiles               | 1.5.0                     | LittleTiles_v1.5.87_mc1.12.2.jar                        | None                                     |
       | LCH   | alet                      | 1.0                       | A_Little_Extra_Tiles-1.1.0-pre029.jar                   | None                                     |
       | LCH   | ageofweapons              | 0.13.5                    | Age-of-Weapons-1.12.2-(v.0.13.6).jar                    | None                                     |
       | LCH   | alfheim                   | 1.4                       | Alfheim-1.4.jar                                         | None                                     |
       | LCH   | codechickenlib            | **.**.**.**                 | CodeChickenLib-1.12.2-3.2.3.358-universal.jar           | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCH   | ancientwarfare            | 1.12.2-2.9.11             | ancientwarfare-1.12.2-2.9.11.jar                        | None                                     |
       | LCH   | ancientwarfareautomation  | 1.12.2-2.9.11             | ancientwarfare-1.12.2-2.9.11.jar                        | None                                     |
       | LCH   | ancientwarfarenpc         | 1.12.2-2.9.11             | ancientwarfare-1.12.2-2.9.11.jar                        | None                                     |
       | LCH   | ancientwarfarestructure   | 1.12.2-2.9.11             | ancientwarfare-1.12.2-2.9.11.jar                        | None                                     |
       | LCH   | ancientwarfarevehicle     | 1.12.2-2.9.11             | ancientwarfare-1.12.2-2.9.11.jar                        | None                                     |
       | LCH   | jei                       | 4.25.5                    | HadEnoughItems_1.12.2-4.25.5.jar                        | None                                     |
       | LCH   | appleskin                 | 1.0.14                    | AppleSkin-mc1.12-1.0.14.jar                             | None                                     |
       | LCH   | quark                     | r1.6-179                  | Quark-r1.6-179.jar                                      | None                                     |
       | LCH   | autoreglib                | 1.3-32                    | AutoRegLib-1.3-32.jar                                   | None                                     |
       | LCH   | ichunutil                 | 7.2.2                     | iChunUtil-1.12.2-7.2.2.jar                              | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCH   | backtools                 | 7.0.1                     | BackTools-1.12.2-7.0.1.jar                              | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCH   | betteradvancements        | **.**.**.**                  | BetterAdvancements-1.12.2-0.1.0.77.jar                  | None                                     |
       | LCH   | betterbiomeblend          | 1.12.2-1.1.7-forge        | betterbiomeblend-1.12.2-1.1.7-forge.jar                 | None                                     |
       | LCH   | bettercombatmod           | 1.5.6                     | BetterCombat-1.12.2-1.5.6.jar                           | None                                     |
       | LCH   | bibliocraft               | 2.4.6                     | BiblioCraft[v2.4.6][MC1.12.2].jar                       | None                                     |
       | LCH   | biometweaker              | 3.2.369                   | BiomeTweaker-1.12.2-3.2.369.jar                         | 631f326344f7f5fd7df7eb940760ebd52b7c9c17 |
       | LCH   | biomesoplenty             | 7.0.1.2445                | BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar           | None                                     |
       | LCH   | blockcraftery             | 1.12.2-1.3.1              | blockcraftery-1.12.2-1.3.1.jar                          | None                                     |
       | LCH   | modularui                 | 2.4.3                     | modularui-2.4.3.jar                                     | None                                     |
       | LCH   | bogosorter                | 1.4.9                     | bogosorter-1.4.9.jar                                    | None                                     |
       | LCH   | spark                     | 1.5.2                     | spark-forge1122.jar                                     | None                                     |
       | LCH   | loliasm                   | 5.20                      | censoredasm5.20.jar                                     | None                                     |
       | LCH   | cfm                       | 6.5.0                     | cfm-legacy-1.12.2-6.5.0.jar                             | None                                     |
       | LCH   | chameleon                 | 1.12.2-4.1.3              | Chameleon-1.12.2-4.1.3.jar                              | None                                     |
       | LCH   | charm                     | 1.4                       | Charm-1.12.2-1.4.1.jar                                  | None                                     |
       | LCH   | chiselsandbits            | 14.33                     | chiselsandbits-14.33.jar                                | None                                     |
       | LCH   | morpheus                  | 1.12.2-3.5.106            | Morpheus-1.12.2-3.5.106.jar                             | None                                     |
       | LCH   | comforts                  | **.**.**.**                   | comforts-1.12.2-1.4.1.3.jar                             | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
       | LCH   | controlling               | 3.0.10                    | Controlling-3.0.12.4.jar                                | None                                     |
       | LCH   | corpse                    | 1.12.2-1.0.8              | corpse-1.12.2-1.0.8.jar                                 | None                                     |
       | LCH   | customnpcs                | 1.12                      | CustomNPCs_1.12.2-(05Jul20).jar                         | None                                     |
       | LCH   | ptrmodellib               | 1.0.5                     | PTRLib-1.0.5.jar                                        | None                                     |
       | LCH   | props                     | **.**.**.**                   | Decocraft-2.6.3.7_1.12.2.jar                            | None                                     |
       | LCH   | doggytalents              | **.**.**.**                  | DoggyTalents-1.12.2-1.15.1.6.jar                        | None                                     |
       | LCH   | dynamictrees              | 1.12.2-0.13.4             | DramaticTrees-1.12.2-0.13.4.jar                         | None                                     |
       | LCH   | openterraingenerator      | v9.5-R2                   | OpenTerrainGenerator-1.12.2-v9.5-R2.jar                 | None                                     |
       | LCH   | dregora                   | 1.0                       | Dregora-1.12.2-v2.9 [DEL OLD FILES] - [The Big One].jar | None                                     |
       | LCH   | forgelin                  | 1.8.4                     | Forgelin-Continuous-2.0.0.1.jar                         | None                                     |
       | LCH   | futuremc                  | 0.2.6                     | Future-MC-0.2.19.jar                                    | None                                     |
       | LCH   | mocreatures               | 12.4.3                    | DrZharks-MoCreatures-Extended-12.4.3.jar                | None                                     |
       | LCH   | orelib                    | **.**.**.**                   | OreLib-1.12.2-3.6.0.1.jar                               | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCH   | dsurround                 | @VERSION@                 | DynamicSurroundings-1.12.2-3.6.3.jar                    | None                                     |
       | LCH   | dynamictreesbop           | 1.12.2-9999.9999.9999z    | DynamicTreesBOP-1.12.2-1.5.2.jar                        | None                                     |
       | LCH   | dynamictreesquark         | 1.12.2-1.0.6              | DynamicTreesQuark-1.12.2-1.0.6.jar                      | None                                     |
       | LCH   | entityculling             | @VER@                     | entityculling-1.12.2-1.6.3.jar                          | None                                     |
       | LCH   | entitydistance            | 1.0.3                     | entitydistance-1.0.3.jar                                | None                                     |
       | LCH   | exoticbirds               | 1.0                       | Exotic Birds 1.12.2-3.2.0.jar                           | None                                     |
       | LCH   | falling_tree              | 2.4.0                     | FallingTree-1.12.2-2.4.0.jar                            | None                                     |
       | LCH   | xporbclump                | @VERSION@                 | Fixeroo-2.2-hotfix.1.jar                                | None                                     |
       | LCH   | fluidlogged_api           | 2.2.7                     | Fluidlogged-API-v2.2.7-mc1.12.2.jar                     | None                                     |
       | LCH   | forgelin_continuous       | **.**.**.**                   | Forgelin-Continuous-2.0.0.1.jar                         | None                                     |
       | LCH   | fpsreducer                | mc1.12.2-1.20             | FpsReducer-mc1.12.2-1.20.jar                            | None                                     |
       | LCH   | ftbbackups                | 1.1.0.1                   | FTBBackups-1.1.0.1.jar                                  | None                                     |
       | LCH   | ftblib                    | **.**.**.**                   | FTBLib-5.4.7.2.jar                                      | None                                     |
       | LCH   | ftbutilities              | **.**.**.**                 | FTBUtilities-5.4.1.131.jar                              | None                                     |
       | LCH   | grapplemod                | 1.12.2-v13                | grappling_hook_mod-1.12.2-v13.jar                       | None                                     |
       | LCH   | groovyscript              | 1.1.3                     | groovyscript-1.1.3.jar                                  | None                                     |
       | LCH   | waila                     | 1.8.26                    | Hwyla-1.8.26-B41_1.12.2.jar                             | None                                     |
       | LCH   | itlt                      | 1.0.4                     | itlt-1.12.x-1.0.4.jar                                   | None                                     |
       | LCH   | journeymap                | 1.12.2-5.7.1p2            | journeymap-1.12.2-5.7.1p2.jar                           | None                                     |
       | LCH   | kirosblocks               | 1.2.1                     | kirosblocks-1.2.2.jar                                   | None                                     |
       | LCH   | ksyxis                    | 1.3.2                     | Ksyxis-1.3.2.jar                                        | None                                     |
       | LCH   | log_un_spam               | 1.0-1.12                  | LogUnSpam-1.0-1.12.jar                                  | None                                     |
       | LCH   | mcwbridges                | 1.0.6                     | mcw-bridges-1.0.6b-mc1.12.2.jar                         | None                                     |
       | LCH   | mcwdoors                  | 1.3                       | mcw-doors-1.0.3-mc1.12.2.jar                            | None                                     |
       | LCH   | mcwfences                 | 1.0.0                     | mcw-fences-1.0.0-mc1.12.2.jar                           | None                                     |
       | LCH   | mcwfurnitures             | 1.0.1                     | mcw-furniture-1.0.1-mc1.12.2beta.jar                    | None                                     |
       | LCH   | mcwlights                 | 1.0.6                     | mcw-lights-1.0.6-mc1.12.2forge.jar                      | None                                     |
       | LCH   | mcwpaintings              | 1.0.5                     | mcw-paintings-1.0.5-1.12.2forge.jar                     | None                                     |
       | LCH   | mcwpaths                  | 1.0.2                     | mcw-paths-1.0.2forge-mc1.12.2.jar                       | None                                     |
       | LCH   | mcwroofs                  | 1.0.2                     | mcw-roofs-1.0.2-mc1.12.2.jar                            | None                                     |
       | LCH   | mcwtrpdoors               | 1.0.2                     | mcw-trapdoors-1.0.3-mc1.12.2.jar                        | None                                     |
       | LCH   | mcwwindows                | 1.0                       | mcw-windows-1.0.0-mc1.12.2.jar                          | None                                     |
       | LCH   | millenaireextended        | 1.3.3                     | Millenaire Extended-1.12.2-1.3.3.jar                    | None                                     |
       | LCH   | millenaire                | Millénaire 8.1.2          | millenaire-8.1.2.jar                                    | None                                     |
       | LCH   | mobends                   | 1.2.1                     | MoBends_1.12.2-1.2.1-19.12.21.jar                       | None                                     |
       | LCH   | guilib                    | $version                  | morepaintings-paintings-1.12.2-5.0.1.2.jar              | None                                     |
       | LCH   | paintingselgui            | $version                  | morepaintings-paintings-1.12.2-5.0.1.2.jar              | None                                     |
       | LCH   | morepaintings             | $version                  | morepaintings-paintings-1.12.2-5.0.1.2.jar              | None                                     |
       | LCH   | mousetweaks               | 2.10.1                    | MouseTweaks-2.10.1-mc1.12.2.jar                         | None                                     |
       | LCH   | llibrary                  | 1.7.20                    | llibrary-1.7.20-1.12.2.jar                              | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCH   | mowziesmobs               | 1.5.8                     | mowziesmobs_1.12.2_1.5.8.jar                            | None                                     |
       | LCH   | multiblocked              | 0.8.8                     | multiblocked-0.8.8.jar                                  | None                                     |
       | LCH   | multiblockednbt           | 1.1.0                     | multiblockednbt-1.1.0.jar                               | None                                     |
       | LCH   | multithreadednoise        | 0.0.2                     | MultithreadedNoise-1.12.2-0.0.2.jar                     | None                                     |
       | LCH   | uteamcore                 | **.**.**.**                 | u_team_core-forge-1.12.2-2.2.5.305.jar                  | None                                     |
       | LCH   | overworldmirror           | **.**.**.**                  | overworld_mirror-1.12.2-1.2.1.10.jar                    | None                                     |
       | LCH   | particleculling           | v1.4.3                    | particleculling-1.12.2-v1.4.3.jar                       | None                                     |
       | LCH   | placebo                   | 1.6.0                     | Placebo-1.12.2-1.6.1.jar                                | None                                     |
       | LCH   | playerattributecommands   | 1.0.0                     | PlayerAttributeCommands-1.0.0.jar                       | None                                     |
       | LCH   | randomtweaks              | 1.12.2-2.8.3.1            | randomtweaks-1.12.2-2.8.3.1.jar                         | 20d08fb3fe9c268a63a75d337fb507464c8aaccd |
       | LCH   | betterfoliage             | 2.4.2                     | RLFoliage-MC1.12-2.4.2.jar                              | None                                     |
       | LCH   | roost                     | 2.0.10                    | roost-1.12.2-2.0.10.jar                                 | None                                     |
       | LCH   | sekcphysics               | 0.1.0                     | sekcphysics-0.1.0.jar                                   | None                                     |
       | LCH   | shouldersurfing           | 2.9.6                     | ShoulderSurfing-1.12.2-2.9.6.jar                        | d6261bb645f41db84c74f98e512c2bb43f188af2 |
       | LCH   | simplezoom                | 1.3.2                     | simplezoom-1.12.2-1.3.2-universal.jar                   | None                                     |
       | LCH   | sledgehammer              | 1.12.2-2.0.26             | Sledgehammer-1.12.2-2.0.26.jar                          | None                                     |
       | LCH   | soundphysics              | 1.1.2                     | Sound-Physics-1.12.2-1.1.3.jar                          | None                                     |
       | LCH   | soundscool                | 1.12.2-1.0.1              | SoundsCool-1.12.2-1.0.1.jar                             | None                                     |
       | LCH   | storagedrawers            | 5.5.2                     | StorageDrawers-1.12.2-5.5.2.jar                         | None                                     |
       | LCH   | sasit                     | 1.1.32                    | StuffASockInIt-1.12.2-1.1.32.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | stupidthings              | 1.1.6                     | Stupid Things-1.12.2-1.1.6.jar                          | None                                     |
       | LCH   | tellme                    | 0.7.0-dev.20200919.184303 | tellme-1.12.2-0.7.0-dev.20200919.184303.jar             | 2b03e1423915a189b8094816baa18f239d576dff |
       | LCH   | travelersbackpack         | 1.0.35                    | TravelersBackpack-1.12.2-1.0.35.jar                     | None                                     |
       | LCH   | tumbleweed                | 1.12-0.4.7                | tumbleweed-1.12-0.4.7.jar                               | None                                     |
       | LCH   | unifine                   | 1.12.2-0.1.0              | Unifine-1.12.2-0.1.0.jar                                | None                                     |
       | LCH   | universaltweaks           | 1.12.0                    | UniversalTweaks-1.12.2-1.12.0.jar                       | None                                     |
       | LCH   | waitingtime               | 1.0.1                     | WaitingTime-1.0.1.jar                                   | None                                     |
       | LCH   | worldedit                 | 6.1.10                    | worldedit-forge-mc1.12.2-6.1.10-dist.jar                | None                                     |
       | LCH   | worldeditselections-forge | 1.0                       | worldeditselections-forge-1.0.5-1.12.2.jar              | None                                     |
       | LCH   | worldutils                | 0.5.0-dev.20210322.174648 | worldutils-1.12.2-0.5.0-dev.20210322.174648.jar         | 2b03e1423915a189b8094816baa18f239d576dff |
       | LCH   | wrapfix                   | 1.3.5-beta                | WrapFix-1.3.5-beta.jar                                  | None                                     |
       | LCH   | xercapaint                | 1.12.2-1.3                | xercapaint-1.12.2-1.3.jar                               | None                                     |
       | LCH   | betteranimalsplus         | 9.0.1                     | betteranimalsplus-1.12.2-9.0.1.jar                      | None                                     |
       | LCH   | customdisc                | 1.3                       | customdisc-1.12.2-1.2.1.jar                             | None                                     |
       | LCH   | structurize               | 1.12.2-0.10.277-RELEASE   | structurize-1.12.2-0.10.277-RELEASE.jar                 | None                                     |
       | LCH   | minecolonies              | 1.12.2-0.11.841-ALPHA     | minecolonies-1.12.2-0.11.841-BETA-universal.jar         | None                                     |
       | LCH   | mysticallib               | 1.12.2-1.13.0             | mysticallib-1.12.2-1.13.0.jar                           | None                                     |
       | UD    | scalar                    | 2.11.1                    | minecraft.jar                                           | None                                     |

### MMC Instance Notes

Since I moved to Cleanroom, Chameleon library, required for Storage Drawers, crashes on start.

Have a nice day !

(I can't submit issues without checking all marks)

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by Rongmario** [comment]
Looks like you've installed a deobfuscated version of `Chameleon`, did you get it from CurseForge or Modrinth?

**Comment by G1ll0u** [comment]
Duplicate of : 
[https://github.com/CleanroomMC/Cleanroom/issues/134](https://github.com/CleanroomMC/Cleanroom/issues/134)

Have a nice day !

**Comment by Rongmario** [comment]
Just reported the file to Modrinth.
