### ISSUE TITLE
Unable to launch with EndReborn [0.3.9] in modpack Ocean Outlast V79A

### ISSUE THREAD

**Issue by UraraChiya** [CleanroomMC/Cleanroom#222]
### Cleanroom Version

0.2.3-alpha+build.23.run.717

### Java Version

Java 21

### Graphics Card Vendor

Intel iGPU

### Bug Report

https://mclo.gs/luMnsXV

### Mod List

_MixinBootstrap-1.1.0.jar.disabled
_supermartijn642corelib-1.1.17a-forge-mc1.12.jar
!configanytime-3.0.jar.disabled
!mixinbooter-9.4.jar.disabled
!Red-Core-MC-1.8-1.12-0.6-Dev-7.jar
[___MixinCompat-1.1-1.12.2___].jar.disabled
[1.12.2] SecurityCraft v1.9.11.jar
+Fugue-1.12.2-0.16.3.jar
ActuallyAdditions-1.12.2-r152.jar
AdvancedBackups-forge-1.12-3.6.3.jar
advancedcombat-oc-edition-0.1.jar
ae2-uel-v0.56.6.jar
AE2WTLib-1.12.2-1.0.34.jar
agricraft-2.12.0-1.12.2-b2.jar
AkashicTome-1.2-12.jar
Alfheim-1.4.jar
antighost-1.12-forge14.21.1.2387-1.1.1.jar
AppleCore-mc1.12.2-3.4.0.jar
AppleSkin-mc1.12-1.0.14.jar
AquaAcrobatics-1.15.4.jar
Aquaculture-1.12.2-1.6.8.jar
armoryexpansion-2.0.0-alpha.jar
ArtemisLib-1.12.2-v1.0.6.jar
AutoRegLib-1.3-32.jar
Avaritia-1.12.2-3.3.0.37-universal.jar
Avaritiaddons-1.12.2-1.9.jar
AvaritiaTweaks-1.12.2-1.3.1.jar
badwithernocookiereloaded-1.12.2-3.4.18.jar
base-1.12.2-3.14.0.jar
BattleTowers-1.12.2.jar
Baubles-1.12.2-1.0.6.0.jar
baubley-heart-canisters-1.12.2-1.2.3.jar
bdlib-1.14.4.1-mc1.12.2.jar
beastslayer-2.0.test_1.04.jar
bedpatch-2.2-1.12.2.jar
BetterAdvancements-1.12.2-0.1.0.77.jar
BetterFps-1.4.8.jar
betterspawnercontrol_1.12.2-1.5.jar
bewitchment-1.12.2-0.0.22.64.jar
BHMenu-Forge-1.12.2-2.4.3.jar
bibliotheca-1.3.6-1.12.2.jar
bilingualname-1.2.jar
blockcraftery-1.12.2-1.3.1.jar
blockdrops-1.12.2-1.4.0.jar
bloodagricraft-1.0.0.jar
BloodMagic-1.12.2-2.4.3-105.jar
bloodtinker-1.0.5.jar
blue_skies-1.12.2-v1.1.3.jar
bogosorter-1.4.9.jar
bonsaitrees-1.1.4-b170.jar
Bookshelf-1.12.2-2.3.590.jar
Botania r1.10-364.4.jar
BrandonsCore-1.12.2-2.4.20.162-universal.jar
BTFixes-1.12.2-1.2.2.jar
BuildingGadgets-2.8.4.jar
Cathedral-1.12.2-1.9.9.jar
censoredasm5.20.jar
Chameleon-1.12-4.1.3.jar
Chisel-MC1.12.2-1.0.2.45.jar
chiselsandbits-14.33.jar
Chocolate_Quest_Repoured-1.12.2-2.6.16B.jar
Chunk Pregenerator-V1.12-2.5.7.jar
clarity-1.1.jar
ClayBucket-1.12-1.1.jar
clearwater-1.2.jar
ClientTweaks_1.12.2-3.1.11.jar
Clumps-3.1.2.jar
CodeChickenLib-1.12.2-3.2.3.358-universal.jar
CoFHCore-1.12.2-4.6.6.1-universal.jar
CoFHWorld-1.12.2-1.4.0.1-universal.jar
collective-1.12.2-3.0.jar
CommonCapabilities-1.12.2-2.4.8.jar
CompactDrawers-1.12.2-1.0.5.125.jar
Computronics-1.12.2-1.6.6.jar
conarm-1.12.2-1.2.5.10.jar
Controlling-3.0.12.4.jar
CookingForBlockheads_1.12.2-6.5.0.jar
CosmeticArmorReworked-1.12.2-v5a.jar
CraftingTweaks_1.12.2-9.0.1.jar
CraftTweaker2-1.12-4.1.20.693.jar
CreativeCore_v1.10.71_mc1.12.2.jar
CreativePlus MC1.12.2 v1.0.2.jar
CTM-MC1.12.2-1.0.2.31.jar
Cucumber-1.12.2-1.1.3.jar
CustomStartingGear-1.12-1.2.0.9-universal.jar
CyclopsCore-1.12.2-1.6.7.jar
deathbackup_1.12.2-1.4.jar
DefaultOptions_1.12.2-9.2.8.jar
Dungeons2-mc1.12.2-f14.23.5.2859-v2.0.0.jar
dynamistics-1.0.2.jar
EnchantmentDescriptions-1.12.2-1.1.20.jar
EnderCore-1.12.2-0.5.78.jar
EnderIO-1.12.2-5.3.72.jar
EnderIO-endergy-1.12.2-5.3.72.jar
EnderStorage-1.12.2-2.4.6.137-universal.jar
EnderTweaker-1.12.2-1.2.3.jar
EndReborn [0.3.9].jar
EnergyControl-1.12.2-0.3.2.jar
environmentaltech-1.12.2-2.0.20.1.jar
EquipmentCompare-1.12.2-1.3.4.jar
EquivalentEnergistics-1.12.2-0.9.0.jar
equivalentstone-1.12.2-1.2.0b.jar
Erebus-1.0.32.jar
eternalsingularity-1.12.2-1.0.7.jar
ExCompressum_1.12.2-3.0.32.jar
exnihilocreatio-1.12.2-0.4.7.2.jar
extendedcrafting-nomifactory-edition-1.7.0.7.jar
ExtraBitManipulation-1.12.2-3.4.1.jar
ExtraCells-1.12.2-2.6.7.jar
extracpus-1.12.2-1.2.1.jar
extrautils2-1.12-1.9.9.jar
fancymenu_forge_2.14.9_MC_1.12-1.12.2.jar
FasterLadderClimbing-1.12-0.1-146.jar
FastFurnace-1.12.2-1.3.1.jar
FeaturedServers-1.12-1.0.6.jar
Fish's Undead Rising-1.4.2.jar
Fixeroo-2.3.2.jar
Flopper-1.12.2-1.0.3.jar
FluxNetworks-1.12.2-4.1.1.34.jar
foamflower-1.12.2-1.0.0.0-beta1.jar
Forgelin-1.8.4.jar
ForgeMultipart-1.12.2-2.6.2.83-universal.jar
fossilsarcheology-8.0.6.jar
ftb-ultimine-1202.3.5.jar
FTBLib-5.4.7.2.jar
FTBMoney-1.2.0.47.jar
FTBQuests-1202.9.0.15.jar
FTBUtilities-5.4.1.131.jar
FullscreenWindowed-1.12-1.6.0.jar
GameStages-1.12.2-2.0.123.jar
geckolib-forge-1.12.2-3.0.31.jar
generators-0.9.20.12-mc1.12.2.jar
geneticsreborn-1.12-1.32.jar
Geographicraft-1.12.2-0.9.8.5.jar
GlobalGameRules-1.12.2-2.2.7.jar
GottschCore-mc1.12.2-f14.23.5.2859-v1.15.1.jar
Guide-API-1.12-2.1.8-63.jar
GunpowderLib-1.12.2-1.1.jar
HadEnoughItems_1.12.2-4.26.0.jar
HammerLib-1.12.2-12.2.52.jar
Hats-1.12.2-7.1.1.jar
Hwyla-1.8.26-B41_1.12.2.jar
ic2-tweaker-0.2.1+build.4.jar
ic2patcher-2.0.9.jar
iChunUtil-1.12.2-7.2.2.jar
IFPatcher-2.4.0.jar
ImprovableSkills-1.12.2-12.4.68.jar
industrialcraft-2-2.8.222-ex112.jar
industrialforegoing-1.12.2-1.12.13-237.jar
infinitylib-1.12.1.jar
IntegrationForegoing-1.12.2-1.11.jar
inworldcrafting-1.12.2-1.2.0-universal.jar
IronBackpacks-1.12.2-3.0.8-12.jar
ironchest-1.12.2-7.0.72.847.jar
ItemFilters-1.0.4.2.jar
itemzoom_1.12.2-1.11.jar
Jade-0.1.0.jar
JAOPCA-1.12.2-2.2.8.106.jar
JAOPCAAgriculture-1.12.2-1.2.1.17.jar
JAOPCASingularities-1.12.2-2.2.0.9.jar
jei_area_fixer-1.5.0.jar
JEI-Utilities-1.12.2-0.2.12.jar
jeiintegration_1.12.2-1.6.0.jar
jeivillagers-1.12-1.0.2.jar
jetif-1.12.2-1.5.2.jar
journeymap-1.12.2-5.7.1p2.jar
just-enough-harvestcraft-1.12.2-1.7.2.jar
JustEnoughIDs-1.0.4-SNAPSHOT-thin.jar
JustEnoughResources-1.12.2-0.9.3.203.jar
konkrete_forge_1.6.1_MC_1.12-1.12.2.jar
lanupnp-1.1-1.12.2.jar
lazy-ae2-1.12.2-1.1.26.jar
lazy-ae2-patch-1.1.0.jar
lemonlib-1.12.2-1.3.0.jar
libnine-1.12.2-1.2.1.jar
LibraryEx-1.12.2-1.2.2.jar
llibrary-1.7.20-1.12.2.jar
LodsOfEmone-0.1.jar
Login_Shield-1.12.2-6-g5654706.jar
lootcapacitortooltips-1.3.jar
LootTweaker-0.4.1+MC1.12.2.jar
Magical Map OC Edition-1.12.2-2.jar
MagicalPsi-1.3.2.jar
ManaVisualizer-r1.0-1.jar
Mantle-1.12-1.3.3.55.jar
matc-1.0.1-hotfix.jar
mcjtylib-1.12-3.5.4.jar
Mekanism-1.12.2-9.8.3.390.jar
MekanismGenerators-1.12.2-9.8.3.390.jar
MekanismTools-1.12.2-9.8.3.390.jar
moartinkers-0.6.0.jar
ModifierKeyFix-1.0.jar
modnametooltip_1.12.2-1.10.1.jar
modtweaker-4.0.20.11.jar
ModularAssembly-1.12.2-1.0.2.jar
modularmachinery-1.12.2-1.11.1.jar
modularui-2.4.3.jar
moreoverlays-1.15.1-mc1.12.2.jar
moresoundconfig-1.0.4.jar
Morph-o-Tool-1.2-21.jar
Morpheus-1.12.2-3.5.106.jar
MouseTweaks-2.10.1-mc1.12.2.jar
mowziesmobs_1.12.2_1.5.8.jar
MTLib-3.0.7.jar
multimob-1.0.5.jar
MysticalAdaptations-1.12.2-1.8.8.jar
MysticalAgradditions-1.12.2-1.3.2.jar
MysticalAgriculture-1.12.2-1.7.5.jar
MysticalCreations-1.12.2-1.6.1.jar
mysticallib-1.12.2-1.13.0.jar
NaturesCompass-1.12.2-1.8.5.jar
NetherEx-1.12.2-2.2.5.jar
NetherPortalFix_1.12.1-5.3.17.jar
NotEnoughEnergistics-1.12.2-2.0.7.jar
OpenBlocks-1.12.2-1.8.1.jar
OpenComputers-MC1.12.2-1.8.6+cd8851e.jar
OpenModsLib-1.12.2-0.12.2.jar
Ore Tweaker-1.0.2-1.12.0.jar
p455w0rdslib-1.12.2-2.3.161.jar
PackagedAuto-1.12.2-1.0.14.55.jar
PackagedAvaritia-1.12.2-1.0.2.19.jar
PackagedExCrafting-1.12.2-1.0.2.24.jar
PackMode Menu OC Edition-1.jar
packmode-1.12.2-1.2.0.jar
Pam's HarvestCraft 1.12.2zg.jar
Patchouli-1.0-26.jar
Pewter-1.4.3.jar
Placebo-1.12.2-1.6.1.jar
PlaneFix-1.12.2-1.0.0.jar
plustic-8.0.6.jar
PotionCore-1.9_for_1.12.2.jar
PrimalTech-0.3.5.jar
primitivemobs-1.2.3a.jar
ProgressiveBosses-1.5.4-mc1.12.x.jar
ProjectE-1.12.2-PE1.4.1.jar
ProjectEX-1.2.0.40.jar
Psi-r1.1-78.2.jar
QualityTools-1.0.7_for_1.12.2.jar
quantumflux-1.12.2-2.0.18.jar
RandomThings-MC1.12.2-4.2.7.4.jar
rangedpumps-0.5.jar
ReachFix-1.12.2-1.0.10.jar
ReAuth-1.12-Forge-4.0.7.jar
RebornCore-FORK-1.12.2-3.19.5-universal.jar
RecipeStages-1.1.3.8.jar
RedstoneArsenal-1.12.2-2.6.6.1-universal.jar
RedstoneFlux-1.12-2.1.1.1-universal.jar
ResourceLoader-MC1.12.1-1.5.3.jar
rftoolspower-1.12-1.2.0.jar
scalar-1.12.2-2.11.1.jar
ScalingHealth-1.12.2-1.3.42+147.jar
SilentLib-1.12.2-3.0.14+168.jar
Simple-Void-World-1.12-1.2.0.9-universal.jar
SimpleDivingGear-1.1.1 mc 1.12.2.jar
SimpleStorageNetwork-1.12.2-2.0.0.jar
Sledgehammer-1.12.2-2.0.26.jar
Snad-1.12.1-1.7.09.16a.jar
solcarrot-1.12.2-1.8.4.jar
sonarcore-1.12.2-5.0.19-20.jar
SpellboundSpireTowers-2.0.0_for_1.12.2.jar
splashlogofix-1.0.jar
statues-rechiseled-1.12.2-1.0.1.jar
StepUp-1.0.2-mc1.10-1.12.jar
StorageDrawers-1.12.2-5.5.2.jar
supermartijn642configlib-1.1.8-forge-mc1.12.jar
supersoundmuffler-revived_1.12.2_1.0.2.10.jar
TConstruct-1.12.2-2.13.0.183.jar
tesla-core-lib-1.12.2-1.0.18.jar
theaurorian-1.12.2-1.2.jar
ThermalDynamics-1.12.2-2.5.6.1-universal.jar
ThermalExpansion-1.12.2-5.5.7.1-universal.jar
ThermalFoundation-1.12.2-2.6.7.1-universal.jar
tinkersjei-1.2.jar
TinkerToolLeveling-1.12.2-1.1.0.jar
tinyprogressions-1.12.2-3.3.34-Release.jar
TipTheScales-1.12.2-1.0.4.jar
tombstone-1.12.2-4.7.0.jar
torchmaster_1.12.2-1.8.5.0.jar
toroquest-1.12.2-5.3.jar
TravelersBackpack-1.12.2-1.0.35.jar
Treasure2-mc1.12.2-f14.23.5.2859-v2.3.0.jar
Trinkets and Baubles-0.32.5.jar
UniDict-1.12.2-3.0.10.jar
UniversalTweaks-1.12.2-1.12.0.jar
valkyrielib-1.12.2-2.0.20.1.jar
vending-1.12.2-3.0.1.2.jar
vintagefix-0.5.1.jar
VoiceChatReloaded-1.12.2-1.3.0.jar
WailaHarvestability-mc1.12-1.1.12.jar
walljump-1.12.2-1.3.2.jar
WanionLib-1.12.2-2.91.jar
Wasaila-1.0.jar
Wawla-1.12.2-2.6.275.jar
Waystones_1.12.2-4.1.0.jar
WHAT-0.2.jar
WirelessCraftingTerminal-1.12.2-3.12.97.jar
WirelessFluidTerminal-1.12.2-1.0.4.jar
WirelessInterfaceTerminal-1.12.2-1.0.2.jar
WirelessPatternTerminal-1.12.2-1.0.3.jar
woot-1.12.2-1.4.11.jar
wormhole-1.1.16-forge-mc1.12.jar
WR-CBE-1.12.2-2.3.2.33-universal.jar
WrapUp-1.12-1.1.3.jar
XU2-Patcher-1.0.0.jar
YARCF-0.14(1.12.2).jar

### MMC Instance Notes

This instance is built using Github Action.
Using installer artifact from commit: b570c8ef95b4a74ca3ca3be3a97fefe6541399c1
Action URL: https://github.com/CleanroomMC/Cleanroom/actions/runs/11230518907

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by Ecdcaeb** [comment]
add `endreborn.utils.EndHelper` to `reflectionPatchTargets` in `fugue.cfg`

**Comment by UraraChiya** [comment]
> add `endreborn.utils.EndHelper` to `reflectionPatchTargets` in `fugue.cfg`

Now the game will crash in main menu. https://mclo.gs/MsVmtsK

**Comment by ZZZank** [comment]
```log
java.lang.NullPointerException: Cannot invoke "java.util.HashMap.get(Object)" because the return value of "paulscode.sound.Library.getSources()" is null
    at net.minecraft.client.audio.SoundManager$SoundSystemStarterThread.playing(SoundManager.java:596)
    at net.minecraft.client.audio.SoundManager.updateAllSounds(SoundManager.java:258)
    at net.minecraft.client.audio.SoundHandler.update(SoundHandler.java:293)
...
```
but [Paulscode-SoundSystem](https://github.com/kovertopz/Paulscode-SoundSystem) should not be the problem, since it has used by minecraft for a very long time

please send `latest.log`

**Comment by Ecdcaeb** [comment]
> ```
> java.lang.NullPointerException: Cannot invoke "java.util.HashMap.get(Object)" because the return value of "paulscode.sound.Library.getSources()" is null
>     at net.minecraft.client.audio.SoundManager$SoundSystemStarterThread.playing(SoundManager.java:596)
>     at net.minecraft.client.audio.SoundManager.updateAllSounds(SoundManager.java:258)
>     at net.minecraft.client.audio.SoundHandler.update(SoundHandler.java:293)
> ...
> ```
> 
> but [Paulscode-SoundSystem](https://github.com/kovertopz/Paulscode-SoundSystem) should not be the problem, since it has used by minecraft for a very long time
> 
> please send `latest.log`

it has been mixined.

**Comment by Ecdcaeb** [comment]
I got a same issue https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12930

**Comment by UraraChiya** [comment]
Oh, I can lanunch now with 0.2.3-alpha+build.25.run.728. Thank you.
