### ISSUE TITLE
Not compatible with 7 Days to Mine

### ISSUE THREAD

**Issue by nenglizuida** [CleanroomMC/Cleanroom#225]
### Cleanroom Version

0.2.3

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

https://mclo.gs/2jCEz3t

### Mod List

	| State | ID                       | Version                  | Source                                                                  | Signature                                |
	|:----- |:------------------------ |:------------------------ |:----------------------------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                | 1.12.2                   | minecraft.jar                                                           | None                                     |
	| LCH   | mcp                      | 9.42                     | minecraft.jar                                                           | None                                     |
	| LCH   | configanytime            | 3.0                      | cleanroom-0.2.3-alpha.jar                                               | None                                     |
	| LCH   | cleanroom                | 0.2.3-alpha              | cleanroom-0.2.3-alpha.jar                                               | None                                     |
	| LCH   | FML                      | 8.0.99.99                | cleanroom-0.2.3-alpha.jar                                               | None                                     |
	| LCH   | forge                    | 14.23.5.2860             | cleanroom-0.2.3-alpha.jar                                               | None                                     |
	| LCH   | xaeroworldmap_core       | 1.12.2-1.0               | minecraft.jar                                                           | None                                     |
	| LCH   | xaerominimap_core        | 1.12.2-1.0               | minecraft.jar                                                           | None                                     |
	| LCH   | creativecoredummy        | 1.0.0                    | minecraft.jar                                                           | None                                     |
	| LCH   | redirectionor            | 1.7 for 1.12.2-1.8.8     | minecraft.jar                                                           | None                                     |
	| LCH   | mixinbooter              | 10.0                     | cleanroom-0.2.3-alpha.jar                                               | None                                     |
	| LCH   | foamfixcore              | 7.7.4                    | minecraft.jar                                                           | None                                     |
	| LCH   | techguns_core            | 1.12.2-1.0               | minecraft.jar                                                           | None                                     |
	| LCH   | itemblacklist            | 1.4.3                    | [物品黑名单(玩法类)]ItemBlacklist-1.4.3.jar                                     | None                                     |
	| LCH   | mod_lavacow              | 1.4.2                    | [Fish的不死崛起(玩法类)]Fish's Undead Rising-1.4.2.jar                          | None                                     |
	| LCH   | jei                      | 4.26.0                   | [HEI内置管理器(辅助类)]HadEnoughItems_1.12.2-4.26.0.jar                         | None                                     |
	| LCH   | ftblib                   | 5.4.7.2                  | [FTB核心(核心类)]FTBLib-5.4.7.2.jar                                          | None                                     |
	| LCH   | ic2                      | 2.8.222-ex112            | [工业时代2(玩法类)]industrialcraft-2-2.8.222-ex112.jar                         | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCH   | itemfilters              | 1.0.4.2                  | [物品过滤器(玩法类)]ItemFilters-1.0.4.2.jar                                     | None                                     |
	| LCH   | ftbquests                | 1202.9.0.15              | [FTB任务(玩法类)]FTBQuests-1202.9.0.15.jar                                   | None                                     |
	| LCH   | cfm                      | 6.3.0                    | [MrCrayfish的家具(玩法类)]furniture-6.3.2-1.12.2.jar                          | None                                     |
	| LCH   | bookshelf                | 2.3.590                  | [前置库(核心类)]Bookshelf-1.12.2-2.3.590.jar                                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | ctm                      | MC1.12.2-1.0.2.31        | [连接纹理(玩法类)]CTM-MC1.12.2-1.0.2.31.jar                                    | None                                     |
	| LCH   | twilightforest           | 3.11.2000                | [暮色森林修复版(玩法类)]twilightforest-1.12.2-3.11.2000.jar                       | None                                     |
	| LCH   | abyssalcraft             | 1.10.6                   | [深渊国度(玩法类)]AbyssalCraft-1.12.2-1.10.6.jar                               | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCH   | jeid                     | 2.2.1                    | [REID(玩法类)]RoughlyEnoughIDs-2.2.1.jar                                   | None                                     |
	| LCH   | rltweaker                | 0.6.3                    | [RL整体优化(优化类)]RLTweaker-1.12.2-0.6.3.jar                                 | None                                     |
	| LCH   | inventorytweaks          | 1.63+release.109.220f184 | [R键整理(辅助类)]InventoryTweaks-1.63.jar                                     | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCH   | xaeroworldmap            | 1.39.0                   | [Xaero世界地图(辅助类)]XaerosWorldMap_1.39.0_Forge_1.12.jar                    | None                                     |
	| LCH   | xaerominimap             | 24.5.0                   | [Xaero小地图(辅助类)]Xaeros_Minimap_24.5.0_Forge_1.12.jar                     | None                                     |
	| LCE   | sevendaystomine          | 1.12.2-1.0.3.2           | [七日杀(玩法类)]sevendaystomine-1.12.2-1.0.3.2.jar                            | None                                     |
	| LC    | waystones                | 4.1.0                    | [传送石碑(玩法类)]Waystones_1.12.2-4.1.0.jar                                   | None                                     |
	| LC    | w2w                      | 1.2.1                    | [传送石碑路径点(玩法类)]w2w-1.2.1.jar                                             | None                                     |
	| LC    | savemystronghold         | 1.12.2-1.0.0             | [保存的我要塞(玩法类)]savemystronghold-1.12.2-1.0.0.jar                          | None                                     |
	| LC    | coroutil                 | 1.12.1-1.2.37            | [前置库(核心类)]coroutil-1.12.1-1.2.37.jar                                    | None                                     |
	| LC    | zombieawareness          | 1.12.1-1.11.16           | [僵尸意识(玩法类)]zombieawareness-1.12.1-1.11.16.jar                           | None                                     |
	| LC    | homoium                  | 1.0.8                    | [先辈(优化类)]homoium-1.0.8.jar                                              | None                                     |
	| LC    | champions                | 1.12.2-1.0.11.10         | [冠军(玩法类)]champions-1.12.2-1.0.11.10.jar                                 | b33d2c8df492beff56d1bbbc92da49b8ab7345a1 |
	| LC    | chisel                   | MC1.12.2-1.0.2.45        | [凿子(玩法类)]Chisel-MC1.12.2-1.0.2.45.jar                                   | None                                     |
	| LC    | redcore                  | 0.6-Dev-7                | [前置库(核心类)]!Red-Core-MC-1.8-1.12-0.6-Dev-7.jar                           | None                                     |
	| LC    | mysteriumlib             | 1.5.7                    | [前置库(核心类)]+mysteriumlib-1.5.7.jar                                       | None                                     |
	| LC    | bspkrscore               | 8.0.0                    | [前置库(核心类)][1.12.2]bspkrscore-universal-8.0.1.jar                        | None                                     |
	| LC    | extendedrenderer         | v1.0                     | [前置库(核心类)]coroutil-1.12.1-1.2.37.jar                                    | None                                     |
	| LC    | configmod                | v1.0                     | [前置库(核心类)]coroutil-1.12.1-1.2.37.jar                                    | None                                     |
	| LC    | creativecore             | 1.10.0                   | [前置库(核心类)]CreativeCore_v1.10.71_mc1.12.2.jar                            | None                                     |
	| LC    | nether_api               | 1.3.0                    | [前置库(核心类)]Nether-API-v1.3.0-mc1.12.2.jar                                | None                                     |
	| LC    | omlib                    | 3.1.5-256                | [前置库(核心类)]omlib-1.12.2-3.1.5-256.jar                                    | None                                     |
	| LC    | dynamictrees             | 1.12.2-0.9.29            | [动态的树(玩法类)]DynamicTrees-1.12.2-0.9.29.jar                               | None                                     |
	| LC    | dynamictreesic2          | 1.12.2-1.2.3             | [动态的树之工业时代2附属(玩法类)]DynamicTreesIC2-1.12.2-1.2.3.jar                     | None                                     |
	| LC    | dynamictreesttf          | 1.12.2-1.2.3             | [动态的树之暮色森林附属(玩法类)]dynamictreesTheTwilightForest-1.12.2-1.2.3.jar        | None                                     |
	| LC    | mm_lib                   | 2.3.0                    | [妖怪之山通用库(核心类)]MMLib-2.3.0.jar                                           | None                                     |
	| LC    | sakura                   | 1.0.7-1.12.2             | [樱(玩法类)]Sakura-1.0.7-1.12.2.jar                                         | None                                     |
	| LC    | dtsakuracompact          | 1.0                      | [动态的树之樱附属(玩法类)]Dynamictrees-sakura-compact-1.12.2-1.4.0.3-universal.jar | None                                     |
	| LC    | baubles                  | 1.5.2                    | [饰品栏(玩法类)]Baubles-1.12-1.5.2.jar                                        | None                                     |
	| LC    | defiledlands             | 1.4.3                    | [污秽之地(玩法类)]defiledlands-1.12.2-1.4.3.jar                                | None                                     |
	| LC    | dynamictreesdefiledlands | 1.12.2-1.0.0             | [动态的树之污秽之地(玩法类)]dynamictreesdefiledlands-1.12.2-1.0.0.jar               | None                                     |
	| LC    | animalium                | 0.3.8                    | [动物(玩法类)]Animalium-0.3.8.jar                                            | None                                     |
	| LC    | firstaid                 | 1.6.22                   | [医疗护理(玩法类)]firstaid-1.6.22.jar                                          | 7904c4e13947c8a616c5f39b26bdeba796500722 |
	| LC    | compactsolars            | 1.12.2-5.0.18.341        | [压缩太阳能阵列(玩法类)]CompactSolars-1.12.2-5.0.18.341-universal.jar             | None                                     |
	| LC    | geckolib3                | 3.0.30                   | [变色龙(核心类)]geckolib-forge-1.12.2-3.0.31.jar                              | None                                     |
	| LC    | codechickenlib           | 3.2.3.358                | [鸡块(核心类)]CodeChickenLib-1.12.2-3.2.3.358-universal.jar                  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | ancientwarfare           | 1.12.2-2.9.13            | [古代战争2(玩法类)]ancientwarfare-1.12.2-2.9.13.jar                            | None                                     |
	| LC    | ancientwarfareautomation | 1.12.2-2.9.13            | [古代战争2(玩法类)]ancientwarfare-1.12.2-2.9.13.jar                            | None                                     |
	| LC    | ancientwarfarenpc        | 1.12.2-2.9.13            | [古代战争2(玩法类)]ancientwarfare-1.12.2-2.9.13.jar                            | None                                     |
	| LC    | ancientwarfarestructure  | 1.12.2-2.9.13            | [古代战争2(玩法类)]ancientwarfare-1.12.2-2.9.13.jar                            | None                                     |
	| LC    | ancientwarfarevehicle    | 1.12.2-2.9.13            | [古代战争2(玩法类)]ancientwarfare-1.12.2-2.9.13.jar                            | None                                     |
	| LC    | fluidlogged_api          | 2.2.7                    | [含水方块(玩法类)]Fluidlogged-API-v2.2.7-mc1.12.2.jar                          | None                                     |
	| LC    | entityculling            | @VER@                    | [实体渲染机制优化(优化类)]entityculling-1.12.2-1.6.3.jar                           | None                                     |
	| LC    | configex                 | 1.0                      | [局部气候重置版(玩法类)]Weather2Remastered-1.12.2-2.8.17.jar                      | None                                     |
	| LC    | weather2remaster         | 2.8.16                   | [局部气候重置版(玩法类)]Weather2Remastered-1.12.2-2.8.17.jar                      | None                                     |
	| LC    | patchouli                | 1.0-23.6                 | [帕秋莉手册(核心类)]Patchouli-1.0-23.6.jar                                      | None                                     |
	| LC    | openmodularturrets       | 3.1.14-382               | [开放式炮台(玩法类)]openmodularturrets-1.12.2-3.1.14-382.jar                    | None                                     |
	| LC    | ompd                     | 3.1.1-76                 | [开放式防御(玩法类)]ompd-1.12.2-3.1.1-76.jar                                    | None                                     |
	| LC    | pillagers                | 1.0.6                    | [我是掠夺者(玩法类)]Pillagers-1.12.2-1.0.6.jar                                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | flammpfeil.slashblade    | mc1.12-r33               | [拔刀剑(玩法类)]SlashBlade-mc1.12-r33.jar                                     | None                                     |
	| LC    | slashblade_addon         | 1.6.0                    | [拔刀剑日系附属(玩法类)]SJAP-1.6.0.jar                                            | None                                     |
	| LC    | harvestersnight          | 1.1.0                    | [收割之夜(玩法类)]harvestersnight-1.12.2-1.1.0.jar                             | None                                     |
	| LC    | hw_inv                   | 1.12.1-1.1.13            | [敌对世界-入侵(玩法类)]hostileworlds_invasions-1.12.1-1.1.13.jar                 | None                                     |
	| LC    | lunatriuscore            | 1.2.0.42                 | [显示核心(核心类)]LunatriusCore-1.12.2-1.2.0.42-universal.jar                  | None                                     |
	| LC    | llibrary                 | 1.7.20                   | [前置库(核心类)]llibrary-1.7.20-1.12.2.jar                                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LC    | mowziesmobs              | 1.5.8                    | [更多BOSS(玩法类)]mowziesmobs_1.12.2_1.5.8.jar                               | None                                     |
	| LC    | illagers_plus            | 1.1                      | [更多灾厄村民(玩法类)]IllagersPlus-1.12.2-1.1.3.jar                              | None                                     |
	| LC    | bettercombatmod          | 1.5.6                    | [更好的战斗(玩法类)]BetterCombat-1.12.2-1.5.6.jar                               | None                                     |
	| LC    | bettercaves              | 1.12.2                   | [更好的洞穴(玩法类)]bettercaves-1.12.2-2.0.4.jar                                | None                                     |
	| LC    | betterbiomeblend         | 1.12.2-1.1.7-forge       | [更好的生物群系过渡(优化类)]betterbiomeblend-1.12.2-1.1.7-forge.jar                 | None                                     |
	| LC    | bettermineshafts         | 1.12.2-2.2.1             | [更好的矿井(玩法类)]BetterMineshaftsForge-1.12.2-2.2.1.jar                      | None                                     |
	| LC    | lastsmith                | 2.1.8-1.12.2             | [最后的太刀匠人(玩法类)]TLS-2.1.8-1.12.2.jar                                      | None                                     |
	| LC    | ee                       | 0.1.1                    | [最终目标(玩法类)]Into The End - 1.1.jar                                       | None                                     |
	| LC    | fd                       | 1.2.5                    | [未来装饰(玩法类)]FutureDecoration-1.12.2-1.6.4.jar                            | None                                     |
	| LC    | texfix                   | 4.0                      | [材质修复(优化类)]TexFix V-1.12-4.0.jar                                        | None                                     |
	| LC    | fugue                    | 1.12.2-0.16.3            | [模组兼容性优化(核心类)]+Fugue-1.12.2-0.16.3.jar                                  | None                                     |
	| LC    | aquaacrobatics           | 1.15.4                   | [水游技艺(玩法类)]AquaAcrobatics-1.15.4.jar                                    | None                                     |
	| LC    | foamfix                  | @VERSION@                | [泡沫修复(优化类)]foamfix-0.10.15-1.12.2.jar                                   | None                                     |
	| LC    | oe                       | 1.1.4                    | [海洋扩展(玩法类)]OceanicExpanse-1.1.4.jar                                     | None                                     |
	| LC    | eyesinthedarkness        | 0.1.0                    | [深夜的眼睛(玩法类)]EyesInTheDarkness-0.1.0.jar                                 | None                                     |
	| LC    | db                       | 0.0.1                    | [深海怪物(玩法类)]The Depths of Madness - 0.1.jar                              | None                                     |
	| LC    | ingameinfoxml            | 2.8.2.94                 | [游戏内信息显示(辅助类)]InGameInfoXML-1.12.2-2.8.2.94-universal.jar               | None                                     |
	| LC    | alfheim                  | 1.4                      | [照明优化(优化类)]Alfheim-1.4.jar                                              | None                                     |
	| LC    | specialai                | 1.1.0_for_mc1.12.2       | [特殊AI(玩法类)]specialai-1.1.0_for_mc1.12.2.jar                             | None                                     |
	| LC    | exoticbirds              | 1.0                      | [珍奇鸟类(玩法类)]Exotic Birds 1.12.2-3.2.0.jar                                | None                                     |
	| LC    | grimoireofgaia           | 1.7.2                    | [盖亚魔典3(玩法类)]GrimoireOfGaia3-1.12.2-1.7.2.jar                            | None                                     |
	| LC    | techguns                 | 2.0.2.0                  | [科技枪(玩法类)]techguns-1.12.2-2.0.2.0_pre3.2.jar                            | None                                     |
	| LC    | itemborders              | 1.2.0                    | [稀有物品标识(辅助类)]ItemBorders-1.12.2-forge-1.2.0.jar                         | None                                     |
	| LC    | particleculling          | v1.4.3                   | [粒子剔除(优化类)]particleculling-1.12.2-v1.4.3.jar                            | None                                     |
	| LC    | refinedstorage           | 2.3.2                    | [精致储存重置(玩法类)]morerefinedstorage-2.3.2.jar                               | None                                     |
	| LC    | paperfixes               | 1.3.0                    | [纸的修复(优化类)]PaperFixes-1.3.0.jar                                         | None                                     |
	| LC    | wings                    | 1.1.6                    | [翅膀(玩法类)]wings-1.1.6-1.12.2.jar                                         | None                                     |
	| LC    | mowzies_wings            | 1.0.0                    | [翅膀(玩法类)]wings-1.1.6-1.12.2.jar                                         | None                                     |
	| LC    | bauble_wings             | 1.0.0                    | [翅膀(玩法类)]wings-1.1.6-1.12.2.jar                                         | None                                     |
	| LC    | armorstatushud           | 1.30                     | [耐久信息显示(辅助类)][1.12.2] Armor Status HUD v1.3.0.jar                       | None                                     |
	| LC    | dmonsters                | 1.12.2-1.9.5             | [致命怪物重置版(玩法类)]DeadlyMonsters-1.12.2-1.9.5.jar                           | None                                     |
	| LC    | appleskin                | 1.0.14                   | [苹果皮(辅助类)]AppleSkin-mc1.12-1.0.14.jar                                   | None                                     |
	| LC    | da                       | 0.0.5                    | [虚空之花(玩法类)]Into The Dungeons - 0.5.jar                                  | None                                     |
	| LC    | creepypastacraft         | 2                        | [蠕动意面(玩法类)]CreepyPastaCraft_Reborn_V2c-1.12.2-hotfix1.jar               | None                                     |
	| LC    | enhancedvisuals          | 1.3.0                    | [视觉效果增强(玩法类)]EnhancedVisuals_v1.4.4_mc1.12.2.jar                        | None                                     |
	| LC    | progressivebosses        | 1.5.4                    | [进化Boss(玩法类)]ProgressiveBosses-1.5.4-mc1.12.x.jar                       | None                                     |
	| LC    | waila                    | 1.8.26                   | [高亮显示(辅助类)]Hwyla-1.8.26-B41_1.12.2.jar                                  | None                                     |
	| LC    | universaltweaks          | 1.12.0                   | [通用修改(优化类)]UniversalTweaks-1.12.2-1.12.0.jar                            | None                                     |
	| LC    | wailaharvestability      | 1.1.12                   | [高亮显示附属(辅助类)]WailaHarvestability-mc1.12-1.1.12.jar                      | None                                     |
	| LC    | wawla                    | 2.6.275                  | [高亮显示附属(辅助类)]Wawla-1.12.2-2.6.275.jar                                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | birdsnests               | 2.1.0                    | [鸟巢(玩法类)]BirdsNests1.12.2-2.1.0.jar                                     | None                                     |
	| LC    | dragonmounts             | 1.12.2-1.6.4             | [龙骑士3(玩法类)]DragonMounts3-1.12.2-1.6.4.jar                               | None                                     |
	| LC    | midnight                 | 0.3.5                    | [午夜(玩法类)]themidnight-0.3.5.jar                                          | None                                     |
	| UD    | scalar                   | 2.11.1-2                 | minecraft.jar                                                           | None                                     |
	| UD    | mobends_wings            | 1.0.0                    | [翅膀(玩法类)]wings-1.1.6-1.12.2.jar                                         | None                                     |

### MMC Instance Notes

no

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Add `nuparu.sevendaystomine.proxy.CommonProxy` to javax list in fugue.cfg
