### ISSUE TITLE
Crash with UpAndDownAndAllAround

### ISSUE THREAD

**Issue by XZYawa** [CleanroomMC/Cleanroom#228]
### Your CleanroomMC Discord Username

xzy9262

### Cleanroom Version

717

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

[latest.log](https://github.com/user-attachments/files/17444603/latest.log)

### Mod List

UpAndDownAndAllAround-1.12.2-2.9.1
+Fugue-1.12.2-0.16.3
scalar-1.12.2-2.11.1

### MMC Instance Notes

\

(关于上回的"noumenon":我是看rong只给少数几个issue打了标签,还以为这些是要放在本体里修的意思......)

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Try this fork
https://legacy.curseforge.com/minecraft/mc-mods/up-and-down-and-everything

**Comment by kappa-maintainer** [comment]
I will update it then

**Comment by kappa-maintainer** [comment]
[gravitymod-2.11.0.zip](https://github.com/user-attachments/files/17632059/gravitymod-2.11.0.zip)
Try this build

**Comment by XZYawa** [comment]
> [gravitymod-2.11.0.zip](https://github.com/user-attachments/files/17632059/gravitymod-2.11.0.zip) Try this build

Still crashed,seems......
[latest.log](https://github.com/user-attachments/files/17679063/latest.log)

**Comment by kappa-maintainer** [comment]
That's a new crash
Try this one
[gravitymod-2.11.0.zip](https://github.com/user-attachments/files/17679110/gravitymod-2.11.0.zip)

**Comment by XZYawa** [comment]
> That's a new crash Try this one [gravitymod-2.11.0.zip](https://github.com/user-attachments/files/17679110/gravitymod-2.11.0.zip)

Now it works fine,thanks!
(But still crashed with some mods in my pack,I will test them later......)
(And all textures are missing,but I think this is intentional?)

**Comment by XZYawa** [comment]
> That's a new crash Try this one [gravitymod-2.11.0.zip](https://github.com/user-attachments/files/17679110/gravitymod-2.11.0.zip)

Conflict with AquaAcrobatics.
> [latest.log](https://github.com/user-attachments/files/17686215/latest.log)

(kappa-maintainer/Up_And_Down_And_All_Around的issue没开,还是先发在这儿吧)

**Comment by kappa-maintainer** [comment]
开了，乖乖发那边去
