### ISSUE TITLE
crash with HuajiAge

### ISSUE THREAD

**Issue by DALENER** [CleanroomMC/Cleanroom#229]
### Cleanroom Version

0.2.3α

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

https://mclo.gs/Swn3jTn

### Mod List

[HuajiAge-InfiniteGalaxy-1.12.2-1.3.5.1](https://github.com/DragonGodSUN/HuajiAge)

### MMC Instance Notes

\

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Wrong scalar version, use 2.11.1
