### ISSUE TITLE
Crash with Dimstorage

### ISSUE THREAD

**Issue by ttt000000000000** [CleanroomMC/Cleanroom#230]
### Cleanroom Version

0.2.3-alpha+build.25.run.728

### Java Version

Java 21

### Graphics Card Vendor

Other (Please Specify)

### Bug Report

https://mclo.gs/XiobyeW

### Mod List

+Fugue-1.12.2-0.16.3
DimStorage-1.12.2-1.3.0
scalar-1.12.2-2.11.1-2

### MMC Instance Notes

no

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by ttt000000000000** [comment]
The same error occurred in Forge

**Comment by kappa-maintainer** [comment]
So that's not a Cleanroom problem
In theory, you can fix that by installing OpenComputers
