### ISSUE TITLE
Cannot Launch with Resonant Rise 5

### ISSUE THREAD

**Issue by Frankiscophil** [CleanroomMC/Cleanroom#232]
### Cleanroom Version

0.2.3-alpha+build.28.run.754

### Java Version

Java 21

### Graphics Card Vendor

Intel iGPU

### Bug Report

**Log:** https://mclo.gs/VgYQewJ
**Crash Report:** https://mclo.gs/ZpB7dHB

### Mod List

	| State | ID                                | Version                  | Source                                               | Signature                                |
	|:----- |:--------------------------------- |:------------------------ |:---------------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft                         | 1.12.2                   | minecraft.jar                                        | None                                     |
	| LC    | mcp                               | 9.42                     | minecraft.jar                                        | None                                     |
	| LC    | configanytime                     | 3.0                      | cleanroom-0.2.3-alpha+build.28.run.754-universal.jar | None                                     |
	| LC    | cleanroom                         | 0.2.3-alpha              | cleanroom-0.2.3-alpha+build.28.run.754-universal.jar | None                                     |
	| LC    | FML                               | 8.0.99.99                | cleanroom-0.2.3-alpha+build.28.run.754-universal.jar | None                                     |
	| LC    | forge                             | 14.23.5.2860             | cleanroom-0.2.3-alpha+build.28.run.754-universal.jar | None                                     |
	| LC    | xaerominimap_core                 | 1.12.2-1.0               | minecraft.jar                                        | None                                     |
	| LC    | mixinbooter                       | 10.0                     | cleanroom-0.2.3-alpha+build.28.run.754-universal.jar | None                                     |
	| LC    | openmodscore                      | 0.12.2                   | minecraft.jar                                        | None                                     |
	| LC    | foamfixcore                       | 7.7.4                    | minecraft.jar                                        | None                                     |
	| LC    | opencomputers|core                | 1.7.5.192                | minecraft.jar                                        | None                                     |
	| LC    | randompatches                     | 1.12.2-1.21.0.3          | randompatches-1.12.2-1.21.0.3.jar                    | None                                     |
	| LC    | gottagofast                       | 1.1                      | gottagofast-1.1.jar                                  | None                                     |
	| LC    | fugue                             | 1.12.2-0.16.4            | +Fugue-1.12.2-0.16.4.jar                             | None                                     |
	| LC    | fastbench                         | 1.7.3                    | FastWorkbench-1.12.2-1.7.3.jar                       | None                                     |
	| LC    | actuallyadditions                 | 1.12.2-r151              | ActuallyAdditions-1.12.2-r151-2.jar                  | None                                     |
	| LC    | ctm                               | MC1.12.2-1.0.2.31        | CTM-MC1.12.2-1.0.2.31.jar                            | None                                     |
	| LC    | appliedenergistics2               | rv6-stable-7             | appliedenergistics2-rv6-stable-7.jar                 | None                                     |
	| LC    | bdlib                             | 1.14.3.12                | bdlib-1.14.3.12-mc1.12.2.jar                         | None                                     |
	| LC    | ae2stuff                          | 0.7.0.4                  | ae2stuff-0.7.0.4-mc1.12.2.jar                        | None                                     |
	| LC    | baubles                           | 1.5.2                    | Baubles-1.12-1.5.2.jar                               | None                                     |
	| LC    | endercore                         | 1.12.2-0.5.76            | EnderCore-1.12.2-0.5.76.jar                          | None                                     |
	| LC    | crafttweaker                      | 4.1.20                   | CraftTweaker2-1.12-4.1.20.576.jar                    | None                                     |
	| LC    | endertweaker                      | 1.2.0                    | EnderTweaker-1.12.2-1.2.0.jar                        | None                                     |
	| LC    | mtlib                             | 3.0.6                    | MTLib-3.0.6.jar                                      | None                                     |
	| LC    | modtweaker                        | 4.0.18                   | modtweaker-4.0.18.jar                                | None                                     |
	| LC    | jei                               | 4.15.0.293               | jei_1.12.2-4.15.0.293.jar                            | None                                     |
	| LC    | codechickenlib                    | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | redstoneflux                      | 2.1.1                    | RedstoneFlux-1.12-2.1.1.1-universal.jar              | None                                     |
	| LC    | cofhcore                          | 4.6.6                    | CoFHCore-1.12.2-4.6.6.1-universal.jar                | None                                     |
	| LC    | brandonscore                      | 2.4.18                   | BrandonsCore-1.12.2-2.4.18.210-universal.jar         | None                                     |
	| L     | cofhworld                         | 1.4.0                    | CoFHWorld-1.12.2-1.4.0.1-universal.jar               | None                                     |
	| L     | thermalfoundation                 | 2.6.7                    | ThermalFoundation-1.12.2-2.6.7.1-universal.jar       | None                                     |
	| L     | draconicevolution                 | 2.3.25                   | Draconic-Evolution-1.12.2-2.3.25.351-universal.jar   | None                                     |
	| L     | thermalexpansion                  | 5.5.7                    | ThermalExpansion-1.12.2-5.5.7.1-universal.jar        | None                                     |
	| L     | enderio                           | 5.2.57                   | EnderIO-1.12.2-5.2.57.jar                            | None                                     |
	| L     | mantle                            | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                             | None                                     |
	| L     | chisel                            | MC1.12.2-1.0.2.45        | Chisel-MC1.12.2-1.0.2.45.jar                         | None                                     |
	| L     | enderiointegrationtic             | 5.2.57                   | EnderIO-1.12.2-5.2.57.jar                            | None                                     |
	| L     | twilightforest                    | 3.10.1013                | twilightforest-1.12.2-3.10.1013-universal.jar        | None                                     |
	| L     | tconstruct                        | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar                     | None                                     |
	| L     | p455w0rdslib                      | 2.3.161                  | p455w0rdslib-1.12.2-2.3.161.jar                      | None                                     |
	| L     | ae2wtlib                          | 1.0.34                   | AE2WTLib-1.12.2-1.0.34.jar                           | None                                     |
	| L     | akashictome                       | 1.2-12                   | AkashicTome-1.2-12.jar                               | None                                     |
	| L     | anvilfix                          | 1.0.5                    | AnvilFix-1.12.2-1.0.5.jar                            | None                                     |
	| L     | appleskin                         | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                           | None                                     |
	| L     | artifacts                         | 1.12.2-1.1.0             | Artifacts-1.12.2-1.1.0.jar                           | None                                     |
	| L     | astralsorcery                     | 1.10.22                  | astralsorcery-1.12.2-1.10.24.jar                     | None                                     |
	| L     | morphtool                         | 1.2-21                   | Morph-o-Tool-1.2-21.jar                              | None                                     |
	| L     | autoreglib                        | 1.3-32                   | AutoRegLib-1.3-32.jar                                | None                                     |
	| L     | base                              | 3.13.0                   | base-1.12.2-3.13.0.jar                               | None                                     |
	| L     | bibliocraft                       | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar                    | None                                     |
	| L     | blockcraftery                     | 1.12.2-1.3.1             | blockcraftery-1.12.2-1.3.1.jar                       | None                                     |
	| L     | guideapi                          | 1.12-2.1.8-63            | Guide-API-1.12-2.1.8-63.jar                          | None                                     |
	| L     | bloodmagic                        | 1.12.2-2.4.3-105         | BloodMagic-1.12.2-2.4.3-105.jar                      | None                                     |
	| L     | bonsaitrees                       | 1.1.4                    | bonsaitrees-1.1.4-b170.jar                           | None                                     |
	| L     | bookshelf                         | 2.3.590                  | Bookshelf-1.12.2-2.3.590.jar                         | None                                     |
	| L     | botania                           | r1.10-363                | Botaniar1.10-363.jar                                 | None                                     |
	| L     | buildcraftlib                     | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                         | None                                     |
	| L     | buildcraftcore                    | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                         | None                                     |
	| L     | buildcraftbuilders                | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                         | None                                     |
	| L     | buildcrafttransport               | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                         | None                                     |
	| L     | buildcraftsilicon                 | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                         | None                                     |
	| L     | buildcraftenergy                  | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                         | None                                     |
	| L     | natura                            | 1.12.2-4.3.2.69          | natura-1.12.2-4.3.2.69.jar                           | None                                     |
	| L     | reborncore                        | 3.19.4.529               | RebornCore-1.12.2-3.19.4.529-universal.jar           | None                                     |
	| L     | techreborn                        | 2.27.3.1084              | TechReborn-1.12.2-2.27.3.1084-universal.jar          | None                                     |
	| L     | forestry                          | 5.8.2.422                | forestry_1.12.2-5.8.2.422.jar                        | None                                     |
	| L     | theoneprobe                       | 1.4.28                   | theoneprobe-1.12-1.4.28.jar                          | None                                     |
	| L     | buildcraftcompat                  | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                         | None                                     |
	| L     | buildcraftfactory                 | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                         | None                                     |
	| L     | buildcraftrobotics                | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                         | None                                     |
	| L     | buildinggadgets                   | 2.8.3                    | BuildingGadgets-2.8.3.jar                            | None                                     |
	| L     | chameleon                         | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                             | None                                     |
	| L     | chickenchunks                     | 2.4.2.74                 | ChickenChunks-1.12.2-2.4.2.74-universal.jar          | None                                     |
	| L     | chiselsandbits                    | 14.33                    | chiselsandbits-14.33.jar                             | None                                     |
	| L     | forgelin                          | 1.8.4                    | Forgelin-1.8.4.jar                                   | None                                     |
	| L     | librarianlib                      | 4.20                     | librarianlib-1.12.2-4.20-release.jar                 | None                                     |
	| L     | classyhats                        | %VERSION%                | ClassyHats-1.5.jar                                   | None                                     |
	| L     | clumps                            | 3.1.2                    | Clumps-3.1.2.jar                                     | None                                     |
	| L     | comforts                          | 1.4.1.3                  | comforts-1.12.2-1.4.1.3.jar                          | None                                     |
	| L     | cyclopscore                       | 1.6.4                    | CyclopsCore-1.12.2-1.6.4.jar                         | None                                     |
	| L     | commoncapabilities                | 2.4.6                    | CommonCapabilities-1.12.2-2.4.6.jar                  | None                                     |
	| L     | compacter                         | 1.3.0.3                  | compacter-1.3.0.3-mc1.12.2.jar                       | None                                     |
	| L     | conarm                            | 1.2.5.9                  | conarm-1.12.2-1.2.5.9.jar                            | None                                     |
	| L     | controlling                       | 3.0.9                    | Controlling-3.0.9.jar                                | None                                     |
	| L     | cookingforblockheads              | 6.5.0                    | CookingForBlockheads_1.12.2-6.5.0.jar                | None                                     |
	| L     | cosmeticarmorreworked             | 1.12.2-v5a               | CosmeticArmorReworked-1.12.2-v5a.jar                 | None                                     |
	| L     | ctgui                             | 1.0.0                    | CraftTweaker2-1.12-4.1.20.576.jar                    | None                                     |
	| L     | crafttweakerjei                   | 2.0.3                    | CraftTweaker2-1.12-4.1.20.576.jar                    | None                                     |
	| L     | cucumber                          | 1.1.3                    | Cucumber-1.12.2-1.1.3.jar                            | None                                     |
	| L     | custommainmenu                    | 2.0.9.1                  | CustomMainMenu-MC1.12.2-2.0.9.1.jar                  | None                                     |
	| L     | darkutils                         | 1.8.230                  | DarkUtils-1.12.2-1.8.230.jar                         | None                                     |
	| L     | eleccore                          | 1.9.453                  | ElecCore-1.12.2-1.9.453.jar                          | None                                     |
	| L     | mcjtylib_ng                       | 3.5.4                    | mcjtylib-1.12-3.5.4.jar                              | None                                     |
	| L     | opencomputers                     | 1.7.5.192                | OpenComputers-MC1.12.2-1.7.5.192.jar                 | None                                     |
	| L     | rftools                           | 7.73                     | rftools-1.12-7.73.jar                                | None                                     |
	| L     | deepresonance                     | 1.8.0                    | deepresonance-1.12-1.8.0.jar                         | None                                     |
	| L     | discordsuite                      | 2.2.4                    | DiscordSuite-2.2.4.jar                               | None                                     |
	| L     | dyndyn                            | 1.12.2-1.10              | DynamicDynamos-1.12.2-1.10.jar                       | None                                     |
	| L     | effortlessbuilding                | 1.12.2-2.16              | effortlessbuilding-1.12.2-2.16.jar                   | None                                     |
	| L     | enderiobase                       | 5.2.57                   | EnderIO-1.12.2-5.2.57.jar                            | None                                     |
	| L     | enderioconduits                   | 5.2.57                   | EnderIO-1.12.2-5.2.57.jar                            | None                                     |
	| L     | enderioconduitsappliedenergistics | 5.2.57                   | EnderIO-1.12.2-5.2.57.jar                            | None                                     |
	| L     | enderioconduitsopencomputers      | 5.2.57                   | EnderIO-1.12.2-5.2.57.jar                            | None                                     |
	| L     | enderioconduitsrefinedstorage     | 5.2.57                   | EnderIO-1.12.2-5.2.57.jar                            | None                                     |
	| L     | enderiointegrationforestry        | 5.2.57                   | EnderIO-1.12.2-5.2.57.jar                            | None                                     |
	| L     | enderiointegrationticlate         | 5.2.57                   | EnderIO-1.12.2-5.2.57.jar                            | None                                     |
	| L     | ftblib                            | 5.4.7.2                  | FTBLib-5.4.7.2.jar                                   | None                                     |
	| L     | enderiomachines                   | 5.2.57                   | EnderIO-1.12.2-5.2.57.jar                            | None                                     |
	| L     | enderiopowertools                 | 5.2.57                   | EnderIO-1.12.2-5.2.57.jar                            | None                                     |
	| L     | enderioendergy                    | 5.2.57                   | EnderIO-endergy-1.12.2-5.2.57.jar                    | None                                     |
	| L     | enderiozoo                        | 5.2.57                   | EnderIO-zoo-1.12.2-5.2.57.jar                        | None                                     |
	| L     | enderstorage                      | 2.4.6.137                | EnderStorage-1.12.2-2.4.6.137-universal.jar          | None                                     |
	| L     | valkyrielib                       | 1.12.2-2.0.20.1          | valkyrielib-1.12.2-2.0.20.1.jar                      | None                                     |
	| L     | environmentaltech                 | 1.12.2-2.0.20.1          | environmentaltech-1.12.2-2.0.20.1.jar                | None                                     |
	| L     | etlunar                           | 1.12.2-2.0.20.1          | etlunar-1.12.2-2.0.20.1.jar                          | None                                     |
	| L     | gunpowderlib                      | 1.12.2-1.0               | GunpowderLib-1.12.2-1.0.jar                          | None                                     |
	| L     | mcmultipart                       | 2.5.3                    | MCMultiPart-2.5.3.jar                                | None                                     |
	| L     | mekanism                          | 1.12.2-9.8.3.390         | Mekanism-1.12.2-9.8.3.390.jar                        | None                                     |
	| L     | immersiveengineering              | 0.12-98                  | ImmersiveEngineering-0.12-98.jar                     | None                                     |
	| L     | exchangers                        | 1.12.2-2.9               | Exchangers-1.12.2-2.9.jar                            | None                                     |
	| L     | extracells                        | 2.6.5                    | ExtraCells-1.12.2-2.6.5.jar                          | None                                     |
	| L     | extrautils2                       | 1.0                      | extrautils2-1.12-1.9.9.jar                           | None                                     |
	| L     | zerocore                          | 1.12.2-0.1.2.8           | zerocore-1.12.2-0.1.2.8.jar                          | None                                     |
	| L     | bigreactors                       | 1.12.2-0.4.5.67          | ExtremeReactors-1.12.2-0.4.5.67.jar                  | None                                     |
	| L     | fastfurnace                       | 1.3.1                    | FastFurnace-1.12.2-1.3.1.jar                         | None                                     |
	| L     | sonarcore                         | 5.0.19                   | sonarcore-1.12.2-5.0.19-20.jar                       | None                                     |
	| L     | fluxnetworks                      | 4.0.14                   | fluxnetworks-1.12.2-4.0.14-31.jar                    | None                                     |
	| L     | foamfix                           | 0.10.10-1.12.2           | foamfix-0.10.10-1.12.2.jar                           | None                                     |
	| L     | forgemultipartcbe                 | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar         | None                                     |
	| L     | microblockcbe                     | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar         | None                                     |
	| L     | minecraftmultipartcbe             | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar         | None                                     |
	| L     | ftbbackups                        | 1.1.0.1                  | FTBBackups-1.1.0.1.jar                               | None                                     |
	| L     | ftbutilities                      | 5.4.1.128                | FTBUtilities-5.4.1.128.jar                           | None                                     |
	| L     | gendustry                         | 1.6.5.8                  | gendustry-1.6.5.8-mc1.12.2.jar                       | None                                     |
	| L     | advgenerators                     | 0.9.20.12                | generators-0.9.20.12-mc1.12.2.jar                    | None                                     |
	| L     | ichunutil                         | 7.2.2                    | iChunUtil-1.12.2-7.2.2.jar                           | None                                     |
	| L     | immersivepetroleum                | 1.1.9                    | immersivepetroleum-1.12.2-1.1.9.jar                  | None                                     |
	| L     | immersivetech                     | 1.3.10                   | immersivetech-1.12-1.3.10.jar                        | None                                     |
	| L     | teslacorelib                      | 1.0.17                   | tesla-core-lib-1.12.2-1.0.17.jar                     | None                                     |
	| L     | industrialforegoing               | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.12.13-237.jar           | None                                     |
	| L     | integrateddynamics                | 1.1.6                    | IntegratedDynamics-1.12.2-1.1.6.jar                  | None                                     |
	| L     | integratedcrafting                | 1.0.9                    | IntegratedCrafting-1.12.2-1.0.9.jar                  | None                                     |
	| L     | integrateddynamicscompat          | 1.0.0                    | IntegratedDynamics-1.12.2-1.1.6.jar                  | None                                     |
	| L     | integratedterminals               | 1.0.13                   | IntegratedTerminals-1.12.2-1.0.13.jar                | None                                     |
	| L     | integratedterminalscompat         | 1.0.0                    | IntegratedTerminals-1.12.2-1.0.13.jar                | None                                     |
	| L     | integratedtunnels                 | 1.6.11                   | IntegratedTunnels-1.12.2-1.6.11.jar                  | None                                     |
	| L     | integratedtunnelscompat           | 1.0.0                    | IntegratedTunnels-1.12.2-1.6.11.jar                  | None                                     |
	| L     | mysticalagriculture               | 1.7.5                    | MysticalAgriculture-1.12.2-1.7.5.jar                 | None                                     |
	| L     | mysticalagradditions              | 1.3.2                    | MysticalAgradditions-1.12.2-1.3.2.jar                | None                                     |
	| L     | randomthings                      | 4.2.7.4                  | RandomThings-MC1.12.2-4.2.7.4.jar                    | None                                     |
	| L     | matteroverdrive                   | 0.7.0.0                  | MatterOverdrive-1.12.2-0.7.1.0-universal.jar         | None                                     |
	| L     | integrationforegoing              | 1.12.2-1.10              | IntegrationForegoing-1.12.2-1.10.jar                 | None                                     |
	| L     | inventorytweaks                   | 1.64+dev.151.822d839     | InventoryTweaks-1.64dev.151.jar                      | None                                     |
	| L     | ironbackpacks                     | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar                    | None                                     |
	| L     | jaopca                            | 1.12.2-2.2.8.103         | JAOPCA-1.12.2-2.2.8.103.jar                          | None                                     |
	| L     | oredictinit                       | 1.12.2-2.2.1.71          | JAOPCA-1.12.2-2.2.8.103.jar                          | None                                     |
	| L     | jeibees                           | 0.9.0.5                  | jeibees-0.9.0.5-mc1.12.2.jar                         | None                                     |
	| L     | jee                               | 1.0.8                    | JustEnoughEnergistics-1.12.2-1.0.8.jar               | None                                     |
	| L     | jeresources                       | 0.9.2.60                 | JustEnoughResources-1.12.2-0.9.2.60.jar              | None                                     |
	| L     | keywizard                         | 1.12.2-1.7.3             | keywizard-1.12.2-1.7.3.jar                           | None                                     |
	| L     | lostcities                        | 2.0.21                   | lostcities-1.12-2.0.21.jar                           | None                                     |
	| L     | lostquiver                        | 1.0 - MC 1.12.2          | lostquiver-1.0.jar                                   | None                                     |
	| L     | lostsouls                         | 1.1.4                    | lostsouls-1.12-1.1.4.jar                             | None                                     |
	| L     | psi                               | r1.1-78                  | Psi-r1.1-78.jar                                      | None                                     |
	| L     | magipsi                           | 1.3                      | MagicalPsi-1.3.2.jar                                 | None                                     |
	| L     | mekanismgenerators                | 1.12.2-9.8.3.390         | MekanismGenerators-1.12.2-9.8.3.390.jar              | None                                     |
	| L     | minemenu                          | 1.6.11                   | MineMenu-1.12.2-1.6.11-universal.jar                 | None                                     |
	| L     | mob_grinding_utils                | 0.3.13                   | MobGrindingUtils-0.3.13.jar                          | None                                     |
	| L     | modnametooltip                    | 1.10.1                   | modnametooltip_1.12.2-1.10.1.jar                     | None                                     |
	| L     | numina                            | 1.12.2-1.0.38            | Numina-1.12.2-1.0.38.jar                             | None                                     |
	| L     | powersuits                        | 1.12.2-1.0.46            | ModularPowersuits-1.12.2-1.0.46.jar                  | None                                     |
	| L     | morebees                          | 1.12.2-2.0.1             | morebees-1.12.2-2.0.1.jar                            | None                                     |
	| L     | morph                             | 7.2.0                    | Morph-1.12.2-7.2.0.jar                               | None                                     |
	| L     | mousetweaks                       | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                        | None                                     |
	| L     | mrtjpcore                         | 2.1.4.43                 | MrTJPCore-1.12.2-2.1.4.43-universal.jar              | None                                     |
	| L     | multimob                          | 1.0.5                    | multimob-1.0.5.jar                                   | None                                     |
	| L     | neat                              | 1.4-17                   | Neat1.4-17.jar                                       | None                                     |
	| L     | xnet                              | 1.8.2                    | xnet-1.12-1.8.2.jar                                  | None                                     |
	| L     | ocxnetdriver                      | 1.0.3                    | ocxnetdriver-1.0.3-b17.jar                           | None                                     |
	| L     | openmods                          | 0.12.2                   | OpenModsLib-1.12.2-0.12.2.jar                        | None                                     |
	| L     | openblocks                        | 1.8.1                    | OpenBlocks-1.12.2-1.8.1.jar                          | None                                     |
	| L     | oreexcavation                     | 1.4.150                  | OreExcavation-1.4.150.jar                            | None                                     |
	| L     | placebo                           | 1.6.0                    | Placebo-1.12.2-1.6.0.jar                             | None                                     |
	| L     | primitivemobs                     | 1.2.3a                   | primitivemobs-1.2.3a.jar                             | None                                     |
	| L     | projectintelligence               | 1.0.9                    | ProjectIntelligence-1.12.2-1.0.9.28-universal.jar    | None                                     |
	| L     | projectred-core                   | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-Base.jar                 | None                                     |
	| L     | projectred-compat                 | 1.0                      | ProjectRed-1.12.2-4.9.4.120-compat.jar               | None                                     |
	| L     | projectred-integration            | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-integration.jar          | None                                     |
	| L     | projectred-transmission           | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-integration.jar          | None                                     |
	| L     | projectred-fabrication            | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-fabrication.jar          | None                                     |
	| L     | projectred-illumination           | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-lighting.jar             | None                                     |
	| L     | projectred-expansion              | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-mechanical.jar           | None                                     |
	| L     | projectred-relocation             | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-mechanical.jar           | None                                     |
	| L     | projectred-transportation         | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-mechanical.jar           | None                                     |
	| L     | projectred-exploration            | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-world.jar                | None                                     |
	| L     | quantumstorage                    | 4.7.0                    | QuantumStorage-1.12-4.7.0.jar                        | None                                     |
	| L     | redstonearsenal                   | 2.6.6                    | RedstoneArsenal-1.12.2-2.6.6.1-universal.jar         | None                                     |
	| L     | resourceloader                    | 1.5.3                    | ResourceLoader-MC1.12.1-1.5.3.jar                    | None                                     |
	| L     | restrictions                      | 1.3.0                    | restrictions-1.12-1.3.0.jar                          | None                                     |
	| L     | rftoolscontrol                    | 2.0.2                    | rftoolsctrl-1.12-2.0.2.jar                           | None                                     |
	| L     | rftoolsdim                        | 5.71                     | rftoolsdim-1.12-5.71.jar                             | None                                     |
	| L     | rftoolspower                      | 1.2.0                    | rftoolspower-1.12-1.2.0.jar                          | None                                     |
	| L     | scannable                         | 1.6.3.24                 | Scannable-MC1.12.2-1.6.3.24.jar                      | None                                     |
	| L     | thermaldynamics                   | 2.5.6                    | ThermalDynamics-1.12.2-2.5.6.1-universal.jar         | None                                     |
	| L     | simplyjetpacks                    | 2.2.14.67                | SimplyJetpacks2-1.12.2-2.2.14.67.jar                 | None                                     |
	| L     | storagedrawers                    | 5.2.2                    | StorageDrawers-1.12.2-5.4.2.jar                      | None                                     |
	| L     | thermalcultivation                | 0.3.6                    | ThermalCultivation-1.12.2-0.3.6.1-universal.jar      | None                                     |
	| L     | thermalinnovation                 | 0.3.6                    | ThermalInnovation-1.12.2-0.3.6.1-universal.jar       | None                                     |
	| L     | tinker_io                         | rw2.8.1a                 | tinker_io-1.12.2-rw2.8.1a.jar                        | None                                     |
	| L     | tinkersaddons                     | 1.0.7                    | TinkersAddons-1.12.1-1.0.7.jar                       | None                                     |
	| L     | tcomplement                       | 1.12.2-0.4.3             | TinkersComplement-1.12.2-0.4.3.jar                   | None                                     |
	| L     | tinkertoolleveling                | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                  | None                                     |
	| L     | tmel                              | 1.12.2-1.4.0.0           | tmel-1.12.2-1.4.0.0.jar                              | None                                     |
	| L     | tombmanygraves                    | 1.12-4.2.0               | TombManyGraves-1.12-4.2.0.jar                        | None                                     |
	| L     | torchmaster                       | 1.8.1.81                 | torchmaster_1.12.2-1.8.1.81.jar                      | None                                     |
	| L     | translocators                     | 2.5.2.81                 | Translocators-1.12.2-2.5.2.81-universal.jar          | None                                     |
	| L     | traverse                          | 1.6.0                    | Traverse-1.12.2-1.6.0-69.jar                         | None                                     |
	| L     | universalmodifiers                | 1.12.2-1.0.16.1          | valkyrielib-1.12.2-2.0.20.1.jar                      | None                                     |
	| L     | wanionlib                         | 1.12.2-2.4               | WanionLib-1.12.2-2.4.jar                             | None                                     |
	| L     | wct                               | 3.12.97                  | WirelessCraftingTerminal-1.12.2-3.12.97.jar          | None                                     |
	| L     | woot                              | 1.12.2-1.4.11            | woot-1.12.2-1.4.11.jar                               | None                                     |
	| L     | wrcbe                             | 2.3.2                    | WR-CBE-1.12.2-2.3.2.33-universal.jar                 | None                                     |
	| L     | xaerominimap                      | 20.14.0                  | Xaeros_Minimap_20.14.0_Forge_1.12.jar                | None                                     |
	| L     | xaeroworldmap                     | 1.6.4                    | XaerosWorldMap_1.6.4_Forge_1.12.jar                  | None                                     |
	| L     | ynot                              | 0.2.4                    | YNot-0.2.4.jar                                       | None                                     |
	| L     | techreborn_compat                 | 1.0.0                    | TechReborn-ModCompatibility-1.12.2-1.4.0.76.jar      | None                                     |
	| L     | phosphor-lighting                 | 1.12.2-0.2.6             | phosphor-1.12.2-0.2.6build50-universal.jar           | None                                     |
	| L     | reauth                            | 3.6.0                    | reauth-3.6.0.jar                                     | None                                     |
	| L     | eleccoreloader                    | 1.9.453                  | ElecCore-1.12.2-1.9.453.jar                          | None                                     |
	| L     | librarianliblate                  | 4.20                     | librarianlib-1.12.2-4.20-release.jar                 | None                                     |
	| L     | mysticallib                       | 1.12.2-1.7.0             | mysticallib-1.12.2-1.7.0.jar                         | None                                     |
	| L     | teslacorelib_registries           | 1.0.17                   | tesla-core-lib-1.12.2-1.0.17.jar                     | None                                     |
	| L     | unidict                           | 1.12.2-2.9.6             | UniDict-1.12.2-2.9.6.jar                             | None                                     |
	| L     | wrapup                            | 1.12-1.1.3               | WrapUp-1.12-1.1.3.jar                                | None                                     |
	| UD    | scalar                            | 2.11.1-2                 | minecraft.jar                                        | None                                     |

### MMC Instance Notes

This instance is built using Github Action.
Using installer artifact from commit: a28f191ff6c18bb1f24ca0c7e3d1646c8f60f0ba
Action URL: https://github.com/CleanroomMC/Cleanroom/actions/runs/11586088564

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Do NOT use old phosphor
Use Alfheim

**Comment by Frankiscophil** [comment]
> Do NOT use old phosphor 
Use Alfheim

THANKS A BUNCH! That was the only thing preventing my client from fully loading XD
