### ISSUE TITLE
IllegalAccessException in Gadgetry: Core

### ISSUE THREAD

**Issue by erialsan** [CleanroomMC/Cleanroom#236]
### Your CleanroomMC Discord Username

erialsan

### Cleanroom Version

Build 759

### Java Version

Java 23

### Graphics Card Vendor

Intel iGPU

### Bug Report

https://mclo.gs/cYNEuV1

### Mod List

Fugue
Scalar 2.11
All Gadgetry series mods

### MMC Instance Notes

Use CRMMC in prism

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Add `epicsquid.gadgetry.core.hax.Hax` to Field.set() list in fugue.cfg
