### ISSUE TITLE
The maven.outlands.top has an https issue which means prism launcher, building from source will fail.

### ISSUE THREAD

**Issue by IsmaelDevYT** [CleanroomMC/Cleanroom#237]
### Cleanroom Version

0.2.3

### Java Version

Java 21

### Graphics Card Vendor

Intel iGPU

### Bug Report

https://mclo.gs/TNuJhBD

### Mod List

None

### MMC Instance Notes

None

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Just @ me in Discord

**Comment by IsmaelDevYT** [comment]
The bug report explains everything

> PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
   > Could not resolve com.cleanroommc:sponge-mixin:0.16.0+mixin.0.8.5.
   
    > The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. For more on this, please refer to https://docs.gradle.org/8.8/userguide/build_environment.html#sec:gradle_system_properties in the Gradle documentation.
    
                > Could not GET 'https://maven.outlands.top/releases/com/cleanroommc/sponge-mixin/0.16.0+mixin.0.8.5/sponge-mixin-0.16.0+mixin.0.8.5.pom'.


It happens in prism launcher, official launcher, or any launcher because it cannot download that library. I guess the owner of this repository will need to make the libraries in GitHub instead of mave.outlands.top


PLEASE SOLVE THE ISSUE

**Comment by IsmaelDevYT** [comment]
@kappa-maintainer you could just say the solution...

so that other people could know was the issue before spending hours of solving this

**BUT IT DOESN'T A SOLUTION UNLESS YOU DOWNLOAD THE LIBRARIES FROM A http website which can dangerous.**

**Comment by Ecdcaeb** [comment]
It is not a true issue here. Nobody would not know what the problem is and use hours to find it out. Atting kappa in discord is enough.
More, it is not a cleanroom issue. We are using Foundation, a experiment, and will switch to Bouncepad. So the issue will not happened in released Cleanroom.
