### ISSUE TITLE
Cleanroom won't work because of this

### ISSUE THREAD

**Issue by IsmaelDevYT** [CleanroomMC/Cleanroom#238]
### Cleanroom Version

0.2.3

### Java Version

Java 21

### Graphics Card Vendor

Intel iGPU

### Bug Report

**With Mods**
https://mclo.gs/MAqB41K
**Without mods**
https://mclo.gs/1z3u6n6

### Mod List

Vintagium

### MMC Instance Notes

I did use the MMC instace pack but I have use adoptium java 21 jdk & java 22 jdk. and azul java 21 jdk.

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by ZZZank** [comment]
you seem to be using Mac OS, whose compatibility is somewhat broken for the current release (if I recall correctly)
```
[06:28:56] [main/INFO] [FML]: Java is OpenJDK 64-Bit Server VM, version 21.0.5, running on Mac OS X:x86_64:10.15.7, installed at /Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home
```

And dont ping someone without providing any information, it's rude and useless

**Comment by IsmaelDevYT** [comment]
@ZZZank I just want help and yes i'm using macros.

**Comment by ZZZank** [comment]
The Mac OS issue likely to be LWJGL problem, which usually, unfortuantely, cannot be fixed by Cleanroom.

So please try the MMC instance provided by Kappa. And if it's not working, you might have to wait.

And again, dont ping without without providing any information, please. Developers are human, not bots that can be activated by a ping.

**Comment by Ecdcaeb** [comment]
I am deeply sorry for your help want. However, given the current shortage of cleanroom personnel, it is difficult for us to promptly address the needs of niche users, such as non QWERTY keyboards and macOS. The problem will not be solved quickly. PLZ wait some times.

**Comment by IsmaelDevYT** [comment]
@kappa-maintainer Its working!!!

The only thing is that I'm getting an error with vintagefix even if i use fugure (0.16.4) and Scalar 2.11.1-2

here is the log file https://mclo.gs/Mc3EHqp

**Comment by ZZZank** [comment]
It's likely to be vintagefix problem, and it's not fatal anyway

Also, do not ping

**Comment by IsmaelDevYT** [comment]
Alright, I won't ping anymore. This issue is solved. Thanks for the help.
