### ISSUE TITLE
storage drawers  Exception caught during firing event net.minecraftforge.client.event.ModelRegistryEvent

### ISSUE THREAD

**Issue by erialsan** [CleanroomMC/Cleanroom#244]
### Your CleanroomMC Discord Username

erialsan

### Cleanroom Version

build 771

### Java Version

Java 21

### Graphics Card Vendor

Intel iGPU

### Bug Report

https://mclo.gs/pc8NxvT

### Mod List

fugue
scalar
chameleon
storage drawers

### MMC Instance Notes

MMC in Prism

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by Rongmario** [comment]
This happens when you download Chameleon from Modrinth, its broken. Download it from CurseForge instead.
