### ISSUE TITLE
Error reading the forge_early.cfg file

### ISSUE THREAD

**Issue by abc15616545561** [CleanroomMC/Cleanroom#254]
### Cleanroom Version

cleanroom-0.2.4-alpha+build.9.run.793

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

latest.log:
[latest.log](https://github.com/user-attachments/files/18050422/latest.log)
This is forge_early
[forge_early.txt](https://github.com/user-attachments/files/18050437/forge_early.txt)

### Mod List

No mods,except Minecraft and Cleanroom itself

### MMC Instance Notes

Not

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [ ] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [ ] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by erialsan** [comment]
Some issue
A large amount of forge_early.cfg is duplicated at startup

**Comment by abc15616545561** [comment]
> Some issue A large amount of forge_early.cfg is duplicated at startup

Every time the system starts, an error appears in the log regarding reading the forge_early.cfg file. The current file is then renamed, and a new one is generated. However, the newly generated file is still not in the correct format, causing the process to repeat on the next startup.

**Comment by kappa-maintainer** [comment]
Fixed in latest build
