### ISSUE TITLE
Crash when launching the game

### ISSUE THREAD

**Issue by abc15616545561** [CleanroomMC/Cleanroom#255]
### Cleanroom Version

0.2.4-alpha+build.11.run.797

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

latest:
[latest.log](https://github.com/user-attachments/files/18051588/latest.log)
crashLog:
[crash-2024-12-08_17.51.16-client.txt](https://github.com/user-attachments/files/18051593/crash-2024-12-08_17.51.16-client.txt)

### Mod List

!Red-Core-MC-1.7-1.12-0.5.1.jar
+Fugue-1.12.2-0.17.2.jar
AbyssalCraft Integration-1.12.2-1.11.2.jar
AbyssalCraft-1.12.2-1.10.3.jar
ActuallyAdditions-1.12.2-r152.jar
ActuallyBaubles-1.12-1.1.jar
Additions-0.5.2.jar
AdLods-1.12.2-1.0.8.0-build.0504.jar
Advanced-Fishing-1.12.2-1.3.3.jar
ae2fc-1.12.2-1.0.10.jar
ae2stuff-0.7.0.4-mc1.12.2.jar
AE2WTLib-1.12.2-1.0.34.jar
aeble_v1.4.3.jar
Aether Continuation v1.3.0.jar
aether-1.12.2-v1.5.3.2.jar
AIImprovements-1.12-0.0.1b3.jar
AkashicTome-1.2-12.jar
Alfheim-1.4.jar
alwayseat-1.1.jar
Ambience-1.12.2-1.7.8.jar
AmbientSounds_v3.1.5_mc1.12.2.jar
Animus-1.12-2.1.7.jar
anvilpatch-1.0.1.jar
AppleCore-mc1.12.2-3.4.0.jar
AppleSkin-mc1.12-1.0.14.jar
appliedenergistics2-rv6-stable-7.jar
AquaAcrobatics-v1.3.5-1.12.2.jar
armorcurve-1.2.9.jar
armoreablemobs-1.12.2-1.1.8.jar
armoryexpansion-2.0.0-alpha.jar
Aroma1997Core-1.12.2-2.0.0.2.b167.jar
AromaBackup-1.12.2-3.0.0.0.b135.jar
astralsorcery-1.12.2-1.10.27.jar
athenaeum-1.12.2-1.19.2.jar
AttributeFix-1.12.2-1.0.10.jar
autoplant-1.12-1.0.0.jar
AutoRegLib-1.3-32.jar
Avaritia-1.12.2-3.3.0.37-universal.jar
avaritiaio-1.4.jar
AvaritiaTweaks-1.12.2-1.3.jar
BacoDifficulty-1.0.3.jar
badwithernocookiereloaded-1.12.2-3.4.18.jar
base-1.12.2-3.13.0.jar
BattleTowers-1.12.2.jar
Baubles-1.12-1.5.2.jar
bdlib-1.14.3.12-mc1.12.2.jar
bedpatch-2.2-1.12.2.jar
BetterAdvancements-1.12.2-0.1.0.77.jar
BetterBurning-1.12.2-0.9.2.jar
bettercaves-1.12.2-2.0.4.jar
BetterCombat-1.12.2-1.5.6.jar
BetterFoliage-MC1.12-2.3.3.jar
BetterFps-1.4.8.jar
BetterHurtTimer-1.12.2-1.5.0.1.jar
BetterMineshaftsForge-1.12.2-2.2.1.jar
bettermobgriefinggamerule-1.12.2-7.1.0.jar
betternether-0.1.8.6.jar
BetterPlacement-1.0.0-1.jar
BetterSigns-1.0_v1.12.2.jar
BetterSlimes-1.12.2-1.3.4.jar
BiblioCraft[v2.4.5][MC1.12.2].jar
biggerchathistory_0.1.1_MC_1.12.2.jar
biggerpacketsplz-since1.8-1.2.jar
binnie-mods-1.12.2-2.5.1.203.jar
BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar
birdsfoods-1.12 - 3.1.jar
BloodArsenal-1.12.2-2.2.2-31.jar
BloodMagic-1.12.2-2.4.3-105.jar
Blur-1.0.4-14.jar
BNBGamingCore-1.12.2-0.12.0.jar
BNBGamingLib-1.12.2-2.17.6.jar
bonsaitrees-1.1.4-b170.jar
Bookshelf-1.12.2-2.3.590.jar
Born In A Barn V1.8-1.12-1.1.jar
Botania r1.10-364.4.jar
botanianeedsit-1.12.2-3.0-release.jar
botaniatweaks-1.9.1.jar
BotanicAdditions-1.12.2-12.2.6.jar
BotanicBonsai-1.0.0.5.jar
BouncyCreepers-0.0.4.jar
Bountiful Baubles-1.12.2-0.1.6.jar
Bountiful-2.2.2.jar
BrandonsCore-1.12.2-2.4.19.214-universal.jar
BringMeTheRings-0.4.jar
BuildingGadgets-2.8.4.jar
CalmDownZombieGuy-1.12.2-1.6.4.jar
candyworld-1.1.5.jar
capabilityadapter-1.1.1.jar
Ceramics-1.12-1.3.7b.jar
Chameleon-1.12-4.1.3.jar
champions-1.12.2-1.0.11.10.jar
ChanceCubes-1.12.2-5.0.2.385.jar
Charm-1.12.2-1.4.1.jar
ChatFlow-1.4-7.jar
ChestTransporter-1.12.2-2.8.8.jar
Chisel-MC1.12.2-1.0.2.45.jar
ChiseledAdditions-1.0.0.jar
chiselsandbits-14.33.jar
Chocolate_Quest_Repoured-1.12.2-2.5.3B.jar
chunkgenlimiter-1.1.jar
classicbar-0.5.4.jar
clearwater-1.2.jar
ClientTweaks_1.12.2-3.1.11.jar
CodeChickenLib-1.12.2-3.2.3.358-universal.jar
CoFHCore-1.12.2-4.6.6.1-universal.jar
CoFHWorld-1.12.2-1.4.0.1-universal.jar
ColorUtility-universal-1.0.4.jar
ColouredTooltips-1.12.2-1.0.9.jar
colytra-1.12.2-1.2.0.4.jar
CombinedPotions-1.12-1.1.jar
comforts-1.12.2-1.4.1.3.jar
CompactDrawers-1.12.2-1.0.5.125.jar
compactmachines3-1.12.2-3.0.18-b278.jar
CompatSkills-1.12.2-1.17.0.jar
conarm-1.12.2-1.2.5.10.jar
ContentTweaker-1.12.2-4.10.0.jar
Controlling-3.0.10.jar
cookiecore-1.12-2.0.0.jar
CookingForBlockheads_1.12.2-6.5.0.jar
coroutil-1.12.1-1.2.37.jar
corpsecomplex-1.12.2-1.0.12.0.jar
CraftingTweaks_1.12.2-8.1.9.jar
CraftTweaker2-1.12-4.1.20.647.jar
crafttweakerutils-0.7.jar
CreativeCore_v1.10.61_mc1.12.2.jar
ctintegration-1.8.0.jar
CTM-MC1.12.2-1.0.2.31.jar
Cucumber-1.12.2-1.1.3.jar
CustomBackgrounds-MC1.12-1.1.1.jar
CustomLoadingScreen-1.12.2-1.5.5.jar
CustomMainMenu-MC1.12.2-2.0.9.1.jar
CustomSkinLoader_Forge-14.13-SNAPSHOT-278.jar
CustomStartingGear-1.12-1.2.0.9-universal.jar
Cyclic-1.12.2-1.20.9.jar
CyclopsCore-1.12.2-1.6.7.jar
DankNull-1.12.2-1.7.101.jar
DarkUtils-1.12.2-1.8.230.jar
DeathCounter-1.12.2-1.1.0.jar
Debark-0.1.2.jar
DefaultWorldGenerator-port-1.12-2.3.jar
defiledlands-1.12.2-1.4.3.jar
demagnetize-1.12.2-1.1.2.jar
deuf-1.1-1.12.2.jar
diethopper-1.1.jar
DimensionStages-1.12.2-2.0.23.jar
DoomlikeDungeons-1.14.5-MC1.12.2.jar
Draconic-Additions-1.12.2-1.16.4.44-universal.jar
Draconic-Evolution-1.12.2-2.3.27.353-universal.jar
dropt-1.12.2-1.18.0.jar
Dungeons2-mc1.12.2-f14.23.5.2859-v2.0.0.jar
DupeFixProject-1.12.2-3.1.6.jar
DynamicDynamos-1.12.2-1.10.jar
DynamicSurroundings-1.12.2-3.6.2.1.jar
DynamicSurroundingsHuds-1.12.2-3.6.0.0.jar
dynamistics-1.0.2.jar
dynviewdist-1.12-1.3.jar
EBLib-6.0.2.5.jar
eiorteis-3.1.jar
EnchantingTable-1.12-1.1.3.jar
EnchantmentDescriptions-1.12.2-1.1.20.jar
enchcontrol-1.12.2-1.1.5-0.jar
EnderCore-1.12.2-0.5.76.jar
EnderIO-1.12.2-5.2.66.jar
EnderIO-endergy-1.12.2-5.2.66.jar
EnderIO-zoo-1.12.2-5.2.66.jar
EnderStorage-1.12.2-2.4.6.137-universal.jar
EnderTweaker-1.12.2-1.2.1.jar
EnergeticSheep-1.12.2-1.1.5.jar
EntityCulling-1.12.2-4.1.5.jar
environmentalcreepers-1.12.2-1.6.0.jar
EquivalentIntegrations-0.4.6.jar
eternalsingularity-1.12.2-1.0.7.jar
ExpandedEquivalence-1.12.2-12.3.17.jar
ExtraBitManipulation-1.12.2-3.4.1.jar
ExtraBotany-r1.1-60-beta-hotfix.jar
ExtraCells-1.12.2-2.6.5.jar
extrautils2-1.12-1.9.9.jar
ExtremeReactors-1.12.2-0.4.5.68.jar
FarmingForBlockheads_1.12.2-3.1.28.jar
fastflyblockbreaking-MC1.9.4-MC1.12.2-1.1.jar
FastFurnace-1.12.2-1.3.1.jar
FastLeafDecay-v14.jar
FastWorkbench-1.12.2-1.7.3.jar
fencejumper-1.12-1.0.5.jar
findme-1.12.2-1.1.0-8.jar
fluiddrawers-1.12.2-1.0.6.jar
fluidict-1.2.jar
FluxNetworks-1.12.2-4.1.1.34.jar
foamfix-0.10.14-1.12.2.jar
FoodExpansion1.3.3-1.12.2.jar
forestry_1.12.2-5.8.2.422.jar
forge-1.12.2-geckolib-3.0.0-beta.7.jar
ForgeEndertech-1.12.2-4.5.5.0-build.0561.jar
Forgelin-Continuous-2.1.0.0.jar
FpsReducer-mc1.12.2-1.18.jar
FTBGuides-2.0.0.52.jar
FTBLib-5.4.7.2.jar
FTBQuests-1202.9.0.15.jar
FTBUtilities-5.4.1.131.jar
FullscreenWindowed-1.12-1.6.0.jar
furniture-6.3.1-1.12.2.jar
GameStages-1.12.2-2.0.123.jar
GasConduits-1.12.2-1.2.4.jar
gendustry-1.6.5.8-mc1.12.2.jar
gendustryjei-1.0.2.jar
GlobalGameRules-1.12.2-2.2.7.jar
globalxp-1.12.2-v1.4.10.jar
GottschCore-mc1.12.2-f14.23.5.2859-v1.15.1.jar
gravestone-1.10.3.jar
Guide-API-1.12-2.1.8-63.jar
GunpowderLib-1.12.2-1.1.jar
HammerLib-1.12.2-2.0.6.26.jar
hardcoreitemstages-1.12.2-1.0.1.jar
Headcrumbs-1.12.2-2.0.5.17.jar
hiddenarmor-1.12.2-1.0.jar
HomingExpOrbs-1.1.jar
hooked-1.0.3.jar
HungerTweaker-1.12.2-1.3.0.jar
iblis-headshots-1.12-1.2.7.jar
iChunUtil-1.12.2-7.2.2.jar
IGI-BloodMagic-1.2.jar
IGI-Thaumcraft-1.0a.jar
igisereneseasons-1.0.0.1.jar
ikwid-1.0.2.jar
incontrol-1.12-3.9.18.jar
InGameInfoXML-1.12.2-2.8.2.94-universal.jar
InventoryHud_1.12.2.forge-3.3.1.jar
inventorypets-1.12-2.0.15.jar
InventoryTweaks-1.64+dev.151.jar
InvMove-1.12.2-0.4.6.jar
IonChests-1.0.0.jar
ironchest-1.12.2-7.0.72.847.jar
ItemFilters-1.0.4.2.jar
ItemPhysic_Full_1.4.34_mc1.12.2.jar
ItemStages-1.12.2-2.0.51.jar
itlt-1.12.x-1.0.4.jar
IvToolkit-1.3.3-1.12.jar
JAOPCA-1.12.2-2.2.8.105.jar
JAOPCAAdditions-1.12.2-2.2.1.9.jar
JAOPCAAgriculture-1.12.2-1.2.1.17.jar
JAOPCASingularities-1.12.2-2.2.0.9.jar
jeibees-0.9.0.5-mc1.12.2.jar
jeiintegration_1.12.2-1.6.0.jar
jeivillagers-1.12-1.0.2.jar
jei_1.12.2-4.16.1.302.jar
jepb-1.12-1.2.1.jar
JEROreIntegration-1.12.2-1.1.0.jar
jetif-1.12.2-1.5.2.jar
just-enough-brewcraft-1.12.2-1.0.2.jar
just-enough-harvestcraft-1.12.2-1.7.2.jar
JustEnoughCalculation-1.12.2-3.2.6.jar
JustEnoughCharacters-1.12.0-3.5.0.jar
JustEnoughEnergistics-1.12.2-1.0.8.jar
JustEnoughIDs-1.0.3-55.jar
JustEnoughReactors-1.12.2-1.1.3.61.jar
JustEnoughResources-1.12.2-0.9.2.60.jar
JustSleep-1.0.0.1.jar
KleeSlabs_1.12.2-5.4.12.jar
lavawaderbauble-1.2.jar
lazy-ae2-1.12.2-1.1.26.jar
letsencryptcraft-1.10.2-1.2.0.jar
libnine-1.12.2-1.2.0.jar
LibrarianLib-Continuous-1.12.2-4.22-2.0-2.jar
LibraryEx-1.12.2-1.2.1.jar
Limited Enchantments-1.0.jar
llibrary-1.7.20-1.12.2.jar
LoadingScreens-1.12.2-0.3.1.jar
logisticspipes-0.10.4.49.jar
LootBags-1.12.2-2.5.8.5.jar
lootcapacitortooltips-1.3.jar
LootOverhaul-1.2.jar
LootTweaker-0.3.0+MC1.12.2.jar
lostcities-1.12-2.0.22.jar
LunatriusCore-1.12.2-1.2.0.42-universal.jar
MAGE-0.2.4.jar
MagicBees-1.12.2-3.2.25.jar
magicfeather-1.12.2-2.2.0.jar
MainMenuScale-1.3.2.jar
Mantle-1.12-1.3.3.55.jar
materialchanger1.0.3-1.12.2.jar
MCA-1.12.2-6.1.0-universal.jar
mcjtylib-1.12-3.5.4.jar
Mekanism-1.12.2-9.8.3.390.jar
MekanismGenerators-1.12.2-9.8.3.390.jar
mekores-2.0.13.jar
memorycleaner-1.4.jar
MikesModsLib-1.0.2.jar
MineMenu-1.12.2-1.6.11-universal.jar
MMLib-2.3.0.jar
MmmMmmMmmMmm-1.12-1.14.jar
MobDismemberment-1.12.2-7.0.0.jar
MoBends_1.12.2-1.0.0-beta-20.06.20.jar
MobStages-1.12.2-2.0.13.jar
modnametooltip_1.12.2-1.10.1.jar
Modpack Configuration Checker-1.12.2-v1.9.5.jar
modtweaker-4.0.19.jar
modularmachinery-1.12.2-1.11.1.jar
morebees-1.12.2-2.0.1.jar
moreloottables-1.12.0-0.1.0.jar
MoreTweaker-1.0.19.jar
Morph-o-Tool-1.2-21.jar
Morpheus-1.12.2-3.5.106.jar
MouseTweaks-2.10-mc1.12.2.jar
mowziesmobs-1.5.8.jar
MTLib-3.0.7.jar
MultithreadedNoise-1.12.2-0.0.2.jar
MysticalAgradditions-1.12.2-1.3.2.jar
MysticalAgriculture-1.12.2-1.7.5.jar
MysticalCreations-1.12.2-1.6.1.jar
nanfix-final-absorbtion.jar
natura-1.12.2-4.3.2.69.jar
NaturesCompass-1.12.2-1.8.5.jar
Netherending-Ores-1.12.2-1.4.2.jar
NetherEx-1.12.2-2.2.4.jar
NetherPortalFix_1.12.1-5.3.17.jar
NoMobSpawningOnTrees-1.2.2-mc1.12.2.jar
NoMoreRecipeConflict-0.13(1.12.2).jar
noRecipeBook_v1.2.2formc1.12.2.jar
Nyx-1.4.2.jar
oeintegration-2.3.4.jar
OldJavaWarning-1.12.2-1.1.11.jar
omlib-1.12.2-3.2.0-256.jar
ompd-1.12.2-3.2.0-76.jar
OpenBlocks-1.12.2-1.8.1.jar
OpenModsLib-1.12.2-0.12.2.jar
openmodularturrets-1.12.2-3.2.0-379.jar
OptiFine_1.12.2_HD_U_G5.jar
OrechidEndium-1.12.2-1.0.1.jar
OreExcavation-1.4.150.jar
OreLib-1.12.2-3.6.0.1.jar
OreStages-1.12.2-2.0.38.jar
p455w0rdslib-1.12.2-2.3.161.jar
PackagedAuto-1.12.2-1.0.5.17.jar
PackagedAvaritia-1.12.2-1.0.2.5.jar
packmode-1.12.2-1.2.0.jar
PackModeMenu-1.0.4.jar
Pam's BrewCraft 1.12.2-1.0.2.jar
Pam's Get all the Seeds! 1.12a.jar
Pam's HarvestCraft 1.12.2zg.jar
pamscookables-1.1.jar
particleculling-1.12.2-v1.0.1.jar
PassableLeaves-1.12.2-2.0.0.jar
Patchouli-1.0-23.6.jar
Placebo-1.12.2-1.6.0.jar
PlaneFix-1.12.2-1.0.0.jar
Plummet-1.12.2-1.0.0.jar
plustic-8.0.3.jar
PotionCore-1.9_for_1.12.2.jar
potiondescriptions-1.12.2-1.2.4.jar
pouchofunknown-1.9.jar
prefab-1.3.0.26.jar
PrettyBeaches_1.12.2-1.1.0.jar
ProgressiveBosses-1.5.4-mc1.12.x.jar
ProjectE-1.12.2-PE1.4.1.jar
ProjectEX-1.2.0.40.jar
ProjectIntelligence-1.12.2-1.0.9.28-universal.jar
ProjectVibrantJourneys-1.12.2-1.6.4.jar
ProportionalDestructionParticles-1.12.2-1.2.4.jar
PyramidPlunder-1.12.2-1.4.jar
Quark-r1.6-182.jar
randompatches-1.12.2-1.22.1.10.jar
RandomThings-MC1.12.2-4.2.7.4.jar
randomtweaks-1.12.2-2.8.3.1.jar
Re-Fraction V1.0.jar
RealFirstPerson2-1.12.2-1.3.2.jar
reauth-3.6.0.jar
RebornCore-1.12.2-3.19.5-universal.jar
RecipesForAll-1.0.0.jar
RecipeStages-1.1.3.jar
RecurrentComplex-1.4.8.2.jar
RedstoneArsenal-1.12.2-2.6.6.1-universal.jar
RedstoneFlux-1.12-2.1.1.1-universal.jar
redstonepaste-mc1.12-1.7.5.jar
RedstoneRepository-1.12.2-1.4.0-dev-universal.jar
Reskillable-1.12.2-1.13.0.jar
ResourceLoader-MC1.12.1-1.5.3.jar
Rex's-Additional-Structures-1.12.x-(v.2.3.1).jar
rftools-1.12-7.73.jar
rftoolsctrl-1.12-2.0.2.jar
rftoolspower-1.12-1.2.0.jar
RoguelikeDungeonsFnarEdition-1.12.2-2.3.1.jar
rotm-1.12.2-1.1.4.jar
roughmobsrevamped-1.12.2-2.3.21.jar
Ruins-1.12.2.jar
Rustic Thaumaturgy-4.4a.jar
rustic-1.1.7.jar
rusticbopwoods-1.0.jar
Sakura-1.0.7-1.12.2.jar
sampler-1.84.jar
savemystronghold-1.12.2-1.0.0.jar
scalar-1.12.2-2.11.1-2.jar
scalingguis-1.12.2-1.0.3.0.jar
ScalingHealth-1.12.2-1.3.42+147.jar
ScalingWealth-1.0.1.jar
Scavenge V1.12-1.8.3.2.jar
ScreenshotToClipboard-1.12.2-1.0.1.jar
SereneSeasons-1.12.2-1.2.18-universal.jar
SereneTweaks-1.0.jar
ServerPropertiesLAN-2.65.jar
ServerTabInfo-1.12.2-1.2.6.jar
shapeselector-1.12.2b4.jar
ShoulderSurfing-1.12.2-2.9.6.jar
shutupmodelloader-1.12.2-1.0.0.jar
SilentLib-1.12.2-3.0.14+168.jar
SimpleSmelteryAccelerator-1.0.1.jar
simplybackpacks-1.4.9.jar
SmoothFont-mc1.12.2-2.1.2.jar
Snad-1.12.1-1.7.09.16a.jar
SnowRealMagic-0.3.3.jar
SolarFluxReborn-1.12.2-12.4.11.jar
solcarrot-1.12.2-1.8.4.jar
Sound-Physics-1.12.2-1.0.10-1.jar
soundsystemreloader-1.0.0.jar
spatialservermod-1.3.1.jar
SpawnerControl-1.6.3b.jar
SpiceOfLife-mc1.12-1.3.12.jar
SplashAnimation-0.2.1.jar
Stackie-1.12.2-1.6.0.48-universal.jar
stacksize-1.12.2-1.0.jar
stellarfluidconduit-1.12.2-1.0.3.jar
StepupFix-1.12.2-1.0.0.4.b17.jar
stg-1.12.2-1.2.3.jar
StorageDrawers-1.12.2-5.4.2.jar
StorageDrawersExtras-1.12-3.1.0.jar
StuffASockInIt-1.12.2-1.1.32.jar
stygian-1.0.4.jar
Surge-1.12.2-2.0.79.jar
taiga-1.12.2-1.3.4.jar
tc6aspects4jei-0.0.2a.jar
tconevo-1.12.2-1.0.38.jar
tconmodmod-1.12.2-1.0.5.jar
TConstruct-1.12.2-2.13.0.183.jar
tellme-1.12.2-0.7.0-dev.20200919.184303.jar
Tesla-1.12.2-1.0.63.jar
tesla-core-lib-1.12.2-1.0.17.jar
Thaumcraft-1.12.2-6.1.BETA26.jar
ThaumicAdditions-1.12.2-12.6.7.jar
ThaumicAugmentation-1.12.2-2.1.1.jar
thaumicenergistics-2.2.4.jar
ThaumicEquivalence-1.12.2-1.0.5.jar
ThaumicInventoryScanning_1.12.2-2.0.10.jar
ThaumicJEI-1.12.2-1.6.0-27.jar
thaumicspeedup-2.0.jar
thaumictinkerer-1.12.2-5.0-620a0c5.jar
thaumicwonders-1.8.2.jar
theoneprobe-1.12-1.4.28.jar
ThermalCultivation-1.12.2-0.3.6.1-universal.jar
ThermalDynamics-1.12.2-2.5.6.1-universal.jar
ThermalExpansion-1.12.2-5.5.7.1-universal.jar
ThermalFoundation-1.12.2-2.6.7.1-universal.jar
ThermalInnovation-1.12.2-0.3.6.1-universal.jar
thermallogistics-0.3-42.jar
ThermalTinkering-1.12.2-2.0.1.jar
TieredTooltips-2.0.0.jar
tinkersaether-1.4.1.jar
TinkersComplement-1.12.2-0.4.3.jar
tinkersjei-1.2.jar
TinkerStages-1.12.2-2.0.17.jar
TinkerToolLeveling-1.12.2-1.1.0.jar
tinker_io-1.12.2-rw2.8.3.jar
TinyMobFarm-1.12.2-1.0.5.jar
Tips-1.12.2-1.0.9.jar
Toast Control-1.12.2-1.8.1.jar
TofuCraftReload-0.1.0.9.jar
togetherforever-1.12.2-1.0.12-22.jar
toolprogression-1.12.2-1.6.12.jar
topaddons-1.12.2-1.13.0.jar
torchmaster_1.12.2-1.8.4.84.jar
torchslabmod-1.12.2-v1.5.2.jar
torohud-1.12.2-5.jar
touhoulittlemaid-1.12.2-1.2.4-release.jar
TrashSlot_1.12.2-8.4.10.jar
Treasure2-mc1.12.2-f14.23.5.2854-v1.16.1.jar
Triumph-1.12.2-3.19.2.jar
tumbleweed-1.12-0.4.7.jar
tweakersconstruct-1.12.2-1.6.1.jar
twilightforest-1.12.2-3.11.1021-universal.jar
UnforgivingVoid-1.12.2-1.0.5.jar
UniDict-1.12.2-3.0.8.jar
unifier-3.0.4.jar
Unifine-1.12.2-0.1.0.jar
unloader-1.2.0.jar
VanillaIcecreamFix-1.0.4.jar
variegated-1.2.7.jar
versioner-1.0.3.jar
Vials-MC1.12-1.2.1.5.jar
VillageNames-1.12.2-4.3.0.jar
w2w-1.2.1.jar
Waddles-1.12.2-0.6.0.jar
WanionLib-1.12.2-2.5.jar
Waystones_1.12.2-4.1.0.jar
Weee! Flowers 1.12.2b.jar
WHAT-0.2.jar
whoops-1.0.1.jar
WirelessCraftingTerminal-1.12.2-3.12.97.jar
WirelessFluidTerminal-1.12.2-1.0.4.jar
WirelessInterfaceTerminal-1.12.2-1.0.2.jar
WirelessPatternTerminal-1.12.2-1.0.3.jar
WorldSelectionAdvanced-1.12.2-02.jar
WrapUp-1.12-1.1.3.jar
XaerosWorldMap_1.14.1_Forge_1.12.jar
Xaeros_Minimap_21.10.0.2_Forge_1.12.jar
XL-Food-Mod-1.12.2-1.9.2.jar
xnet-1.12-1.8.2.jar
YNot-0.2.4.jar
YungsLaw-1.12.2-1.0.4.jar
Zen Summoning-1.12-1.1.0.jar
zenstages-0.5.0.jar
zenutils-1.8.1.jar
zerocore-1.12.2-0.1.2.9.jar
zombieawareness-1.12.1-1.11.16.jar

### MMC Instance Notes

Not

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
You found a new LP class loading order!
Try latest Fugue build from action after it is done:
https://github.com/CleanroomMC/Fugue/actions/runs/12220924983

**Comment by abc15616545561** [comment]
> You found a new LP class loading order!您找到了新的 LP 类加载顺序！ Try latest Fugue build from action after it is done:完成后，尝试最新的 Fugue 版本： https://github.com/CleanroomMC/Fugue/actions/runs/12220924983

Alright, I will give it a try. However, as you can see, I have a lot of mods installed, so it might take some time for me to get back to you.

**Comment by abc15616545561** [comment]
> You found a new LP class loading order! Try latest Fugue build from action after it is done: https://github.com/CleanroomMC/Fugue/actions/runs/12220924983

It didn't solve my problem.

New Latest.log:
[latest.log](https://github.com/user-attachments/files/18051648/latest.log)
New CrashLog:
[crash-2024-12-08_18.20.59-client.txt](https://github.com/user-attachments/files/18051650/crash-2024-12-08_18.20.59-client.txt)
[crash-2024-12-08_18.21.00-client.txt](https://github.com/user-attachments/files/18051649/crash-2024-12-08_18.21.00-client.txt)

I don't know why there are two crashLog.

**Comment by abc15616545561** [comment]
> You found a new LP class loading order! Try latest Fugue build from action after it is done: https://github.com/CleanroomMC/Fugue/actions/runs/12220924983

您好像是中国人，抱歉我之前不知道，一直用chatGPT翻译中文来回答的（）

**Comment by kappa-maintainer** [comment]
去action找最新的fugue，如果还崩就去配置文件自己填类名

**Comment by abc15616545561** [comment]
> 去action找最新的fugue，如果还崩就去配置文件自己填类名

这次非常顺利，成功进入了主界面，但是在创建世界后加入世界时还是有问题，貌似是热力导致的？
崩溃日志：
[crash-2024-12-08_19.47.29-server.txt](https://github.com/user-attachments/files/18051895/crash-2024-12-08_19.47.29-server.txt)
[crash-2024-12-08_19.47.36-client.txt](https://github.com/user-attachments/files/18051896/crash-2024-12-08_19.47.36-client.txt)
游戏日志：
[latest.log](https://github.com/user-attachments/files/18051898/latest.log)

**Comment by kappa-maintainer** [comment]
逆天
热力物流禁用试试
不行就把LP禁用试试

**Comment by abc15616545561** [comment]
> 逆天 热力物流禁用试试 不行就把LP禁用试试

破案了，确实是热动力学的问题，禁用就没事了，不过我看日志好像也是因为缺少类，能修不
Caused by: java.lang.ClassNotFoundException: astavie.thermallogistics.container.ContainerTerminal

**Comment by kappa-maintainer** [comment]
这类我看了最新版是有的，你更新下看看
如果不行再新开一个issue，然后尝试二分找出最小再现组合
