### ISSUE TITLE
music cant play in Music player mod

### ISSUE THREAD

**Issue by erialsan** [CleanroomMC/Cleanroom#258]
### Your CleanroomMC Discord Username

erialsan

### Cleanroom Version

Build 798

### Java Version

Java 21

### Graphics Card Vendor

Intel iGPU

### Bug Report

https://mclo.gs/5aRdwdJ

### Mod List

Fugue Scalar
U-team core
Music player

### MMC Instance Notes

Use MMC instance pack in prism

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by erialsan** [comment]
Also, this happens when trying to play music, so mods can be activated!
In conjunction with the previous issue, there may be a music-related problem

**Comment by Ecdcaeb** [comment]
`[22:07:43] [lava-daemon-pool-playback-1-thread-1/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:660]: Caused by: java.lang.IllegalStateException: Must find action functions from script: /s/player/5b77d519/player_ias.vflset/ja_JP/base.js`

is it works for forge?

**Comment by erialsan** [comment]
I haven't tried Forge, but it worked with older versions of Cleanroom.

**Comment by erialsan** [comment]
I had a problem with forge.
How did you...
It wasn't a problem before.
I don't understand this mod.
