### ISSUE TITLE
java.lang.RuntimeException: An error occurred trying to configure the Minecraft home In Old Sound, Eye Candy, & Animations by Adrenix

### ISSUE THREAD

**Issue by erialsan** [CleanroomMC/Cleanroom#260]
### Your CleanroomMC Discord Username

erialsan

### Cleanroom Version

Build 798

### Java Version

Java 21

### Graphics Card Vendor

Other (Please Specify)

### Bug Report

https://mclo.gs/Qdg4Y7S

### Mod List

(fugue,scalar)
[Old Sound, Eye Candy, & Animations](https://www.curseforge.com/projects/403590) by Adrenix

### MMC Instance Notes

Use MMC instance pack

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by erialsan** [comment]
I forgot to change the graphics card.
It's Intel's internal GPU for the 12th generation.

**Comment by Ecdcaeb** [comment]
add `mod.adrenix.oseca.core.OSECACore` to `getCodeSourcePatchTargets` in `fugue.cfg`

**Comment by erialsan** [comment]
It Work
