### ISSUE TITLE
游戏启动时崩溃

### ISSUE THREAD

**Issue by create-xiaoyu** [CleanroomMC/Cleanroom#261]
### Cleanroom Version

0.2.4-alpha+build.17.run.803

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

[latest.log](https://github.com/user-attachments/files/18163780/latest.log)

### Mod List

Fugue
Scalar

### MMC Instance Notes

不是MMC

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
在开发新功能，我也崩
