### ISSUE TITLE
与AdLods-1.12.2-1.0.8.0-build.0504.jar不兼容

### ISSUE THREAD

**Issue by AnzOOCH** [CleanroomMC/Cleanroom#263]
### Your CleanroomMC Discord Username

OOCH

### Cleanroom Version

0.2.4-alpha

### Java Version

Java 22

### Graphics Card Vendor

NVidia

### Bug Report

[crash-2024-12-19_17.45.27-client.txt](https://github.com/user-attachments/files/18196216/crash-2024-12-19_17.45.27-client.txt)

### Mod List

  Loaded coremods (and transformers): 
                                      wings (wings-1.1.6-1.12.2.jar)
                                        me.paulf.wings.server.asm.WingsRuntimePatcher
                                        me.paulf.wings.server.asm.mobends.WingsMoBendsRuntimePatcher
                                      IFPatcher (IFPatcher-2.2.0.jar)
                                        net.eve0415.ifpatcher.Transformer
                                      MixinBooter (cleanroom-0.2.4-alpha.jar)
                                        
                                      UniversalTweaksCore (UniversalTweaks-1.12.2-1.13.0.jar)
                                        
                                      BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.22.64.jar)
                                        
                                      AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      LoliASM (censoredasm5.20.jar)
                                        
                                      iceandfire (iceandfire-1.9.1-1.12.2.jar)
                                        com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
                                      EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
                                        com.enderio.core.common.transform.EnderCoreTransformer
                                        com.enderio.core.common.transform.SimpleMixinPatcher
                                      Thaumic Augmentation Core Plugin (ThaumicAugmentation-1.12.2-2.1.8.jar)
                                        thecodex6824.thaumicaugmentation.core.TATransformer
                                      ReachFixPlugin (ReachFix-1.12.2-1.0.9.jar)
                                        meldexun.reachfix.asm.ReachFixClassTransformer
                                      LittlePatchingLoader (LittleTiles_v1.5.58_mc1.12.2.jar)
                                        com.creativemd.littletiles.LittleTilesTransformer
                                      LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
                                        lumien.hardcoredarkness.asm.ClassTransformer
                                      LoadingPlugin (Reskillable-1.12.2-1.13.0.jar)
                                        codersafterdark.reskillable.base.asm.ClassTransformer
                                      ColorUtilityCorePlugin (ColorUtility-universal-1.0.4.jar)
                                        com.Axeryok.ColorUtility.ColorUtilityTransformer
                                      LoadingPlugin (RandomThings-MC1.12.2-4.2.7.4.jar)
                                        lumien.randomthings.asm.ClassTransformer
                                      ErebusFix Mixin Loading Plugin (erebusfix-1.12.2-0.0.0.1.jar)
                                        
                                      RandomPatches (randompatches-1.12.2-1.22.1.10.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      TheBetweenlandsLoadingPlugin (TheBetweenlands-3.9.6-core.jar)
                                        thebetweenlands.core.TheBetweenlandsClassTransformer
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      AstralCore (astralsorcery-1.12.2-1.10.27.jar)
                                        
                                      CQRPlugin (Chocolate_Quest_Repoured-1.12.2-2.6.15B.jar)
                                        team.cqr.cqrepoured.asm.CQRClassTransformer
                                      Flare Coremod (flare-0.2.1.jar)
                                        
                                      CorePlugin (ForgeEndertech-1.12.2-4.5.6.1-build.0648.jar)
                                        
                                      Fugue (+Fugue-1.12.2-0.17.4.jar)
                                        
                                      TARCore (ThaumicAdditions-1.12.2-12.7.8.jar)
                                        
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
                                        li.cil.oc.common.asm.ClassTransformer
                                      MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
                                        mekanism.coremod.KeybindingMigrationHelper
                                      ScalarLoadingPlugin (scalar-1.12.2-2.11.1.jar)
                                        
                                      Quark Plugin (Quark-r1.6-179.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
                                        com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
                                        
                                      Forgelin-Continuous (Forgelin-Continuous-2.1.0.0.jar)
                                        
                                      ratscore (rats-3.2.14-1.12.2.jar)
                                        com.github.alexthe666.rats.server.misc.RatsRuntimePatcher
                                      LevelUpCore (levelup2-1.5.8.jar)
                                        
                                      LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
                                        lumien.resourceloader.asm.ClassTransformer
                                      MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
                                        
                                      IvToolkit (IvToolkit-1.3.3-1.12.jar)
                                        
                                      midnight (themidnight-0.3.5.jar)
                                        com.mushroom.midnight.core.transformer.MidnightClassTransformer
                                      CreativePatchingLoader (CreativeCore_v1.10.70_mc1.12.2.jar)
                                        
                                      OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
                                        openmods.core.OpenModsClassTransformer
                                      FutureMC (future-mc-0.2.11.jar)
                                        thedarkcolour.futuremc.asm.CoreTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.7.0-232-universal.jar)
                                        zmaster587.advancedRocketry.asm.ClassTransformer
                                      CharmLoadingPlugin (Charm-1.12.2-1.4.1.jar)
                                        svenhjol.charm.base.CharmClassTransformer
                                      Plugin (NotEnoughIDs-1.5.4.4.jar)
                                        ru.fewizz.neid.asm.Transformer
                                      MDECore-Core (mdecore-1.12-1.1.jar)
                                        com.mattdahepic.mdecore.asm.TickrateTransformer
                                      AncientSpellcraftCore (AncientSpellcraft-1.12.2-1.7.5.jar)
                                        
                                      HCASM (HammerLib-1.12.2-2.0.6.32.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      Max Potion ID Extender (maxpotidext-1.0.3.jar)
                                        zabi.minecraft.maxpotidext.MPIDTransformer

### MMC Instance Notes

none

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
要么用Hesperus要么用Alfheim，phosphor八百年没更新了
