### ISSUE TITLE
Crash with Silent Gems

### ISSUE THREAD

**Issue by mczph** [CleanroomMC/Cleanroom#264]
### Your CleanroomMC Discord Username

mczph

### Cleanroom Version

0.2.4-alpha+build.27

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

https://mclo.gs/VoJ4oHi
Relevant information was found in [this issue](https://github.com/CleanroomMC/Cleanroom/issues/15), but it has not been fixed by Fugue

### Mod List

	| State  | ID            | Version       | Source                                               | Signature |
	|:------ |:------------- |:------------- |:---------------------------------------------------- |:--------- |
	| LCHIJA | minecraft     | 1.12.2        | minecraft.jar                                        | None      |
	| LCHIJA | mcp           | 9.42          | minecraft.jar                                        | None      |
	| LCHIJA | configanytime | 3.0           | cleanroom-0.2.4-alpha+build.27.run.832-universal.jar | None      |
	| LCHIJA | cleanroom     | 0.2.4-alpha   | cleanroom-0.2.4-alpha+build.27.run.832-universal.jar | None      |
	| LCHIJA | FML           | 8.0.99.99     | cleanroom-0.2.4-alpha+build.27.run.832-universal.jar | None      |
	| LCHIJA | forge         | 14.23.5.2860  | cleanroom-0.2.4-alpha+build.27.run.832-universal.jar | None      |
	| LCHIJA | mixinbooter   | 10.2          | cleanroom-0.2.4-alpha+build.27.run.832-universal.jar | None      |
	| LCHIJA | fugue         | 1.12.2-0.17.5 | +Fugue-1.12.2-0.17.5.jar                             | None      |
	| LCHIJA | silentlib     | 3.0.13        | SilentLib-1.12.2-3.0.14+168.jar                      | None      |
	| LCHIJA | silentgems    | 2.8.18        | SilentsGems-1.12.2-2.8.22+327.jar                    | None      |

### MMC Instance Notes

CleanroomMMC using Prism Launcher 8.4

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Reset fugue.cfg, if didn't work, add `net.silentchaos512.gems.handler.PlayerDataHandler$PlayerData`to javax list

**Comment by mczph** [comment]
None of them were fixed, the same crash occurred, and it seems there are other problems.
latest.log:https://mclo.gs/9vEZLfC

**Comment by Ecdcaeb** [comment]
` net.silentchaos512.lib.tile.TileEntitySL`
`net.silentchaos512.gems.handler.PlayerDataHandler$PlayerData`

**Comment by Ecdcaeb** [comment]
add `net.silentchaos512.lib.tile.SyncVariable$Helper`

**Comment by mczph** [comment]
> net.silentchaos512.lib.tile.SyncVariable$Helper

fixed
