### ISSUE TITLE
Infinite Black Screen/Repeating OpenGL error

### ISSUE THREAD

**Issue by GavinFF-SS** [CleanroomMC/Cleanroom#265]
### Your CleanroomMC Discord Username

gavinff.

### Cleanroom Version

Cleanroom_MMC 0.2.4-alpha+build.29.run.834

### Java Version

Java 22

### Graphics Card Vendor

NVidia

### Bug Report

https://mclo.gs/3Y6yfuk

### Mod List

Fugue
Scalar
(both of these are not shown in the logs I uploaded, I uploaded the logs before testing it using these mods, but the error does persist)

### MMC Instance Notes

This instance is built using Github Action.
Using installer artifact from commit: df3a8b3e189348701fe9d655b6c691b7108901c3
Action URL: https://github.com/CleanroomMC/Cleanroom/actions/runs/12443411968

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Try switching to Prism launcher, I guess the old lwjgl library is breaking all traditional launchers

**Comment by Rongmario** [comment]
Seems like from the log PrismLauncher is being used, also you said you were using an NVIDIA GPU but the instance is utilizing your Intel integrated graphics instead?

**Comment by GavinFF-SS** [comment]
> Try switching to Prism launcher, I guess the old lwjgl library is breaking all traditional launchers Update: just found you did use Prism, is same crash happens in 0.2.4-alpha?

Yes, still happens, the first one I tried in fact.

**Comment by GavinFF-SS** [comment]
> Seems like from the log PrismLauncher is being used, also you said you were using an NVIDIA GPU but the instance is utilizing your Intel integrated graphics instead?

Weird, "Use discrete GPU" is checked in Prism Launcher for the instance.

**Comment by kappa-maintainer** [comment]
So it is not caused my our recent update of lwjgl, could you try to force javaw using NVIDIA GPU and launch again? I guess that's a driver problem

**Comment by GavinFF-SS** [comment]
> So it is not caused my our recent update of lwjgl, could you try to force javaw using NVIDIA GPU and launch again? I guess that's a driver problem

How would I do that? I've tried stuff like prime-run, but I can't figure it out.

**Comment by kappa-maintainer** [comment]
It seems you are using Arch with latest packages
So read this: https://wiki.archlinux.org/title/Hybrid_graphics

**Comment by GavinFF-SS** [comment]
> It seems you are using Arch with latest packages So read this: https://wiki.archlinux.org/title/Hybrid_graphics

I'm running on Nobara, which is Fedora based.

**Comment by kappa-maintainer** [comment]
Ah... Fedora
That's out of my scope then, my only successful installation of bbswitch was on Debian

**Comment by GavinFF-SS** [comment]
Not seeing anything online for installing bbswitch on Fedora either, most of the guides have defunct repos, the official guide on the Fedora wiki no longer exists. Really weird.

**Comment by GavinFF-SS** [comment]
Well, switched back to the releases version, running with "prime-run" as the wrapper command and it... works? I literally didn't do anything besides enabling prime run and switching to the 0.2.4 alpha build on this repo's releases, and a restart of the computer too. Weird.

**Comment by kappa-maintainer** [comment]
Wait, is the latest action build still crashing?

**Comment by GavinFF-SS** [comment]
Last time I checked it was.

**Comment by kappa-maintainer** [comment]
Could you test it again? We are making our way to the next release and I want to make sure it is stable enough

**Comment by GavinFF-SS** [comment]
Okay: The nightly one doesn't work but they're both completely different errors, with one only happening on Java 23 (which I tried on the releases build and that ran) and one happening on Java 22.
