### ISSUE TITLE
Use Brigadier

### ISSUE THREAD

**Issue by Ecdcaeb** [CleanroomMC/Cleanroom#33]
should we import [Brigadier](https://github.com/Mojang/brigadier) ?
I like it very much.

**Comment by KorewaLidesu** [comment]
We could, but that may be low priority.
Also what about the compatibility with other mods register their commands?

**Comment by Rongmario** [comment]
embeddedt wrote some [WIP stuff in Millennium](https://github.com/CleanroomMC/Millennium/tree/brigadier) a while ago that was to make Brigadier work in 1.12, other than great completion mechanics, I wonder if the API itself is worth it.

**Comment by Rongmario** [comment]
Closing this here, this is more of a [proposal](https://github.com/CleanroomMC/Cleanroom/discussions).
