### ISSUE TITLE
FML I18n Error

### ISSUE THREAD

**Issue by Ecdcaeb** [CleanroomMC/Cleanroom#34]
I meet i18n error when running Cleanroom.
the translationkey start with "fml" will not be translated.
![image](https://github.com/CleanroomMC/Cleanroom/assets/107909747/071db419-70b2-4cb8-bcff-50750df0919c)

version : https://github.com/CleanroomMC/Cleanroom/commit/5c42b8ec55d16de0669f35f3085ea69a0a8b18fb

**Comment by kappa-maintainer** [comment]
In development the default Forge resource won't load, that's a known bug
Did you encounter similar errors in production?

**Comment by Ecdcaeb** [comment]
I have not tested yet.
But it is normal in Forge2768.

**Comment by kappa-maintainer** [comment]
So test it in production Cleanroom, if it displays normally that's a known and wip bug

**Comment by Ecdcaeb** [comment]
> So test it in production Cleanroom, if it displays normally that's a known and wip bug

But in development. The error happened in the key start with "fml" , not all. Actually, other keys work correctly.

**Comment by kappa-maintainer** [comment]
That's simple, they were from vanilla resource
In fact, if you set a combo key in key controls, you will find a key description "forge.controlsgui.shift" instead of localized string
Next time please ask in Discord first before opening an issue

**Comment by kappa-maintainer** [comment]
Btw we will fix this in Cleanroom Gradle, so won't fix
