### ISSUE TITLE
[Launch Crash]java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.client.gui.FontRenderer

### ISSUE THREAD

**Issue by OcrSu** [CleanroomMC/Cleanroom#36]
When I launch the game using the PCL2 launcher, Java21, the game crashes.

JVM parameters and file validation is turned off.

CPU:Ryzen7 5700X   |   Win10 x64  |  GPU:AMD RX6800

Crash Log: https://gist.githubusercontent.com/OcrSu/b0f210383882463ab7d2e7865175484e/raw/gistfile1.txt

**Comment by kappa-maintainer** [comment]
Looks like PCL is loading the game with legacy mojang icu4j, please report to its author and use a decent launcher like HMCL, polymc or Prism
