### ISSUE TITLE
Crash with Xaero's Minimap

### ISSUE THREAD

**Issue by MPCQUQ666** [CleanroomMC/Cleanroom#38]
[crash-2024-01-12_20.51.34-client.txt](https://github.com/CleanroomMC/Cleanroom/files/13919319/crash-2024-01-12_20.51.34-client.txt)

**Comment by kappa-maintainer** [comment]
How to reproduce the crash? I found the cause of this, but still need to test if the fix works

**Comment by MPCQUQ666** [comment]
Can you speak Chinese?

**Comment by kappa-maintainer** [comment]
Please contact with Chinese in Discord server
https://discord.gg/f2K4aSpG4F

**Comment by kappa-maintainer** [comment]
Fixed in Fugue 0.3.4
