### ISSUE TITLE
放后台切屏后崩溃

### ISSUE THREAD

**Issue by 623667595** [CleanroomMC/Cleanroom#45]
[crash-2024-01-18_03.04.38-client.txt](https://github.com/CleanroomMC/Cleanroom/files/13967855/crash-2024-01-18_03.04.38-client.txt)客户端里有censoredasm5.6 不知道什么原因 正常游玩没问题 切屏就崩溃回到主界面

**Comment by kappa-maintainer** [comment]
请找出最小触发模组组合，优先测试涉及UI的模组

**Comment by 623667595** [comment]
已测试和 换行修复WrapFix-1.1.1-beta 冲突

**Comment by kappa-maintainer** [comment]
这模组已经整合进cleanroom了，删掉即可

**Comment by 623667595** [comment]
> 这模组已经整合进cleanroom了，删掉即可
cleanroom-15.24.0.3028-installer
 我安装了最新的 一启动就炸 我删掉fugue 就进去了 但是很多模组不兼容了

**Comment by kappa-maintainer** [comment]
fugue还没更新呢，急啥
