### ISSUE TITLE
Sound broken with More Sound Config

### ISSUE THREAD

**Issue by jchung01** [CleanroomMC/Cleanroom#48]
Upon adding the [More Sound Config](https://www.curseforge.com/minecraft/mc-mods/more-sound-config) mod, there is no sound.
[latest.log at relevant line](https://mclo.gs/ObtymgC#L84)
I'm assuming it's because the mod is expecting `alcCloseDevice()` from [the path](https://github.com/ichttt/SoundDeviceOptions/blob/master/src/main/java/ichttt/mods/moresoundconfig/SoundDevices.java#L70) `org.lwjgl.openal.ALC10` but Cleanroom has the method in [a different path](https://github.com/CleanroomMC/Cleanroom/blob/main/src/main/java/org/lwjgl/openal/AL10.java#L26) `org.lwjgl.openal.AL10`?
Using Cleanroom 15.24.0.3028.

**Comment by kappa-maintainer** [comment]
Our lwjglx was copied from lwjgl3ify, which used a script to automatically generate most delegates and misplaced many methods
We will fix this method soon

**Comment by kappa-maintainer** [comment]
Please try the latest commit

**Comment by jchung01** [comment]
Same error, looks like return type needs to be `boolean`.

**Comment by kappa-maintainer** [comment]
Another commit ...

**Comment by jchung01** [comment]
Yep, looks like the sound is fixed now.
