### ISSUE TITLE
mc crashes on world creation

### ISSUE THREAD

**Issue by uTa4u** [CleanroomMC/Cleanroom#50]
when loading without vintagefix and loliasm it crashes a bit later (on world loading i guess)
[crash-2024-02-09_20.58.17-server.txt](https://github.com/CleanroomMC/Cleanroom/files/14224884/crash-2024-02-09_20.58.17-server.txt)

**Comment by Rongmario** [comment]
Can I have the whole log file and not just the crash report?

**Comment by kappa-maintainer** [comment]
No respond for a month, will close the issue for now
