### ISSUE TITLE
Incompatibilities Found 

### ISSUE THREAD

**Issue by aking4125** [CleanroomMC/Cleanroom#52]
_Sorry if this is not the issue page to submit reports about this but:_

With the help of this: https://github.com/CleanroomMC/CleanroomMMC

The following mods crashes upon booting:

[BiblioCraft](https://github.com/Nuchaz/BiblioCraft) - [crash-2024-02-10_06.49.02-client.txt](https://github.com/CleanroomMC/Cleanroom/files/14229195/crash-2024-02-10_06.49.02-client.txt)
[BiomesOPlenty](https://github.com/Glitchfiend/BiomesOPlenty) - [crash-2024-02-10_06.52.06-client.txt](https://github.com/CleanroomMC/Cleanroom/files/14229189/crash-2024-02-10_06.52.06-client.txt)
[CarryOn](https://github.com/Tschipp/CarryOn) - [crash-2024-02-10_06.56.34-client.txt](https://github.com/CleanroomMC/Cleanroom/files/14229190/crash-2024-02-10_06.56.34-client.txt)
[Decocraft](https://legacy.curseforge.com/minecraft/mc-mods/decocraft) - [crash-2024-02-10_06.58.39-client.txt](https://github.com/CleanroomMC/Cleanroom/files/14229191/crash-2024-02-10_06.58.39-client.txt)
[Champions](https://github.com/TheIllusiveC4/Champions) - [crash-2024-02-10_07.00.41-client.txt](https://github.com/CleanroomMC/Cleanroom/files/14229192/crash-2024-02-10_07.00.41-client.txt)

We are also using [Fugue](https://github.com/CleanroomMC/Fugue)

Using Azul Zulu: 21.32.17

Sorry if this isn't the place to report this.

**Comment by kappa-maintainer** [comment]
Can confirm all of them are either classloading problem or module problem

**Comment by kappa-maintainer** [comment]
Nothing crashes on test branch now

**Comment by aking4125** [comment]
Where would I apply these changes? I tried downloading the latest arifacts for [CleanroomMMC](https://github.com/CleanroomMC/CleanroomMMC) and [Fugue](https://github.com/CleanroomMC/Fugue) but I get the same issues.

**Comment by kappa-maintainer** [comment]
*On experimental branches
