### ISSUE TITLE
Incompatibilities

### ISSUE THREAD

**Issue by Plootie** [CleanroomMC/Cleanroom#53]
I'm trying to get DDSS running with cleanroom and encountered 4 mods that didn't wanna play nice.

[VanillaFix](https://github.com/CleanroomMC/Cleanroom/files/14230903/vanillafix.crash-2024-02-11_00.26.48-client.txt)

[Solar Flux Reborn](https://github.com/CleanroomMC/Cleanroom/files/14230904/solar.flux.debug.log)

[Phosphor lighting enginet](https://github.com/CleanroomMC/Cleanroom/files/14230905/Phosphor.crash-2024-02-11_00.24.06-client.txt)

[Sledgehammer](https://github.com/CleanroomMC/Cleanroom/files/14230906/sledgehammer.debug.log)

**Comment by kappa-maintainer** [comment]
VanillaFix: use censoredASM + VintageFix instead
Solar Flux Reborn: update to latest version (12.4.11)
Phosphor: use Hespherus or Alfheim lib or Sodium 1.12 instead
Sledgehammer: too hackery to patch, just disable it for now

**Comment by Plootie** [comment]
> VanillaFix: use censoredASM + VintageFix instead Solar Flux Reborn: update to latest version (12.4.11) Phosphor: use Hespherus or Alfheim lib or Sodium 1.12 instead Sledgehammer: too hackery to patch, just disable it for now

Thanks! This got me to the main menu, however i'm now getting a crash on world creation from 
[Corail Tombstone](https://github.com/CleanroomMC/Cleanroom/files/14230966/crash-2024-02-11_01.06.46-server.txt)

**Comment by jchung01** [comment]
Just to add, Sledgehammer should work if you use its latest version (2.0.25) with default configs at least. It probably wouldn't hurt to try updating Corail Tombstone as well. DDSS is an old modpack after all.

**Comment by Plootie** [comment]
Tried updating tombstone which has led to a crash on startup from lootbags on its latest version
[crash-2024-02-11_01.54.43-client.txt](https://github.com/CleanroomMC/Cleanroom/files/14231036/crash-2024-02-11_01.54.43-client.txt)

**Comment by Rongmario** [comment]
Can you give the full log for your latest run? Both issues are caused by Google's Guava library since we've updated it.

**Comment by Plootie** [comment]
Sure 
[latest.log](https://github.com/CleanroomMC/Cleanroom/files/14231043/latest.log)

**Comment by kappa-maintainer** [comment]
Try [Lootbag Patches](https://www.curseforge.com/minecraft/mc-mods/lootbag-patches)?
It works well in my test instance
