### ISSUE TITLE
`Thaumic Speedup` mod probably not working

### ISSUE THREAD

**Issue by Krutoy242** [CleanroomMC/Cleanroom#61]
Thaumcraft requre 20+ seconds to load.

Spark game loading profiler shows that method `thaumcraft.common.config.ConfigAspects.postInit()` took 20+ seconds to load.

### https://spark.lucko.me/IUXt4qcv0A

![image](https://github.com/CleanroomMC/CleanroomMMC/assets/936618/fb3ca87f-1000-4103-a888-b5f48e244a9d)

As i understand correct, its aspect generation and its should be handled by mod [Thaumic Speedup](https://www.curseforge.com/minecraft/mc-mods/thaumic-speedup). On Java 8 its took 3-5 seconds or even less.

### [debug.log](https://mclo.gs/iIngw8W)

**Comment by ZZZank** [comment]
`Thaumic Speedup` is indeed not working, due to usage of an outdated API. 
Fugue 0.14.7 provides a patch for it, as a temporary solution this mod gets updated. 
Give it a try?

**Comment by Krutoy242** [comment]
I will maybe try!

**Comment by Rongmario** [comment]
Closing as older MixinBooter API isn't shaded in. Will update Thaumic Speedup.
