### ISSUE TITLE
`genPatches` does not check the `import`

### ISSUE THREAD

**Issue by Ecdcaeb** [CleanroomMC/Cleanroom#69]
Is it normal?
I noticed it does not check the `import` when genPatches for #68 .

else:
https://github.com/CleanroomMC/Cleanroom/blob/main/patches/minecraft/net/minecraft/advancements/AdvancementRewards.java.patch#L7

**Comment by Rongmario** [comment]
Yes it is as intended, you have to qualify your imports.
