### ISSUE TITLE
ProjectE's Dark Matter axe causes a crash when the skill cuts a tree.

### ISSUE THREAD

**Issue by erialsan** [CleanroomMC/Cleanroom#72]
Title, this did not happen in the exact same environment at FORGE, so perhaps the clean room is the cause.
It also occurred in cleanroom + cleanroom mods (Fugue, Vintagium, LoliASM, VintageFix) only.
This leads me to believe that the Dark Matter Axe skill is buggy.

**Comment by Rongmario** [comment]
Crash report + log file please?

**Comment by erialsan** [comment]
Create and prepare a minimum reproducible configuration.

**Comment by kappa-maintainer** [comment]
Can't reproduce, please provide crash report and latest.log

**Comment by erialsan** [comment]
I forgot to verify it while I was busy.
I'll do it now.

**Comment by erialsan** [comment]
Skills other than axe can be activated.
Only evaporation of trees by axe does not work.

**Comment by erialsan** [comment]
In the meantime, I will send you a Log. I may be able to find out something.

**Comment by erialsan** [comment]
https://mclo.gs/WRAM45e

**Comment by Ecdcaeb** [comment]
might some block do not have their own Item. So, ItemStack is empty.

**Comment by Rongmario** [comment]
Closing as it's confirmed to be ProjectE's bug.
