### ISSUE TITLE
possible codechickenlib Incompatibility 

### ISSUE THREAD

**Issue by thiccmeme** [CleanroomMC/Cleanroom#80]
### Cleanroom Version

15.24.0.3029

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

[crash-2024-02-28_17.29.37-client.txt](https://github.com/CleanroomMC/Cleanroom/files/14441333/crash-2024-02-28_17.29.37-client.txt)

### Mod List

ancientwarfaretweaked
codechickenlib
configanytime
hmb's nuclear tech 
libnine
mantle
roughlyenoughid's
RTG unoffical
Tinkers construct
vintage fix

### MMC Instance Notes

N/A

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Install Fugue
https://github.com/CleanroomMC/Fugue
Btw I think I have mentioned that in README?
