### ISSUE TITLE
Immersive Engineering cause crash.

### ISSUE THREAD

**Issue by LingJiuQiSan** [CleanroomMC/Cleanroom#84]
### Cleanroom Version

15.24.0.3029

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

[latest.log](https://github.com/CleanroomMC/Cleanroom/files/14486313/latest.log)
[debug.log](https://github.com/CleanroomMC/Cleanroom/files/14486315/debug.log)
[crash-2024-03-05_03.34.07-client.txt](https://github.com/CleanroomMC/Cleanroom/files/14486322/crash-2024-03-05_03.34.07-client.txt)

### Mod List

ImmersiveEngineering-0.12-98
Fugue-1.12.2-0.5.4

### MMC Instance Notes

I use installer to install cleanroom.

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [x] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fixed this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
This was caused by launcher loaded the wrong ICU4J
Please use an approved launcher like HMCL or PrismLauncher
