### ISSUE TITLE
Incompatible with CustomSkinLoader

### ISSUE THREAD

**Issue by AnzOOCH** [CleanroomMC/Cleanroom#90]
### Cleanroom Version

15.24.0.3029

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

[latest.log](https://github.com/CleanroomMC/Cleanroom/files/14574301/latest.log)

### Mod List

CustomSkinLoader_ForgeLegacy-14.19.1.jar
(only 1)

### MMC Instance Notes

Nope. Used HMCL instead.

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fixed this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by KasumiNova** [comment]
Try using version 14.11?

**Comment by kappa-maintainer** [comment]
Should have fixed in latest Fugue
