### ISSUE TITLE
The latest Cleanroom is incompatible with VintageFix

### ISSUE THREAD

**Issue by erialsan** [CleanroomMC/Cleanroom#91]
### Your CleanroomMC Discord Username

erialsan

### Cleanroom Version

15.24.3031

### Java Version

Java 21

### Graphics Card Vendor

Intel iGPU

### Bug Report

https://mclo.gs/GotVgTn
There are other mods for this, but later confirmation of a similar crash occurred only with VintageFix!

### Mod List

VintageFix（Latest）

### MMC Instance Notes

Yes

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fixed this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by erialsan** [comment]
When trying to enter the world, the entire screen turns sky blue and then crashes.
I've tried several versions of Fugue, UniversalTweaks, and other mods that may fix the bug, and I've also tried VintageFix with the latest builds, but no luck!

**Comment by kappa-maintainer** [comment]
Try latest MMC+fugue 0.9.4+

**Comment by erialsan** [comment]
That's the version that was published half an hour ago!
I will try it after I finish my meal!

**Comment by erialsan** [comment]
Issue resolved. With the latest Cleanroom and Fugue

**Comment by erialsan** [comment]
It no longer crashes on startup, but I still get the biome color problem with certain mod configurations.
Worst of all, there is no crash report and the Log only says fatal error.

**Comment by kappa-maintainer** [comment]
What's your "certain mod configurations"?
I am running a tekkit 2 instance, everything except the clouds look normal
I have updated Cleanroom and Fugue 3 to 4 times in past hours, please check with latest build
Remember to delete fugue config so you can get a new default one!

**Comment by erialsan** [comment]
It is cured for now, but I will test it in several environments because the bug occurred again when I thought it was cured before.
At least we have confirmed that it works on SkyOdyssey!

**Comment by jchung01** [comment]
The crash should be fixed if you use latest VintageFix build (https://nightly.link/embeddedt/VintageFix/workflows/gradle/main/Package.zip), specifically this commit https://github.com/embeddedt/VintageFix/commit/a24848d91d63e385eb5fb8cf2218dfe0824c7748.

**Comment by erialsan** [comment]
We have confirmed that it can be cured. However, it outputs a horrible number of WARNs at startup.
There seems to be some problem, so we will monitor the progress. I will close this issue temporarily.
