### ISSUE TITLE
Keybinding only registers Qwerty

### ISSUE THREAD

**Issue by BigBoss1941** [CleanroomMC/Cleanroom#96]
### Your CleanroomMC Discord Username

thermonuclear_minecraft_engineer

### Cleanroom Version

The stable branch

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

When trying to assign keys, the key input is registered in Qwerty. outside of that, the game registers azerty correctly. IE: when moving, pressing the pre-assigned Z button allows me to move, as is the case in java 8. but assigning the key W to the ''Throw item"

### Mod List

none, having fugue installed doesn't change anything either

### MMC Instance Notes

This instance is built using Github Action.
Using installer artifact from commit: 45ed7e7f4eb566da65c375ee22cef2423de9a2d2
Action URL: https://github.com/CleanroomMC/Cleanroom/actions/runs/8229431020

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fixed this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by BigBoss1941** [comment]
Newest PR seems to have fixed this issue, so maybe it should be closed?

**Comment by Rongmario** [comment]
Issue still exists with modifiers + key code combos, should probably be a separate issue.
