### ISSUE TITLE
Incompatible with SmoothFont

### ISSUE THREAD

**Issue by ChenHaoYan1234** [CleanroomMC/Cleanroom#99]
### Cleanroom Version

15.24.0.3032

### Java Version

Java 21

### Graphics Card Vendor

Mesa/Software

### Bug Report

[latest.log](https://github.com/CleanroomMC/Cleanroom/files/14647113/latest.log)
[crash-2024-03-19_15.39.10-client.txt](https://github.com/CleanroomMC/Cleanroom/files/14647114/crash-2024-03-19_15.39.10-client.txt)

### Mod List

Only smoothfont 2.1.4

### MMC Instance Notes

nothing

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fixed this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by erialsan** [comment]
It is supposed to be a fix, or rather, it will be built into Cleanroom.
I also confirmed this (at SkyOdyssey).

**Comment by kappa-maintainer** [comment]
Should have fixed in latest Fugue
